### PR TITLE
NA - fan-in debug url

### PR DESCRIPTION
**Pull request by srinivasupadhya**
Introduced route - `<go-server>/go/api/fanin_debug/<pipeline-name>/<iteration>` which provides JSON response containing all upstream dependencies with values of their SCM revisions pegged at selected iteration

### CODE REVIEW

**Comment by arvindsv** [comment]
Took a quick look. It didn't seem to do anything when I hit ```http://localhost:8153/go/api/fanin_debug/Test-Down/0``` with a config like this:

```
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="75">
  <server artifactsdir="artifacts" commandRepositoryLocation="default" serverId="ba884b1b-9f33-4424-9228-925150a9aba6" />
  <pipelines group="defaultGroup">
    <pipeline name="Test1">
      <materials>
        <git url="/tmp/test.git" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
    <pipeline name="Test2">
      <materials>
        <git url="/tmp/test.git" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
    <pipeline name="Test-Down">
      <materials>
        <pipeline pipelineName="Test1" stageName="defaultStage" materialName="Test1" />
        <pipeline pipelineName="Test2" stageName="defaultStage" materialName="Test2" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
  <agents>
    <agent hostname="localhost" ipaddress="192.168.0.104" uuid="d44e4c4e-9fde-4fa7-a687-652069e493cc" />
  </agents>
</cruise>
```

**Comment by ketan** [comment]
Any particular reason this does not follow the new conventions laid out in #1100?

Also, would it make sense to move this under the URL `/go/api/support/fanin_debug/:pipeline_name`

**Comment by srinivasupadhya** [comment]
@arvindsv - i have updated the PR. Now `<go-server>/go/api/fanin_debug/<pipeline-name>` gives initial data, `<go-server>/go/api/fanin_debug/<pipeline-name>/<iteration>`  gives data for that iteration, if the iteration count is > than the number of iterations it takes to finish resolution it gives final output.

@ketan - it does not follow conventions because its just for debug purposes & also the json is created through GSon & im not sure how easy/hard it is to confirm to the convention.

**Comment by ketan** [comment]
> @ketan - it does not follow conventions because its just for debug purposes & also the json is created through GSon & im not sure how easy/hard it is to confirm to the convention.

There is no reason to render it via GSon, also you won't know how hard/easy it is until you try :)

**Comment by srinivasupadhya** [comment]
merging this myself since i need to work on #1291. @arvindsv please review PR & let me know if i need to make any changes. Will create separate PR with suggested changes.

**Pull request merged**
