### PR TITLE
Delete pluggable scm API (#4967)

### PR DESCRIPTION
**Pull request by varshavaradarajan**
Request:
```
curl -i 'https://ci.example.com/go/api/admin/scms/pluggable.scm.name' \
      -u 'admin:badger' \
      -H 'Accept:application/vnd.go.cd.v1+json' \
      -X DELETE
```

Response:
```
Scm deleted successfully if valid
Associated pipelines list
```

The API is accessible to admins and group admins. Just like the other SCM APIs.

### CODE REVIEW

**Comment by ketan** [comment]
Update the API docs? There is also a changelog in there now.

**Comment by varshavaradarajan** [comment]
Thanks @ketan. Will do

**Comment by maheshp** [comment]
@ketan @varshavaradarajan shouldn't we be bumping up the version of the API?

**Comment by varshavaradarajan** [comment]
No. There was no delete API before. The contract has not been changed to warrant a new API version. We have done this many times before. From what I remember, template config and template auth API. There were other examples too..

**Comment by maheshp** [comment]
There was a similar conversation on https://github.com/gocd/gocd/pull/6395

**Comment by varshavaradarajan** [comment]
https://github.com/gocd/gocd/pull/6395#issuecomment-500889863 - new feature added or removed from the existing API, right? Not for adding a new API.

**Pull request merged**
