### PR TITLE
Allow adding some metadata for jobs that should be run via elastic agent plugins (#1082)

### PR DESCRIPTION
**Pull request by ketan**
```xml
<job>
  <agentConfig pluginId="...">
    <property>
      <key>Dockerfile</key>
      <value>Dockerfile.example</value>
    </property>
  </agentConfig>
</job>
```

### CODE REVIEW

**Comment by ketan** [comment]
@arvindsv — we've currently set this to allow either `<resources/>` or `<agentConfig/>` but not both.

That look ok to you?

**Comment by arvindsv** [comment]
Ok. Ideally, it's only one. But I guess it'll have to be something like this (if only one):

```
<agentConfig pluginId="go-server">
  <key>resources</key>
  <value>resource1 resource2 resource3</value>
</agentConfig>
```

which is a little icky, since it has a go-server plugin ID and resources are not separated. So, your option is fine, I guess.

**Comment by ketan** [comment]
> which is a little icky, since it has a go-server plugin ID and resources are not separated. So, your option is fine, I guess.

It's also icky because "resources" is going to be a reserved-words of sorts for other purposes (agents page, apis etc)

**Comment by arvindsv** [comment]
Ok, I understand.

**Pull request merged**
