### PR TITLE
Port over agent job history api to spark

### PR DESCRIPTION
**Pull request by ketan**
Issue: #7269

### CODE REVIEW

**Comment by ketan** [comment]
API:

<details>
<summary>Click to expand
<pre>
GET /go/api/agents/:uuid/job_run_history
Accept: application/vnd.go.cd.v1+json
</pre>
</summary>

```
{
  "_links": {
    "doc": {
      "href": "https://api.gocd.org/19.11.0/#agent-job-run-history"
    },
    "self": {
      "href": "http://localhost:8153/go/api/agents/ebe15c24-181f-4e54-85a8-fb4c5b3ca3cb/job_run_history"
    },
    "find": {
      "href": "http://localhost:8153/go/api/agents/:uuid"
    }
  },
  "uuid": "ebe15c24-181f-4e54-85a8-fb4c5b3ca3cb",
  "jobs": [
    {
      "job_state_transitions": [
        {
          "state_change_time": "2019-11-12T00:20:56Z",
          "state": "Scheduled"
        },
        {
          "state_change_time": "2019-11-12T00:21:06Z",
          "state": "Assigned"
        },
        {
          "state_change_time": "2019-11-12T00:21:17Z",
          "state": "Preparing"
        },
        {
          "state_change_time": "2019-11-12T00:22:19Z",
          "state": "Building"
        },
        {
          "state_change_time": "2019-11-12T00:37:42Z",
          "state": "Rescheduled"
        }
      ],
      "job_name": "jasmine",
      "stage_name": "build-non-server",
      "stage_counter": "1",
      "pipeline_name": "build-windows-PR",
      "pipeline_counter": 5282,
      "result": "Unknown",
      "rerun": false
    }
  ],
  "pagination": {
    "page_size": 100,
    "offset": 792,
    "total": 793
  }
}
```
</details>

---

Supported query params:

| Name          | Required | Description                                                                                                                             |
| ------------- | -------- | --------------------------------------------------------------------------------------------------------------------------------------- |
| `offset`      | No       | The offset of the records within the total number of records available. Useful for pagination. Defaults to `0`                          |
| `page_size`   | No       | The number of records per page. Defaults to `50`                                                                                        |
| `sort_column` | No       | The column to sort the data on. Can be one of `pipeline`, `stage`, `job`, `result`, `completed` or `duration`. Defaults to `completed`. |
| `sort_order`  | No       | The sort order. Can be `ASC` or `DESC`. Defaults to `DESC`.                                                                             |

---

Changes from the unversioned API

- Using query params instead of path params
- Removal of job's `id`, `original_job_id` and `job_state_transitions`' `id`  properties in response. These are internal DB IDs, and are unusable for end-users.
- Remove `duration` field. What this meant was ambiguous (build time? does it include wait time or prepare time?)
- Remove `state` field. This was a copy of the last job-state-transition's `state` attribute.
- Rename `name` field to `job_name` to make it less-ambiguous

**Comment by ketan** [comment]
Edit: Do not support `sort_column` value `duration`, since I've mentioned in my previous comment how it is ambiguous.

**Comment by kritika-singh3** [comment]
The support for `page_size` will also address https://github.com/gocd/gocd/issues/3326

**Comment by ketan** [comment]
API docs at https://github.com/gocd/api.go.cd/pull/526.

**Pull request merged**
