### PR TITLE
Add support for rules in config repo api and spa

### PR DESCRIPTION
**Pull request by kritika-singh3**
Issue: #7605 

Description: Added support for `rules` in config-repo in API v3 and SPA

### CODE REVIEW

**Comment by kritika-singh3** [comment]
Preview:

config_repo_rules_ui

**Comment by arvindsv** [comment]
Maybe add a sentence around the "Rules" section telling users what they're configuring? It looks really similar to the granular auth. So, it might not be clear.

**Comment by kritika-singh3** [comment]
@arvindsv How about this message:

`Configure rules to allow what environment/pipeline group/pipeline this config repo can refer to. By default, all entities will be denied.`

**Comment by arvindsv** [comment]
@kritika-singh3 I like that message.

**Comment by kritika-singh3** [comment]
On increasing the size of the modal to `Size.large` and adjusting the width and margin of the input fields, the modal now looks as:

Screen Shot 2020-02-10 at 11 51 51 AM

Screen Shot 2020-02-10 at 11 52 02 AM

Does this look ok.?
@maheshp @GaneshSPatil @arvindsv @bdpiparva @ketan

**Comment by kritika-singh3** [comment]
Preview of config-repo modal:

config-repo-modal-large

**Pull request merged**
