### PR TITLE
removed feature toggle color_logs_feature_toggle_key - #1649

### PR DESCRIPTION
**Pull request by alexschwartz**
tried to remove feature toggle 'color_logs_feature_toggle_key' - #1649
builds fine locally

### CODE REVIEW

**Comment by ketan** [comment]
Hi, there is also some code in build_output_observer.js, that may be related. I have not seen it in a while, but when implementing this feature, I recalling making some changes there.

**Comment by alexschwartz** [comment]
Hi, thanks for mentioning it. There is indeed more code to be removed -- I just passed "true" for a parameter which is actually obsolete.

**Comment by ketan** [comment]
hey @jyotisingh @zabil — could you look into why the PR plugin is not reporting status here?

**Comment by ketan** [comment]
@alexschwartz thank you for your contribution. The next experimental build at http://www.go.cd/download will have your changes in it.

**Pull request merged**
