### PR TITLE
pac builder form changes

### PR DESCRIPTION
**Pull request by ibnc**
* config file lang selection now under builder form
* Numbered the steps

Related to #7152

### CODE REVIEW

**Comment by ibnc** [comment]
screenshot of what's currently in this PR:

Screen Shot 2019-11-07 at 10 48 32

**Comment by ibnc** [comment]
Screenshot from latest commit:


Screen Shot 2019-11-07 at 11 02 46

**Comment by ibnc** [comment]
Updated screenshot after feedback:


Screen Shot 2019-11-07 at 14 03 24

**Comment by marques-work** [comment]
@ibnc what do you think of 1b46452?

I gave a shot at a different approach for the layout fix because I was somewhat concerned about using `47.65%` which felt like a magic number. I ~think~ hope that it captures the intent of the SCSS rules to make the columns equal width while allowing the browser to calculate any width adjustments via `flex-shrink` and `flex-grow`. It was my hope that it would also be more robust across browsers.

**Pull request merged**
