### PR TITLE
Introduce iframe window messaging endpoint helper

### PR DESCRIPTION
**Pull request by marques-work**
Added ExtensionIFrameEndpoint helper object to:

- ensure listener is established in parent window
- handle dispatch of messages based on keys
- simple wrappers to send and reply to key-based messages

Refactored analytics modal script to use this.

@maheshp could you review this when you get a chance? thanks!

### CODE REVIEW

**Comment by kierarad** [comment]
@maheshp this is marques (not kiera) - let's figure out a time to sync up and review the code.

**Comment by maheshp** [comment]
@marques-work I was talking to @ketan to get his opinion. One of the things he brought up was around the plugin-endpoint.js caching. All assets under `public` have a long lived cache. That would mean any changes to `plugin-endpoint.js` would not reflect since the file name is appended by a hash. Adding a hash to the file name would mean the plugins will not be able to refer to them.

The other thing to consider/think about is how would the plugin handle changes to the `plugin-endpoint.js`, wouldn't changes to the JS API break things for the plugin. In that case should we consider versioning the JS API as well?

**Comment by marques-work** [comment]
@maheshp @ketan interesting point. Even though it's installed in the hashed directory for the plugin, it's still possible for it to go stale so long as the plugin assets' content doesn't change.

I suppose we will need to version these then, and possibly maintain several versions.

Or, update the SHA-256 digest with the plugin-endpoint.js contents as well. That would certainly take care of all caching issues.

**Comment by ketan** [comment]
> Even though it's installed in the hashed directory for the plugin

"hashed directory for the plugin" seems interesting, care to elaborate?

**Comment by ketan** [comment]
>> Even though it's installed in the hashed directory for the plugin
> 
> "hashed directory for the plugin" seems interesting, care to elaborate?

My point is that if the base directory out of which everything is served works to bust the cache, we might be good and no changes may be needed. `/go/assets/${PLUGIN_ID}-${LONG_HASH}/foo.{js,css,img}`

The LONG_HASH might just mean a (secure) random string generated everytime the plugin is loaded.

**Comment by marques-work** [comment]
@ketan - sure :).

When we pull the zipped static assets payload from the plugin, we explode it into a directory whose name is the SHA-256 hash of zip payload bytes. That ensures that when the plugin assets content changes, the URI path to the assets changes too, which takes care of browser caching issues. This happens each time an analytics plugin is loaded, which is, for the most part, once at startup.

However, the plugin-endpoint.js content is not included in the SHA-256 digest, so if someone upgrades GoCD (and the content of that script changes), but keeps the same plugin version, one could still load a stale plugin-endpoint.js from the iframe.

Unless of course, we calculate the SHA-256 against the plugin-endpoint.js script as well.

**Comment by marques-work** [comment]
@ketan that was my initial thought too, but the plugin-endpoint.js is **copied from GoCD** into the hashed directory, which means if only that file updates, the browser may use a stale version unless we generate the hash on the combined content of the plugin assets zip payload and plugin-endpoint.js

**Comment by marques-work** [comment]
@ketan I see what you mean -- let the LONG hash be unique and unpredictable instead of content based. That would work too. I guess our initial thoughts were to invalidate only when content actually changes and utilize the browser hash when we can. For our plugin, we have few assets so it might be ok. However, we can't guarantee other plugin authors won't load a bunch of stuff.

Using a GUID instead is a very simple change though, I admit :).

**Comment by ketan** [comment]
> @ketan I see what you mean -- let the LONG hash be unique and unpredictable instead of content based. That would work too. I guess our initial thoughts were to invalidate only when content actually changes and utilize the browser hash when we can. For our plugin, we have few assets so it might be ok. However, we can't guarantee other plugin authors won't load a bunch of stuff.

I hear your concern about plugin authors loading a bunch of stuff, and the cache busting on clients because of a server reboot for no good reason.

I think doing this might be a good enough middle-ground:

* package the `plugin-endpoint.js` in assets dir (for the rails app). Likely part of `application.js` or something based on whatever the sprockets gem does.
* package the `plugin-endpoint.js` AS-IS (without compression, or sha in the name) somewhere on the classpath (like how it's being done [here](https://github.com/gocd/gocd/pull/4155/files#diff-2af3da569e27d5fad9d8c14613c35a66R546))
* the base-dir for your plugin assets becomes a function of zip file contents and the contents of the original `plugin-endpoint.js` on the classpath

This will avoid having to go through the `RailsAssetService` for resolving the actual path at runtime.

**Comment by marques-work** [comment]
@ketan yep, that's _EXACTLY_ what I was referring to :)

> we generate the hash on the combined content of the plugin assets zip payload and plugin-endpoint.js

But I probably didn't spell it out so clearly as you did.

The change to do that would be simple, as should involve just updating the hash with a second byte array.

**Comment by maheshp** [comment]
@marques-work @ketan generating the hash using the plugin_endpoint.js would solve the caching issue, but I am concerned with how to handle the JS API changes.

Instead, does it makes sense to version the JS API and make it available to the plugin authors(maybe thro the plugin-api.gocd.org). The plugins can use this JS and bundle it as part of its static assets.

GoCD would use the appropriate JS API based on the plugin version to pass messages to the plugin iframe.

**Comment by marques-work** [comment]
@maheshp right, back to the versioning question.

My thoughts are that we'll probably need to version as this JS API will be public so that plugin developers can use it. perhaps the api version could be a top-level namespace for the supported keys?

e.g. `v1.analytics.pipeline-charts`

maybe we could have several send methods that prepend the version to the key:

`sendv1()`, `sendv2()`, etc..

or just have separate `plugin-endpoint-v1.js`, `plugin-endpoint-v2.js` that plugin developers can include.

**Comment by ketan** [comment]
> Instead, does it makes sense to version the JS API and make it available to the plugin authors(maybe thro the plugin-api.gocd.org). The plugins can use this JS and bundle it as part of its static assets.

https://www.npmjs.com/ — that's the convention for distributing JS code, and all tooling works with this.

Might mean pulling out that JS into a git of its own with its own release cycle.

**Comment by marques-work** [comment]
@ketan wouldn't that lead to situations where the plugin-endpoint.js on the plugin is different than on the server? We decided that by serving it through Go server, we'd avoid this type of incompatibility.

Granted there's other incompatibilities issues to still deal with, like a plugin expecting a higher version of the JS API than the version of GoCD provides.

**Comment by marques-work** [comment]
@maheshp @ketan additionally, this script is just defining the connector and a means to define an API, _but not the API itself._ The API definition will likely be another script, packed into application.js that lays out the messages GoCD supports for plugins. Plugins won't need to import the API, they just need to write conforming messages against that standard.

**Comment by maheshp** [comment]
I was thinking the JS API version should be tied to the plugin version. Say a plugin implementing v1.0 of the endpoint will have to use JS API v1.0 and would get the corresponding messages. The script as you rightly said would just be a connector to handle these messages.

**Comment by ketan** [comment]
I don't have enough context around this, so perhaps I'm wrong. But my understanding it that sooner or later, the server (but not the plugin) will have backward compatibility to deal with — which means a couple of versions of the endpoint.js on the server and some sort of a way to negotiate what version of the JS the plugin uses.

We do this with most API contracts, and I don't believe this is any different.

**Comment by marques-work** [comment]
@ketan yeah, that's certainly correct as well, and we may end up with several versions of the connector living on the server under different namespaces. Needs some thought.

**Pull request merged**
