### PR TITLE
Bump up version of Config Repo target_version and add migration

### PR DESCRIPTION
**Pull request by akshaydewan**
cc: @arvindsv

### CODE REVIEW

**Comment by arvindsv** [comment]
@akshaydewan Looks good to me. But, shouldn't the v3_comprehensive.json file have external artifacts? Or, is that going to be changed as a part of a different PR?

Context for whoever is seeing this: This is preparation for support for [external artifacts](https://github.com/gocd/gocd/issues/4049) in config repos.

**Comment by akshaydewan** [comment]
@arvindsv Since the test is migrating from v2 to v3, I can't add external artifacts there. Instead I've added another test for v3 and that one contains external artifacts.

**Comment by arvindsv** [comment]
@akshaydewan Ok.

About [this](https://github.com/gocd/gocd/pull/4779/commits/a3a08e69468ef616cceec846c3aa07f1de2bba11#diff-56c2043ac5ed0f65b790cb794477dcd6R48), since it's JSON, we should be able to use something like:

```json
"configuration": {
  "Image": "gocddemo/guestbook",
  "Tag": "v5"
}
```

Right?

**Comment by arvindsv** [comment]
It might not matter much, since this is the API between the plugin and the GoCD server. Not the interface between the user (`*.gopipeline.json`) and the plugin. However, unless we care about the order, we don't need it to be an array.

**Comment by akshaydewan** [comment]
Currently the `ConfigConverter` uses the same format for Task plugins as well. Environment variables and Parameters also have a similar structure. If we do change it, we should try to make all of them consistent.

Btw, the JSON config repo plugin also uses a similar structure, but the YAML plugin is nicer. We can think of improving the JSON plugin (which is user facing) if not the contract between the server and plugin.

**Comment by arvindsv** [comment]
Yes. On second thoughts, I think changing the user-facing side is better use of time anyway. So, I am alright with this being this way (between plugin and server).

/cc @tomzo - FYI

**Comment by tomzo** [comment]
> Currently the ConfigConverter uses the same format for Task plugins as well. Environment variables and Parameters also have a similar structure. If we do change it, we should try to make all of them consistent.

@akshaydewan That's right. I like that you made the new one similar. I also think that this format is  convenient for the contracts and I would not change it.
And yes if we want JSON to be more concise, then the change should happen in plugin.

But I don't see any changes for the `ConfigConverter`, there should be some code creating new artifact config classes, is it still WIP or in another PR?

**Comment by varshavaradarajan** [comment]
@tomzo - https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/config/ConfigConverter.java#L174 and https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/config/ConfigConverter.java#L521 

Did you mean any other change?

**Comment by tomzo** [comment]
@varshavaradarajan thanks, I was looking for those. This looks OK to me now.

**Comment by varshavaradarajan** [comment]
@tomzo - given that we are differentiating between fetch from gocd and external by using `artifact_origin` (See #4888), I added a migration to add `"artifact_origin":"gocd"` on all fetch tasks if the `target_version` is 2. That okay? Can you please take a look?

**Comment by varshavaradarajan** [comment]
Also, @arvindsv and @tomzo - Should we retain all the migrations? I understand that people would have checked in jsons and yamls with target_version 1 and we don't want that to break. But for how long should we maintain those? Or is this something similar to API versioning? Should we throw an error if the target version is less than say, a minimum supported version?

**Comment by tomzo** [comment]
> I added a migration to add "artifact_origin":"gocd" on all fetch tasks if the target_version is 2. That okay? Can you please take a look?

Yes. 
@varshavaradarajan The code looks fine, minor things I would improve:
 - It would be nice to add a test which migrates from v1 up to v3 to checks that when all steps are executed the end result is as expected.
 - I would rename those older tests a bit `shouldMigrateToV2` to `shouldMigrateV1ToV2`

And  Test `shouldDoNothingIfMigratingFromV3ToV3` is failing though.

>  Should we retain all the migrations?

IMO we keep all migrations forever. It is an equivalent of the xsd migrations for cruise-config.xml. I don't see a reason to remove them.

> Should we throw an error if the target version is less than say, a minimum supported version?

We might want to set a warning in health messages, not an error. The reason would be to force users to update to newer format to reduce the overhead of migrations on server. Otherwise user has no reason to do so until new feature is needed.

**Comment by varshavaradarajan** [comment]
@tomzo - thanks, had to change the migration. Can you take a look again, please?

Regarding testing v1 to v3, there is a loop in JsonMessageHandler1_0 that calls individual migrations - that is, v1 to v2 and then v2 to v3. That's why I didn't think it was necessary to test v1 to v3 as long as we test that the migrator is called that many times. Let me know if you think otherwise. If so, I'll have to write a test in JsonMessageHandler1_0Test asserting on the json.

**Pull request merged**
