### PR TITLE
Fix for broken ui on timeline modal on compare spa

### PR DESCRIPTION
**Pull request by kritika-singh3**
Issue: #7808

Description:
 - changed from flex implementation  to table

### CODE REVIEW

**Comment by kritika-singh3** [comment]
Chrome:

Screen Shot 2020-03-12 at 2 10 51 PM

Firefox:

Screen Shot 2020-03-12 at 2 11 02 PM

**Comment by marques-work** [comment]
MS Edge :(
image

**Comment by GaneshSPatil** [comment]
@kritika-singh3 -  

1. As per the provided screenshots, the pipeline counter are split into 2 lines, which looked a bit misaligned to me.

2. Also, the stage tile(s) will occupy the remaining space, meaning, in case of 1 stage - 100% width, in case of n stages - (100/n)% width.
This was the similar case with old GoCD dashboard, in case of multiple stages, the stages would look cluttered, hence we moved to fixed width stage tile.

Can we do something similar? Show fixed width stage tile, and if there are more stages, overflow them to the next line?

\cc: @arvindsv @maheshp @marques-work - Thoughts?

**Comment by arvindsv** [comment]
If it's easier to be consistent with the dashboard, I'm fine with that. I don't know how that will look when there are tens of stages, though.

**Comment by maheshp** [comment]
Related PR with fixed width - https://github.com/gocd/gocd/pull/7863

**Pull request merged**
