### PR TITLE
Show SCM materials when creating a new pipeline

### PR DESCRIPTION
**Pull request by kszatan**
This PR tries to address issue #2947.

### CODE REVIEW

**Comment by rajiesh** [comment]
@kszatan , the failure of functional test case [here](https://build.gocd.org/go/tab/build/detail/acceptance-linux-PR/759/RunAcceptanceSpecs-priority/2/firefox-split-runInstance-4) is caused by an issue in the PR. The stage details page should not show both template and stage details.

Steps to reproduce,

1. Start the server with any SCM plugin included in its `<SERVER_WORKING_DIR>/plugins/external` folder
2. On Pipeline creation wizard fill in details and navigate to step 3 - Stage details
3. Could observer that the template and stage both shows up

Browser console log shows this error 

```
Error: Argument 'PluggableSCMConfigurationController' is not a function, got undefined
```

**Comment by kszatan** [comment]
I have fixed this error but now it seems there's another problem. Could you please help me figure it out? https://build.gocd.org/go/tab/build/detail/acceptance-linux-PR/777/RunAcceptanceSpecs-plugins/1/firefox-split-runInstance-3

**Comment by arvindsv** [comment]
@kszatan - What is happening with [this failure](https://build.gocd.org/go/files/acceptance-linux-PR/777/RunAcceptanceSpecs-plugins/1/firefox-split-runInstance-3/GaugeReports/reports/html-report/specs/CurlTaskPlugin.html) is that inline errors in plugins are getting lost.

To reproduce this, you need:

1. Download and install [this task plugin](https://github.com/gocd-contrib/task-skeleton-plugin/releases).
2. Create a new pipeline. Choose any material (even git material).
3. Choose "Curl" in the task dropdown.
4. Don't enter any URL.
5. Click Save.

Without this PR, you see this error:



With this PR, you see no error against that field.

Also, maybe more importantly, any other information you've entered into other fields gets lost. It looks like the responses from the plugin are not being bound back onto the form. Not in the new _pluggable_scm_form.html.erb, but in the older task one.

If you have some idea why, take a look at it. If not, let me know and I'll help. Thanks!

**Comment by kszatan** [comment]
OK, so the problem is that PluggableSCMConfigurationModule and TaskPluginView are both Anuglar applications that try to attach to the same form. They do basically the same thing but one for pluggable materials and the other one for pluggable tasks. I'll have to merge those scripts or think of a way to make them work alongside themselves without errors.

**Comment by arvindsv** [comment]
Sigh. This got missed. I saw your questions [on gitter](https://gitter.im/gocd/gocd?at=59f303caf7299e8f533b2353). Sorry about that, @kszatan. I'm going to spend some time thinking about what you said, tomorrow and reply to you.

**Comment by kszatan** [comment]
No problem! I have an idea and I'm trying to make it work right now.

**Comment by arvindsv** [comment]
Ok, take a look. The closest I remember to getting to this problem is with the task plugin. As you know, tasks can have on-cancel tasks. So, there can be two tasks, both plugin tasks, on the same page.

To get past this problem, I remember creating two `ng-app`s, so that there could be two separate Angular contexts on the same page. What is left of this code seems to be in [task_plugin_view.js](https://github.com/gocd/gocd/blob/3eebade2e7b833542c92ea0a027870aeb5399c14/server/webapp/WEB-INF/rails.new/app/assets/javascripts/task_plugin_view.js) and is used in many places, such as [this](https://github.com/gocd/gocd/blob/3eebade2e7b833542c92ea0a027870aeb5399c14/server/webapp/WEB-INF/rails.new/app/views/admin/tasks/pluggable_task/_form.html.erb#L20).

Would something like this work in this case?

**Comment by kszatan** [comment]
> So, there can be two tasks, both plugin tasks, on the same page.
... and in the same form! That's why there's this whole GOINPUTNAME html rewriting.

> Would something like this work in this case?
The problem I'm facing is that TaskPluginView attaches on the closest form (it has to b/c of how Angular form validations work) and when you have another plugin template in the same form (for example handled by PluggableSCMConfigurationModule) they will clash. Fortunately, the code inside TaskPluginView does what needs to be done for every plugin template (changing input names and wiring the template data returned from server). I'm writing a general Angular app to handle all plugin templates in a form at once, automatically, instead of executing inline JS.

The biggest problem is that I'm new to Angular and really learned the tool to fix this issue. It's a bit of a struggle :)

**Comment by arvindsv** [comment]
Oh, I can imagine! Thank you for doing this. I remember my struggle when I was doing this as well - and it's not "standard Angular" to make it do this.

It also doesn't help that it's inside ERBs. We want to rewrite that to get rid of ERBs, and use Mithril + JSX/MSX but it is not done yet.

Thanks again. I'll wait for you to try this approach - and if you need anything, let me know and I will try to respond quicker this time.

**Comment by kszatan** [comment]
OK, the latest commit solves this problem!

**Comment by kszatan** [comment]
@arvindsv It seems to be failing on some acceptance tests https://build.gocd.org/go/pipelines/value_stream_map/build-linux-PR/2305. I need a feedback.

**Comment by arvindsv** [comment]
@kszatan I took a look - and it seems fine to me. It's strange that all the functional tests failed to start the server. It's obviously nothing to do with your change. Maybe something has changed/needs to change in the way the server is started in the functional tests. I'm looking into it.

**Comment by arvindsv** [comment]
@kszatan What's happening is that this branch/PR needs to be rebased. Schema version of the config has been updated to 98 in the latest code, due to another PR. So, this one is failing to start the server in functional tests, because the tests have the config at a higher version.

I tried a rebase of this, and it seems simple. Just a couple of ruby spec files conflicted. If you rebase and push, I can trigger a new run. Thanks!

**Comment by arvindsv** [comment]
:( Well ... I lost track of this and it languished here and ended up conflicting, as would be expected. Sorry, @kszatan. It was my fault. I am closing this with the assumption that this has been too long for you to have context about this.

If not, let me know and I'll try and fix conflicts, since I led to this happening. Thank you! Apologies again.

**Comment by kszatan** [comment]
@arvindsv No problem. I got an impression that there's a new UI coming for GoCD and there's no interest in merging this PR. If that's not the case then I might have another crack at this when I find some time in the following weeks.

**Comment by arvindsv** [comment]
@kszatan Makes sense. If you don't mind pinging me here or on Gitter or on email (any of my commit messages will have the address), before starting again, I can give you some information about the latest plans of the UI and what's going on.

At this point, there are no plans for a new UI for the wizard, but we worked on improving the UI around the dashboard, etc. as you might have seen. We are also moving away from Ruby / ERBs to single page applications. That might actually make this work (potentially) easier - since we can use the proper pipeline config API to create a pipeline, instead of messing around with the ruby controllers. One challenge might be to get the SCM plugin UI to show here. However, we are making some changes to the UI framework to create better components, etc. which might help.

Once you get back to me, I can provide some help. We can have a quick chat before you restart. Thanks again.

**Pull request closed without merging**
