### PR TITLE
Fixes on new pipeline config spa:

### PR DESCRIPTION
**Pull request by kritika-singh3**
Issue: #8141 

Description:
 - The global error on client validation failure will now go away after 5 secs
 - Added min="0" for run instance count and job timeout
 - Added validation for custom tab path when name is specified

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
@kritika-singh3 - which issue point in the #8141 will be fixed by `The global error on client validation failure will now go away after 5 secs` ?

**Comment by kritika-singh3** [comment]
@GaneshSPatil The first one: `A global error shows up with the message "Validations failed for template with name 'deploy_template'. Error(s): [Validation failed.]. Please correct and resubmit." which does not go away.`

**Comment by GaneshSPatil** [comment]
@kritika-singh3 -

1. Clearing the global errors after 5 secs may not fix the above-mentioned issue completely. If the user hits save and closes the popup (by clicking `esc`), the error would be visible for 5 secs. Also, such error suddenly disappearing without an interaction might be confusing.

2. Not clearing global errors (on a specific timeout) was an intentional change. Reasons:
  - There is a possibility of multiple global errors and can may require more than 5 secs to read. 
  - Both, global errors and field specific errors are validation errors and should not go away unless user fixes them.

To allow users clearing the global errors, we changed the global errors from normal to dismissible errors, providing users an option to remove them (if the user think it may've been fixed by updating some other field from the form).

Coming back to the original issue,
To fix the above-mentioned error, we should not populate the global errors when user is operating inside a modal. IIRC, the global error holder `flashMessage` has been passed down to the individual widgets and modals. We should add a check to not populate global error when inside the modal context.

**Comment by kritika-singh3** [comment]
@GaneshSPatil Only when the client side validation fails, the global error will be removed after 5 secs.
 
For point 2 - the global errors populated from API calls will remain till the user click close. Also, only the global error goes away. The field validation errors stays. Also, various other info messages also disappear on our UI. I don't support the idea that it is confusing.

Your fix will not work as there are various cases (e.g. adding a fetch artifact task) in which the error are not fully mapped to the fields. In such cases, only the global errors represent the errors from the API call.

**Comment by GaneshSPatil** [comment]
> Also, various other info messages also disappear on our UI. I don't support the idea that it is confusing.

The `save/update/deleted successfully` info messages or errors occur on user interaction. User is aware of the fact that these messages are shown because (s)he performed some action on the page.

When i say "it would be confusing", i was thinking of the following scenario:
1. The user is in the popup modal context, performs save, some error happens and now closes the popup.
2. Upon closing the popup, the user is out of the edit modal context, and (s)he sees the error `Validation Failed! Please fix the below errors before submitting on the page and after a couple of seconds, it goes away. 
Which i thought would be confusing as without an interaction on the top level page, an error was shown, and went away.

> Your fix will not work as there are various cases (e.g. adding a fetch artifact task) in which the error are not fully mapped to the fields. In such cases, only the global errors represent the errors from the API call.

IIRC, we have a top level flashMessage, and then we've a flashMessage for each modal. Currently, all the global errors are mapped to the page level flashMessage. The logic of unbounded error being mapped to global flashMessage still remains the same. The only difference there would be is, instead of the global flashMessage being displayed outside, we would show that global flashMessage inside the modal.
Do you think that would work for server side errors too? or is there anything that I am missing?

**Comment by kritika-singh3** [comment]
The confusing scenario you mentioned, I also thought of the same. But my views were,
 - if the user remains on the modal popup - the field validation will be able to convey the info we want to convey
 - if the user closes the modal popup, we anyways discard the changes made. So showcasing the error on the discarded data is of no use anymore.

There is a difference between the page level global error and modal level global error - which is the entity on which it is mapped.
The 'consumeError' method works on an entity. The global level entity is the entire pipeline config, hence, it will catch all the errors. The modal level entity is a subset (say stage, job, task) and it will only use the entity specific part of the API response. Hence, there is a chance that edit in one part raises an error in another part which might get missed (I don't remember an exact example but one such e.g. is dependency material and fetch artifact).

**Pull request merged**
