### PR TITLE
Return a JobResult of Cancelled when the job is cancelled during preperation

### PR DESCRIPTION
**Pull request by ibnc**
It makes more sense, and will prevent the stage and job result/states from getting into a bad spot. See the screenshot bellow

screen shot 2017-05-09 at 3 39 38 pm

@jyotisingh I found a cancelBuild message while digging deeper into the logs.

```
2017-05-06 20:03:43,614 [pool-1-thread-2] DEBUG thoughtworks.go.agent.AgentWebSocketClientController:254 - Processing message[Message{action=cancelBuild, data=null, acknowledgementId=945c2073-cd38-4eda-b185-150f03b4b831}].
```
Which was received at pretty much the exact time we started to prepare:
```
2017-05-06 20:03:43,615 [pool-1-thread-5] DEBUG thoughtworks.go.agent.WebSocketSessionHandler:70 - Session[172.16.38.74/172.16.38.74:8154] attempt 1 to send message: Message{action=consoleOut, data={"jobIdentifier":{"pipelineName":"gocd.perf126","pipelineCounter":40,"pipelineLabel":"40","stageName":"default","buildName":"defaultJob","buildId":28098,"stageCounter":"1"},"tag":"pr","line":"[go] Start to prepare gocd.perf126/40/default/1/defaultJob on blrstdgoprf04.thoughtworks.com [/home/go/agent/go-agents/agent-12]","timestamp":"20:03:43.614"}, acknowledgementId=f50fc419-2ec7-4bd5-8b37-d78b76d39901}
2017-05-06 20:03:52,674 [pool-1-thread-3] ERROR thoughtworks.go.agent.AgentWebSocketClientController:227 - Waited 30 seconds for canceling job finish, but the job is still running. Maybe canceling job does not work as expected, here is running job details: JobRunner{handled=true, isJobCancelled=true, running=true, doneSignal=java.util.concurrent.CountDownLatch@70c4a90f[Count = 1], work=BuildWork[BuildAssignment{plan=[JobPlan identifier=JobIdentifier[gocd.perf126, 40, 40, default, 1, defaultJob, 28098]resources= plans=[] generators=[]], materialRevisions=MaterialRevision[
        [GitMaterial{url=git://172.16.38.50/git-repo-gocd.perf126, branch='master', submoduleFolder='null', shallowClone=true}, StringRevision[3174d32396427d3bd8206055655e3d392b07e023];[Material: com.thoughtworks.go.domain.materials.git.GitMaterialInstance@41043e4f[url=git://172.16.38.50/git-repo-gocd.perf126,username=<null>,pipelineName=<null>,stageName=<null>,view=<null>,useTickets=<null>,branch=master,submoduleFolder=<null>,flyweightName=861fd42a-bf8a-4714-ac45-fcb50e806be9,fingerprint=4463da5ed46e7c4ee6ee16484e1fab547142068e56d7ec8861be26303e75de67,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=239]
, Material: com.thoughtworks.go.domain.materials.git.GitMaterialInstance@41043e4f[url=git://172.16.38.50/git-repo-gocd.perf126,username=<null>,pipelineName=<null>,stageName=<null>,view=<null>,useTickets=<null>,branch=master,submoduleFolder=<null>,flyweightName=861fd42a-bf8a-4714-ac45-fcb50e806be9,fingerprint=4463da5ed46e7c4ee6ee16484e1fab547142068e56d7ec8861be26303e75de67,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=239]
, Material: com.thoughtworks.go.domain.materials.git.GitMaterialInstance@41043e4f[url=git://172.16.38.50/git-repo-gocd.perf126,username=<null>,pipelineName=<null>,stageName=<null>,view=<null>,useTickets=<null>,branch=master,submoduleFolder=<null>,flyweightName=861fd42a-bf8a-4714-ac45-fcb50e806be9,fingerprint=4463da5ed46e7c4ee6ee16484e1fab547142068e56d7ec8861be26303e75de67,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=239]
, Material: com.thoughtworks.go.domain.materials.git.GitMaterialInstance@41043e4f[url=git://172.16.38.50/git-repo-gocd.perf126,username=<null>,pipelineName=<null>,stageName=<null>,view=<null>,useTickets=<null>,branch=master,submoduleFolder=<null>,flyweightName=861fd42a-bf8a-4714-ac45-fcb50e806be9,fingerprint=4463da5ed46e7c4ee6ee16484e1fab547142068e56d7ec8861be26303e75de67,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=239]
, Material: com.thoughtworks.go.domain.materials.git.GitMaterialInstance@41043e4f[url=git://172.16.38.50/git-repo-gocd.perf126,username=<null>,pipelineName=<null>,stageName=<null>,view=<null>,useTickets=<null>,branch=master,submoduleFolder=<null>,flyweightName=861fd42a-bf8a-4714-ac45-fcb50e806be9,fingerprint=4463da5ed46e7c4ee6ee16484e1fab547142068e56d7ec8861be26303e75de67,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=239]
2017-05-06 20:03:52,675 [pool-1-thread-5] INFO  thoughtworks.go.work.DefaultGoPublisher:94 - Agent [blrstdgoprf04.thoughtworks.com, 10.132.4.124, 69af98d9-007c-4844-ba06-4eaf327a769a] is reporting status [Preparing] to Go Server for Build [gocd.perf126/40/default/1/defaultJob/28098]
```

Returning a JobResult of Cancelled will be more consistent with what is actually going on, and it will cause the agent to call reportCompleted instead of reportCurrentStatus. Reporting completed though reportCompleted will update the job result which will prevent the stage from having an Unknown result.

Let me know if you see any problems with this

### CODE REVIEW

**Comment by ibnc** [comment]
Also, it should be noted that this issue is not isolated to when the websocket is turned on. This problem can occur with websockets toggled on or off. I believe it's simply more likely to occur with the websockets turned on because the messages are received much sooner.

**Comment by ibnc** [comment]
@arvindsv Has this PR been reviewed yet? Is this even still a problem?

**Comment by arvindsv** [comment]
@jyotisingh @GaneshSPatil Can one of you take a look at this tomorrow? We can talk about it. Since you two have worked on something close to this recently, I think you'll know best.

If it's not necessary or is incorrect now, we can close it.

**Comment by jyotisingh** [comment]
@ibnc, @arvindsv  - Last month @GaneshSPatil and I spent some time looking at the websocket implementation for the agent-server communication to understand the different corner cases. We were able to replicate the scenario that you described above. 

While debugging we found that this happens because of a race between `BuildAssignmentService#matchingJobForRegisteredAgents` and `AgentRemoteHandler#processWithoutAcknowledgement` (ping request). Basically, when there is decent enough load on the server things would be running relatively slowly as compared to a really fast development server. 
Let's consider the scenario when the server finds that an agent connected via websocket is "idle", so it tries assigning work to it ([here](https://github.com/gocd/gocd/blob/10d4f4da8a0e4e8f89fd98b47978bc321b158dc1/server/src/com/thoughtworks/go/server/service/BuildAssignmentService.java#L229)). While the message is still being sent, and before the agent picks the work, the agent could send a `ping` request to the server. As a part of [this](https://github.com/gocd/gocd/blob/10d4f4da8a0e4e8f89fd98b47978bc321b158dc1/server/src/com/thoughtworks/go/server/websocket/AgentRemoteHandler.java#L88) call, the agent would be marked as "idle" by the server. In the next run of the [timer](https://github.com/gocd/gocd/blob/10d4f4da8a0e4e8f89fd98b47978bc321b158dc1/server/src/com/thoughtworks/go/server/service/BuildAssignmentService.java#L186), the agent would be considered for build-assignment again since as per server's knowledge the agent status is `idle`. While trying to [assign work](https://github.com/gocd/gocd/blob/10d4f4da8a0e4e8f89fd98b47978bc321b158dc1/server/src/com/thoughtworks/go/server/service/BuildAssignmentService.java#L223) to the same agent, server finds out that the agent was supposed to be building a job already, and it [reschedules](https://github.com/gocd/gocd/blob/10d4f4da8a0e4e8f89fd98b47978bc321b158dc1/server/src/com/thoughtworks/go/server/service/BuildAssignmentService.java#L151) the job. When a job is rescheduled, a new copy of the job instance (with different job-id) is created. The older one is marked ignored. 
By this time, agent has already received and is trying to process the original `assignWork` message from the server. Depending on the time when it reaches [here](https://github.com/gocd/gocd/blob/10d4f4da8a0e4e8f89fd98b47978bc321b158dc1/common/src/com/thoughtworks/go/remote/work/BuildWork.java#L127), or [here](https://github.com/gocd/gocd/blob/10d4f4da8a0e4e8f89fd98b47978bc321b158dc1/common/src/com/thoughtworks/go/remote/work/BuildWork.java#L140), the job might have been marked as ignored by the server. This is not really agent cancelling the build.

The http based implementation did not care about the status that was being reported as part of the `ping` thread, the loop thread was the decision maker. This is something that we tried addressing in the changes we were making, but had to put it on hold. We should have put up a comment here at that time, but missed doing so. But I think this PR should not be merged at this point as it doesn't solve the real problem. 

I hope what I said above makes some sense. If not, @GaneshSPatil will make an attempt this time :)

**Pull request closed without merging**
