### PR TITLE
Security bug: when editing svn material, plain password is printed in html

### PR DESCRIPTION
**Pull request by xli**
Change to output "" instead of svn material password.

p4 and tfs materials have similar problem, changed together.

### CODE REVIEW

**Comment by arvindsv** [comment]
Looks good to me. I checked the functionality too and it seems to work, adding and editing materials (SVN, TFS, Perforce).

**Comment by arvindsv** [comment]
Maybe not. I think the password is being set to ```******``` when it is saved.

**Comment by arvindsv** [comment]
No. I'm wrong. Ignore that. Still looks good to me, at this point.

**Comment by xli** [comment]
Build failed by test "KillAllChildProcessTaskBuilderTest.shouldKillAllChildProcessOnbuild", should not related to this PR changes

**Comment by ketan** [comment]
That's caused by JDK8 -
https://github.com/gocd/javasysmon/commit/c53cb0301c321d86ce9565148068a28fcdfa8739

**Comment by zabil** [comment]
Still working of fixing it as the commit has to check a lot of system
dependent stuff.

Meanwhile I'll set JAVA_HOME on PR pipelines to point to JDK7.

On Fri, Feb 5, 2016 at 11:26 AM, Ketan Padegaonkar <notifications@github.com
> wrote:

> That's caused by JDK8 -
>
> https://github.com/gocd/javasysmon/commit/c53cb0301c321d86ce9565148068a28fcdfa8739
>

**Pull request merged**
