### PR TITLE
Clean Shell Scripts

### PR DESCRIPTION
**Pull request by Androbin**
You need a space after the `[` and before the `]`.
The order of the `2>&1` and the redirect matters. The `2>&1` has to be last.
Double quote array expansions to avoid re-splitting elements.

### CODE REVIEW

**Comment by ketan** [comment]
Hi @Androbin — thanks for the PR. I just realized that the stuff in `manual-testing` is unused. I'll simply cherry-pick the changes to the jruby script directly to master and close this PR.

**Comment by ketan** [comment]
Applied directly at 8fa812d5fee4b82d6abc1134065bb0ceba5fd702

**Comment by Androbin** [comment]
Thanks @ketan ! You said that `manual-testing` is unused. But what about `server/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.6.2-java/test_all` ?

**Comment by ketan** [comment]
> Thanks @ketan ! You said that manual-testing is unused. But what about server/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.6.2-java/test_all ?

That is provided by the [nokogiri gem](https://github.com/sparklemotion/nokogiri/blob/v1.6.2/test_all). Not something we wrote, or something we use.

**Pull request closed without merging**
