### PR TITLE
Fixes sort bug present for freeSpace column in agents table

### PR DESCRIPTION
**Pull request by yankurk**

### CODE REVIEW

**Comment by yankurk** [comment]
#3756

**Comment by ketan** [comment]
Do you think a test is in order? https://github.com/gocd/gocd/blob/3fef18c6c79dafa81e9833ebe2044bcbd02ec504/server/webapp/WEB-INF/rails.new/spec/webpack/models/agents/agents_spec.js#L154

**Comment by ketan** [comment]
If a new test isn't needed, perhaps modify an existing test to cover this behavior?

**Comment by ashokgowtham** [comment]
Seems like the build has passed previously
https://build.gocd.org/go/pipelines/trigger/1486/do-nothing/1
But was cancelled after a retrigger. So actually all checks passed

**Pull request merged**
