### PR TITLE
Bump jruby-complete from 9.2.0.0 to 9.2.19.0

### PR DESCRIPTION
**Pull request by chadlwilson**
Replaces #9438 by @dependabot-bot which doesn't work OOTB.

https://www.jruby.org/news
https://blog.rubygems.org/2018/12/19/3.0.0-released.html

- Indirectly bumps Ruby stdlib `2.5.0` -> `2.5.8` and RubyGems `2.6.8` -> `3.1.6`
- Removes old `RubyRipper` hack relying on class overriding, long since resolved in JRuby `9.2.1.0`
- Updates build scripting to account for gems being installed to `gems/jruby/2.5.0` regardless of the JRuby patch version. Couldn't find an OOTB JRuby public constant available for use in Gradle.
- Replaced use of deprecated flags gone in RubyGems 3+

Seems to work OK so far locally; trying via pipeline in clean environment.

### CODE REVIEW

**Comment by arvindsv** [comment]
Gave Chad access to the PR pipeline group and marking this as not to be handled by stale bot.

**Comment by chadlwilson** [comment]
Hi @arvindsv - sorry for my ignorance, is this linked to my GitHub identity I get `There was an unknown error authenticating you. Please try again after some time, and contact the administrator if the problem persists.` currently if I try to authenticate with it.

**Comment by arvindsv** [comment]
Ah, I think you need to be in some GitHub group / team thing. Just a minute.

**Comment by arvindsv** [comment]
Can you try again? If not, I'll write to you directly and see if we can work out what's going on.

**Comment by arvindsv** [comment]
You need to accept some GitHub invitation I think.

**Comment by chadlwilson** [comment]
Thanks, working now!

**Comment by chadlwilson** [comment]
Re-ran and tests passed. Seems to be some flakiness/race condition with H2 locks on integration tests.

Failing on the same [docker-agent build task](https://build.gocd.org/go/tab/build/detail/installers-pull_9481/1/docker/1/docker-agent) as other PR builds after it tries to `exec` into the agent pod to test it.

Unfortunately it's not possible to see what's going wrong as it doesn't log either the the container output or the `exec` output in the equivalent of a `finally` or `trap` before exiting. Will see if I can replicate locally, but think unrelated to this change.

**Comment by arvindsv** [comment]
> Will see if I can replicate locally, but think unrelated to this change.

Yes, I think it's unrelated to your change. Please try to replicate. If you're not able to reproduce it, I'll try and find out more about this, or put in more logging if possible. Thank you!

**Comment by chadlwilson** [comment]
Locally the container fails to start due to
```
wrapper  | License Error:
wrapper  | The License Key, 202105080000006, was found but failed to be validated.
wrapper  | Please verify that the wrapper.license.* properties match exactly and have
wrapper  | not been modified.  Also verify that the following property values match
wrapper  | those specified when generating the license:
wrapper  |   wrapper.java.mainclass=org.tanukisoftware.wrapper.WrapperJarApp
wrapper  |   wrapper.app.parameter.1=lib/agent-bootstrapper.jar
```
... which causes the `exec` to fail, because the container has already been `--rm`ed.

Perhaps that's the same for these PR builds. I do have a change to get it to log the output here, which I'll polish up separately.

**Comment by chadlwilson** [comment]
Created #9547 for the issue, and #9546 to improve logging - think we need to get this fixed to unblock the `installers*/docker` pipelines for all other PRs since they will all get stuck currently.

**Review by marques-work — APPROVED** [review]
LGTM - maybe a rebase onto `master` now that @arvindsv merged the temporary license fix?

Other than that, are there additional changes you wanted to make -- I noticed this was still marked as a draft? All of the pipelines (including the functionals) are green, so there's a lot of confidence that this works properly.

**Comment by chadlwilson** [comment]
Rebased now.

@marques-work - at the time the pipelines were still red and it took a bit of shepherding to get it through. I also wasn't so comfortable merging without a better understanding from an experienced contributor of whether the smoke and functional tests were sufficient to give confidence in these types of changes or whether this had been attempted and abandoned earlier, however it looks from your comment like it should be OK, which is great.

I can merge this when the cla-bot and `cla.gocd.org` is fixed. Sadly seems to have died somehow in the last day or two?

**Comment by chadlwilson** [comment]
Had to revert this as it broke things on Windows. Can replicate locally inside a VM now.

The wrapping `script-templates/jruby.bat` no longer gets called by the `bundle install`ed gems such as `scss-lint`. They expect to find some kind of `jruby.exe` wrapper specifically on the `PATH`, not our custom script.

This is a bit of a mystery/mess to me. It seems rather complicated.

**Comment by chadlwilson** [comment]
FYI, I have resubmitted this as a partial upgrade to `9.2.9.0` in #9822 which is the last version prior to the RubyGems 3 upgrade which caused the Windows scripting issues above, discussed in #9574. I still aim to come back to the Windows scripting issues however.

**Pull request merged**
