### PR TITLE
Get rid of code related to licensing of go

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by ketan** [comment]
This is still a WIP, I'll send a note out when this is done.

**Comment by ketan** [comment]
This commit is good for someone to look at once 15.2 is out the door. The commit message has all the relevant information about the commit.

**Comment by jyotisingh** [comment]
Changes looks good. There are a few things that got left out, just look for "Enterprise" in localize.xml and localize_ja.xml, you will find a few sort of unused keys such as TEMPLATES_FEATURE_NOT_AVAILABLE, ENVIRONMENT_FEATURE_NOT_AVAILABLE etc. 
Also, there is `TEMPLATES_FEATURE_NOT_AVAILABLE` which is being referred to from `_template_unavailable_notification.html.erb` which is currently unused. We should get rid of them.

**Comment by ketan** [comment]
Removed the constants and files you mention, and a few more.

**Pull request merged**
