### PR TITLE
Added error on config repo save

### PR DESCRIPTION
**Pull request by kritika-singh3**
Issue: #6327 
 - If the material for config repo was already in use by a material with auto update
   off, the error would have the key `auto_update`.
 - Checked for the presence of the same and added it as a top-level error

### CODE REVIEW

**Comment by kritika-singh3** [comment]
config-repo-error-fix

**Comment by bdpiparva** [comment]
@naveenbhaskar - Please can you take a look at error message styling bit?

**Comment by naveenbhaskar** [comment]
yes.. working with kritika on this

**Comment by kritika-singh3** [comment]
Updated Preview:
config-repo-error-fix

**Pull request merged**
