### PR TITLE
[WIP] fixing an out of memory issue after turned on websocket.

### PR DESCRIPTION
**Pull request by xli**
jetty websocket has OOM bug (https://bugs.eclipse.org/bugs/show_bug.cgi?id=478829) that is fixed in later version.
This PR is for testing OOM fixes in latest jetty websocket lib.

### CODE REVIEW

**Comment by arvindsv** [comment]
I guess the status of this is that Java 8 is needed for this? So, it needs to wait till then?

**Comment by xli** [comment]
No luck.
I will check this out later, find another way maybe.

**Comment by xli** [comment]
@arvindsv WPC found server crashed because Go agent VM hit memory limit not the server run out of memory.
Right now, agent VM is running very close to memory limit set for VM, hence once we turned on websocket, which will use more memory than it was off, build became much more easier to fail.
We need increase agent VM memory limit and try out with websocket is enabled.
So, I'll close this PR for now.

**Comment by wpc** [comment]
As @xli said I can not find a proof for memory leak. I tried to lower down the heap limit to trigger OOM dump before linux OOM-killer kill the process, but didn't success. Server memory footprint is alway low, it even runs with -Xmx400m. GC log indicates server memory consumption and GC cycles are normal. 

One thing I notice is agent running with high memory. About 300+mb in RSS. 
```
11:13:45.723 go        5365  0.2 13.0 2288524 386032 ?      Sl   Mar30  17:01 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-0.b17.el6_7.x86_64/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Dagent.launcher.version=Unknown ...
```
When UI test running, it starts another agent with similar memory consumption. Maybe we can start with limit max agent memory consumptions.

Or maybe we could just turn on swap for the build agents, to get ourself out of dancing on the edge situation.

**Comment by ketan** [comment]
> Right now, agent VM is running very close to memory limit set for VM, hence once we turned on websocket, which will use more memory than it was off, build became much more easier to fail.

Do we know what is causing the additional memory utilisation?

> Or maybe we could just turn on swap for the build agents, to get ourself out of dancing on the edge situation.

No please. Turning on swap is a disaster as builds run an order of magnitude slower because of swap. Is the OOM caused because of heap, or permgen? If the permgen has increased, do we know how much it has increased by?

**Comment by wpc** [comment]
> Do we know what is causing the additional memory utilisation?

No, we have do a memory dump analysis yet. We just assume new websocket feature needs more memory, because it involves more components.

> Is the OOM caused because of heap, or permgen?

It is not a java OOM. It's linux OOM-killer. Here is an sample syslog when process get killed:

```
Apr  4 12:11:07 fmtgocdagent10 kernel: java invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=0, oom_score_adj=0
Apr  4 12:11:07 fmtgocdagent10 kernel: java cpuset=/ mems_allowed=0
Apr  4 12:11:07 fmtgocdagent10 kernel: Pid: 26953, comm: java Not tainted 2.6.32-504.el6.x86_64 #1
Apr  4 12:11:07 fmtgocdagent10 kernel: Call Trace:
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff810d40c1>] ? cpuset_print_task_mems_allowed+0x91/0xb0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff81127300>] ? dump_header+0x90/0x1b0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff8122ea2c>] ? security_real_capable_noaudit+0x3c/0x70
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff81127782>] ? oom_kill_process+0x82/0x2a0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff811276c1>] ? select_bad_process+0xe1/0x120
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff81127bc0>] ? out_of_memory+0x220/0x3c0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff811344df>] ? __alloc_pages_nodemask+0x89f/0x8d0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff8116c69a>] ? alloc_pages_current+0xaa/0x110
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff811246f7>] ? __page_cache_alloc+0x87/0x90
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff811240de>] ? find_get_page+0x1e/0xa0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff81125697>] ? filemap_fault+0x1a7/0x500
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff8114eae4>] ? __do_fault+0x54/0x530
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff810b33c6>] ? futex_wait+0x1e6/0x310
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff8114f0b7>] ? handle_pte_fault+0xf7/0xb00
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff8114fcea>] ? handle_mm_fault+0x22a/0x300
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff8104d0d8>] ? __do_page_fault+0x138/0x480
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff81041e98>] ? pvclock_clocksource_read+0x58/0xd0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff81041e98>] ? pvclock_clocksource_read+0x58/0xd0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff81040f2c>] ? kvm_clock_read+0x1c/0x20
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff8152ffbe>] ? do_page_fault+0x3e/0xa0
Apr  4 12:11:07 fmtgocdagent10 kernel: [<ffffffff8152d375>] ? page_fault+0x25/0x30
Apr  4 12:11:07 fmtgocdagent10 kernel: Mem-Info:
Apr  4 12:11:07 fmtgocdagent10 kernel: Node 0 DMA per-cpu:
Apr  4 12:11:07 fmtgocdagent10 kernel: CPU    0: hi:    0, btch:   1 usd:   0
Apr  4 12:11:07 fmtgocdagent10 kernel: Node 0 DMA32 per-cpu:
Apr  4 12:11:07 fmtgocdagent10 kernel: CPU    0: hi:  186, btch:  31 usd: 143
Apr  4 12:11:07 fmtgocdagent10 kernel: active_anon:698750 inactive_anon:33 isolated_anon:0
Apr  4 12:11:07 fmtgocdagent10 kernel: active_file:209 inactive_file:267 isolated_file:32
Apr  4 12:11:07 fmtgocdagent10 kernel: unevictable:0 dirty:0 writeback:0 unstable:0
Apr  4 12:11:07 fmtgocdagent10 kernel: free:14264 slab_reclaimable:3305 slab_unreclaimable:6784
Apr  4 12:11:07 fmtgocdagent10 kernel: mapped:215 shmem:39 pagetables:3613 bounce:0
Apr  4 12:11:07 fmtgocdagent10 kernel: Node 0 DMA free:12280kB min:220kB low:272kB high:328kB active_anon:3176kB inactive_anon:0kB active_file:32kB inactive_file:228kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15364kB mlocked:0kB dirty:8kB writeback:0kB mapped:52kB shmem:0kB slab_reclaimable:20kB slab_unreclaimable:8kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:384 all_unreclaimable? yes
Apr  4 12:11:07 fmtgocdagent10 kernel: lowmem_reserve[]: 0 3014 3014 3014
Apr  4 12:11:07 fmtgocdagent10 kernel: Node 0 DMA32 free:44776kB min:44832kB low:56040kB high:67248kB active_anon:2791824kB inactive_anon:132kB active_file:804kB inactive_file:840kB unevictable:0kB isolated(anon):0kB isolated(file):128kB present:3086552kB mlocked:0kB dirty:0kB writeback:0kB mapped:808kB shmem:156kB slab_reclaimable:13200kB slab_unreclaimable:27128kB kernel_stack:4704kB pagetables:14452kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:2528 all_unreclaimable? yes
Apr  4 12:11:07 fmtgocdagent10 kernel: lowmem_reserve[]: 0 0 0 0
Apr  4 12:11:07 fmtgocdagent10 kernel: Node 0 DMA: 8*4kB 4*8kB 2*16kB 1*32kB 4*64kB 1*128kB 2*256kB 2*512kB 4*1024kB 3*2048kB 0*4096kB = 12288kB
Apr  4 12:11:07 fmtgocdagent10 kernel: Node 0 DMA32: 832*4kB 737*8kB 526*16kB 322*32kB 157*64kB 33*128kB 2*256kB 2*512kB 1*1024kB 0*2048kB 0*4096kB = 44776kB
Apr  4 12:11:07 fmtgocdagent10 kernel: 544 total pagecache pages
Apr  4 12:11:07 fmtgocdagent10 kernel: 0 pages in swap cache
Apr  4 12:11:07 fmtgocdagent10 kernel: Swap cache stats: add 0, delete 0, find 0/0
Apr  4 12:11:07 fmtgocdagent10 kernel: Free swap  = 0kB
Apr  4 12:11:07 fmtgocdagent10 kernel: Total swap = 0kB
Apr  4 12:11:07 fmtgocdagent10 kernel: 786429 pages RAM
Apr  4 12:11:07 fmtgocdagent10 kernel: 47248 pages reserved
Apr  4 12:11:07 fmtgocdagent10 kernel: 1448 pages shared
Apr  4 12:11:07 fmtgocdagent10 kernel: 720539 pages non-shared
Apr  4 12:11:07 fmtgocdagent10 kernel: [ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj name
Apr  4 12:11:07 fmtgocdagent10 kernel: [  349]     0   349     2717      160   0     -17         -1000 udevd
Apr  4 12:11:07 fmtgocdagent10 kernel: [  658]     0   658     2716      162   0     -17         -1000 udevd
Apr  4 12:11:07 fmtgocdagent10 kernel: [  909]     0   909     2280      125   0       0             0 dhclient
Apr  4 12:11:07 fmtgocdagent10 kernel: [  956]     0   956     6899       68   0     -17         -1000 auditd
Apr  4 12:11:07 fmtgocdagent10 kernel: [  990]     0   990    62289      279   0       0             0 rsyslogd
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1012]    32  1012     4744       69   0       0             0 rpcbind
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1028]     0  1028    52736      179   0       0             0 sssd
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1029]     0  1029    61671      494   0       0             0 sssd_be
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1030]     0  1030    54172      159   0       0             0 sssd_nss
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1031]     0  1031    50559      173   0       0             0 sssd_pam
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1052]    29  1052     6357      114   0       0             0 rpc.statd
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1086]    81  1086     5905       87   0       0             0 dbus-daemon
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1100]     0  1100    47235      221   0       0             0 cupsd
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1132]     0  1132     1020       28   0       0             0 acpid
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1238]     0  1238    16556      177   0     -17         -1000 sshd
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1249]    38  1249     8206      166   0       0             0 ntpd
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1328]     0  1328    20737      230   0       0             0 master
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1338]    89  1338    20800      224   0       0             0 qmgr
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1345]     0  1345    44286     1127   0       0             0 tuned
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1358]     0  1358    29216      153   0       0             0 crond
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1407]   498  1407    31699     4835   0       0             0 Xvnc
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1416]   498  1416   685321    16582   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1424]   498  1424     5009       67   0       0             0 dbus-launch
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1425]   498  1425     5879       66   0       0             0 dbus-daemon
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1429]   498  1429    12581      155   0       0             0 vncconfig
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1431]   498  1431    38648     1103   0       0             0 xterm
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1432]   498  1432    45663      333   0       0             0 icewm
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1435]   498  1435    27077       94   0       0             0 bash
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1494]     0  1494     5276       47   0       0             0 atd
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1526]     0  1526    55578     1171   0       0             0 docker
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1535]     0  1535     2716      159   0     -17         -1000 udevd
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1660]     0  1660    65367    14693   0       0             0 chef-client
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1681]     0  1681     1020       23   0       0             0 agetty
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1690]     0  1690     1016       22   0       0             0 mingetty
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1692]     0  1692     1016       22   0       0             0 mingetty
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 1695]     0  1695     1016       22   0       0             0 mingetty
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 7933]   498  7933   371543    80304   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 7934]   498  7934   370971    79534   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 9223]     0  9223   144975      332   0       0             0 console-kit-dae
Apr  4 12:11:07 fmtgocdagent10 kernel: [10534]     0 10534    18325      129   0       0             0 login
Apr  4 12:11:07 fmtgocdagent10 kernel: [14181]     0 14181    27075       98   0       0             0 bash
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 7592]     0  7592     1016       21   0       0             0 mingetty
Apr  4 12:11:07 fmtgocdagent10 kernel: [ 7638]     0  7638     1016       21   0       0             0 mingetty
Apr  4 12:11:07 fmtgocdagent10 kernel: [10638]   498 10638   572132    95113   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [16519]    89 16519    20757      226   0       0             0 pickup
Apr  4 12:11:07 fmtgocdagent10 kernel: [26803]   498 26803   362369    18622   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [26825]   498 26825    11598     8683   0       0             0 gauge
Apr  4 12:11:07 fmtgocdagent10 kernel: [26908]   498 26908     1872      273   0       0             0 gauge-java
Apr  4 12:11:07 fmtgocdagent10 kernel: [26922]   498 26922   696497    43683   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [26932]   498 26932     1976      213   0       0             0 html-report
Apr  4 12:11:07 fmtgocdagent10 kernel: [26942]   498 26942   453797   159320   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [27092]   498 27092   188336    33464   0       0             0 firefox
Apr  4 12:11:07 fmtgocdagent10 kernel: [27149]   498 27149    32631      112   0       0             0 gconfd-2
Apr  4 12:11:07 fmtgocdagent10 kernel: [31115]   498 31115   418533     9546   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [31116]   498 31116   418533     9490   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [31128]   498 31128   418533     9573   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [31406]   498 31406   363462    35894   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [31408]   498 31408   363462    35906   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: [31409]   498 31409   363462    35697   0       0             0 java
Apr  4 12:11:07 fmtgocdagent10 kernel: Out of memory: Kill process 26942 (java) score 216 or sacrifice child
Apr  4 12:11:07 fmtgocdagent10 kernel: Killed process 26942, UID 498, (java) total-vm:1815188kB, anon-rss:637012kB, file-rss:268kB
``` 
 
I have looked at GC logs, heap, perm usage is very low. 

One thing weird about this situation: in above syslog for process 26942 is the test go server process,  ps info said rss usage is around 360mb, but later the killing report side anon-rss:637012kB. Almost doubled.

Also we stop investigating this issue because we found same error on trunk build: https://build.go.cd/go/tab/build/detail/acceptance-gauge/336/RunAcceptanceSpecs-priority/1/firefox-split-runInstance-6

**Pull request closed without merging**
