### PR TITLE
Dashboard Views refactoring

### PR DESCRIPTION
**Pull request by akshaydewan**
Needs a review before merging.
There are a few fixes pending on the Modal for creating a new view. These can be done on master as well, IMO.

### CODE REVIEW

**Comment by akshaydewan** [comment]
I'm seeing some console errors when a new tab is added. Will need to check that too.

**Comment by marques-work** [comment]
@akshaydewan @naveenbhaskar @arvindsv:

@kierarad and I finished the modal stacking work (opening multiple modals now moves prior modals out of the way for clarity) as well as moving the delete button into the personalization modal.

Also rebased onto latest upstream and fixed the lint issues.

Might only be some minor UI changes left, but this is certainly ready for review.

**Comment by marques-work** [comment]
@naveenbhaskar could you also give @kierarad push access to your repo?

**Comment by marques-work** [comment]
Made some minor styling fixes. Merging now. @naveenbhaskar could you poke around and make sure that the UI looks right to you? Thanks.

**Pull request merged**
