### PR TITLE
Allowlist support for plugin materials

### PR DESCRIPTION
**Pull request by maheshp**
Issue: #3962

* Added support for AllowList for Pluggable materials.
* Introduced PipelineConfig V11, to configure Pluggable materials with AllowList.

### CODE REVIEW

**Review by kritika-singh3 — APPROVED** [review]
LGTM. Do we need to bump up the config repo message format version for this?

**Comment by maheshp** [comment]
>  Do we need to bump up the config repo message format version for this?

I don't think we need to.

**Comment by kritika-singh3** [comment]
Verified the pipeline config API v11 and also the feature of allowlist for pluggable scm materials on `GoCD Version: 20.8.0 (12139-9c0643a585e5fa22cb1b2986049822d13708b783)`.
Need to update the UI.

**Comment by maheshp** [comment]
Yes, will send a PR for the same.

**Pull request merged**
