### PR TITLE
Update to allowlist/denylist

### PR DESCRIPTION
**Pull request by arvindsv**
Issue: #8263 

Description:
  - Change blacklist / whitelist in most places to either includes / excludes or allowlist / denylist.
  - In some places it's inside data (like the dashboard's personalization view sending it), which, if changed will break everyone's selected pipelines. It's internal and won't be seen anywhere. Haven't changed it. If anyone wants to, it's open-source and a PR will be accepted, as long as it doesn't affect existing users.
  - This PR also introduces `target_version: 10` for the internal config-repo JSON format (between CR plugins and GoCD). A similar PR will need to be opened for each plugin, so that they support v10. Just the YAML and Groovy plugins. The JSON one should work out of the box.

Todos:
- [x] Verify changes manually
- [ ] Submit PR to config repo plugins [Later, not necessarily immediately]
- [x] Update documentation (https://github.com/gocd/docs.go.cd/pull/468)
- [x] Check if any functional tests are affected (https://github.com/gocd/ruby-functional-tests/pull/670)

### CODE REVIEW

**Comment by marques-work** [comment]
> In some places it's inside data (like the dashboard's personalization view sending it), which, if changed will break everyone's selected pipelines. It's internal and won't be seen anywhere. Haven't changed it. If anyone wants to, it's open-source and a PR will be accepted, as long as it doesn't affect existing users.

IIRC, we do have data migrations built as a part of the personalization views work. It should be straightforward. For someone else to do of course :).

**Comment by arvindsv** [comment]
@maheshp After making the latest change, I verified it with this:

<details>
    <summary>Config</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="137">
  <server agentAutoRegisterKey="f4c32031-5803-4865-a4e6-aacc6b09fbf5" webhookSecret="5688f269-6af8-4633-9d51-ada2b62c7a85" commandRepositoryLocation="default" serverId="c73d3fbc-7350-498d-85d5-38b446175bf7" tokenGenerationKey="e8374d55-2ffc-4224-b463-34074824c776">
    <backup emailOnSuccess="true" emailOnFailure="true" />
    <artifacts>
      <artifactsDir>artifacts</artifactsDir>
    </artifacts>
  </server>
  <config-repos>
    <config-repo id="repo1" pluginId="json.config.plugin">
      <git url="/tmp/test.git" />
      <rules>
        <allow action="refer" type="*">*</allow>
      </rules>
    </config-repo>
  </config-repos>
  <pipelines group="group1" />
</cruise>
```

</details>

<details>
    <summary>Input JSON for config repo</summary>
    
```json
{
  "format_version" : 1,
  "name": "p1",
  "environment_variables": [],
  "group" : "group1",
  "materials": [
    {
      "url": "https://github.com/arvindsv/faketime.git",
      "type": "git",
      "name": "git_material1",
      "destination": "dir1",
      "filter": {
        "whitelist": [
          "dir1",
          "dir2"
        ]
      }
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "type": "git",
      "name": "git_material2",
      "destination": "dir2",
      "filter": {
        "ignore": [
          "dir1",
          "dir2"
        ]
      }
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "type": "git",
      "name": "git_material3",
      "destination": "dir3"
    }
  ],
  "stages": [
    {
      "name": "build",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "environment_variables": [],
      "jobs": [
        {
          "name": "build",
          "environment_variables": [],
          "tabs": [],
          "resources": [],
          "artifacts": [],
          "properties": [],
          "run_instance_count": null,
          "timeout": 0,
          "tasks": [
            {
              "type": "rake"
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

<details>
    <summary>JSON for that pipeline once exported</summary>

```json
{
  "group": "group1",
  "name": "p1",
  "display_order_weight": -1.0,
  "label_template": "${COUNT}",
  "lock_behavior": "none",
  "environment_variables": [],
  "parameters": [],
  "materials": [
    {
      "url": "https://github.com/arvindsv/faketime.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [],
        "includes": [
          "dir1",
          "dir2"
        ]
      },
      "destination": "dir1",
      "auto_update": true,
      "name": "git_material1",
      "type": "git"
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [
          "dir1",
          "dir2"
        ],
        "includes": []
      },
      "destination": "dir2",
      "auto_update": true,
      "name": "git_material2",
      "type": "git"
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [],
        "includes": []
      },
      "destination": "dir3",
      "auto_update": true,
      "name": "git_material3",
      "type": "git"
    }
  ],
  "stages": [
    {
      "name": "build",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "approval": {
        "type": "success",
        "users": [],
        "roles": [],
        "allow_only_on_success": false
      },
      "environment_variables": [],
      "jobs": [
        {
          "name": "build",
          "environment_variables": [],
          "tabs": [],
          "resources": [],
          "artifacts": [],
          "timeout": 0.0,
          "tasks": [
            {
              "run_if": "passed",
              "type": "rake"
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

That shows that the pipeline was created with the right allowlist / denylist. I verified it on the UI as well.

Screenshot 2020-07-09 at 17 42 01

**Comment by arvindsv** [comment]
The YAML and groovy plugins will need updates. Ideally they're all done together and published in the same release (since they are bundled). I'll open an issue for it -- just as a reminder, so that we don't release without that. I'll try and work on it sometime.

**Comment by maheshp** [comment]
Thanks @arvindsv! The PR LGTM, will merge the PR and will test it once we get a build out.

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.6.0 (11955-1babc8e0681956a3619d907b6ada709adb1aa1f5)

Config repo changes verified using bundled YAML and JSON plugins. Checked with latest Groovy plugin(1.0.3-146)

**Pull request merged**
