### PR TITLE
Include entry with the current template name in the fetch suggestion hierarchy. (#2877)

### PR DESCRIPTION
**Pull request by varshavaradarajan**
#2877

### CODE REVIEW

**Comment by akshaydewan** [comment]
As a side effect of this, I can also see my template in the list of pipelines on the autocomplete dialog. (e.g. template named `bernard` in the screenshots)

screenshot 2019-02-22 at 12 12 12

And saving fails if I select the template:
screenshot 2019-02-22 at 12 13 11

**Comment by varshavaradarajan** [comment]
@akshaydewan - thank you. Will fix it.

**Comment by bdpiparva** [comment]
@akshaydewan - Please can you take a look at this PR?

**Pull request merged**
