### PR TITLE
Config repo support for parameters and referencing templates from pipelines.

### PR DESCRIPTION
**Pull request by varshavaradarajan**

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
#3849

**Comment by tomzo** [comment]
@varshavaradarajan This looks good. I don't see anything wrong in these changes. But I think it would be nice to add one integration test case at higher level with main XML config with some template and a config-repo pipeline referencing it. That way we would have a test for all preprocessors used together.
Have a look at [these tests](https://github.com/gocd/gocd/blob/4a7363bbcb7919c81de5482d8e814c714ad3f75e/server/test/integration/com/thoughtworks/go/config/CachedGoConfigIntegrationTest.java#L349) as example. You can write the remote pipeline in XML there like [here](https://github.com/gocd/gocd/blob/4a7363bbcb7919c81de5482d8e814c714ad3f75e/server/test-resources/external_git_config_repo_referencing_first/downstream.gocd.xml) (no plugin is needed). It is a hidden feature, which we have for tests. It will bypass the `ConfigConverter` but it would use preprocessors in order.

Also, @jyotisingh wrote the preprocessors part so she might have better insight here than me.

**Comment by varshavaradarajan** [comment]
Yes, I am writing the integration test.

**Comment by jyotisingh** [comment]
@varshavaradarajan - looks good to me. 
As @tomzo mentioned, just write an integration test. Let me know if you need any help with that.

**Pull request merged**
