### PR TITLE
Use SHA-512/256 for all entity hashing

### PR DESCRIPTION
**Pull request by marques-work**
Trying to move away from `md5`, which is broken WRT cryptographic standards, to SHA-512/256. This isn't all of the usages (e.g., various parts of `CruiseConfig` and artifact checksums still use `md5`, but this is the majority of cases.

### CODE REVIEW

**Comment by arvindsv** [comment]
I assume this does not affect the name of the flyweight directory, etc. which can cause problems. It looks like it's for MD5 in API calls and stuff around diffs of config.

**Comment by arvindsv** [comment]
Might be good to consider perf as well. Should be ok, but still.

**Comment by marques-work** [comment]
@arvindsv yes, I don't think it would affect flyweight dirs. Generally, it should only affect APIs (mostly etag generation I believe).

yes, performance is a question. SHA-256 is more computationally expensive, but whether that becomes a choke point (I'm guessing not) is worth observing.

**Comment by marques-work** [comment]
@arvindsv I have read that SHA-512 might be more performant than SHA-256 (esp on 64-bit CPUs). Those hashes are super long though, but I believe there are truncated variants (or we can truncate them ourselves. It would not be difficult to swap this out.

**Comment by marques-work** [comment]
Now, SHA-512/256. Updated title and description to match.

**Pull request merged**
