### PR TITLE
Reduced the width of tooltip wrapper as the same was cut off

### PR DESCRIPTION
**Pull request by kritika-singh3**
Issue: #7391 

Description:
 also removed the default permission added due to rebase

### CODE REVIEW

**Comment by kritika-singh3** [comment]
Screen Shot 2019-12-09 at 2 28 56 PM

**Comment by akshaydewan** [comment]
Other ways to (long term) fix this could be to tweak the z-index of the tooltip. It could be set higher than the modal overlay. Or we can change the alignment of the tooltip when it is near the edge of the view, but that might be tricky on a modal.

**Comment by kritika-singh3** [comment]
@akshaydewan  Tweaking the z-index of the tooltip might not work as we have a fixed width on our [modals](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/views/components/modal/index.scss#L54-L64). The extra width on the tooltip will get cut off.

**Comment by akshaydewan** [comment]
Ah, I see. Got it 👍

**Pull request merged**
