### PR TITLE
Config repo performance

### PR DESCRIPTION
**Pull request by ibnc**
This PR multithreads the config repo processing. It will now checkout the repo, parse the config, and merge the config in parallel (Merging still has a lock, so that bit will be in serial).

This PR addresses https://github.com/gocd/gocd/issues/5010

@ketan @tomzo

### CODE REVIEW

**Comment by arvindsv** [comment]
@ibnc Can you explain the problem too? Previously, there were multiple listeners (configured, at least) as well. Was there a lock at the wrong place?

**Comment by ibnc** [comment]
> @ibnc Can you explain the problem too? Previously, there were multiple listeners (configured, at least) as well. Was there a lock at the wrong place?

Previously, there were multiple listeners that updated the materials, but only one listener for checking out, parsing, and merging the config repo updates from the materials. The multiple listeners for config repo materials were dedicated material update listeners that would only update the material in the DB. So increasing the number of those listeners would only have a small effect on the over all performance. The actual checking out, parsing, and merging were done in serial.

**Comment by ibnc** [comment]
@tomzo 

You'd be the best person to ask about the initial check out and parsing work. 

I'm currently looking through the epic https://github.com/gocd/gocd/issues/1133 but there's a lot to parse through there.

**Comment by tomzo** [comment]
The PR which added second queue for config-repos and the config repo updater - https://github.com/gocd/gocd/pull/1333 
The design was described here https://github.com/gocd/gocd/issues/1133#issuecomment-116826923

This was over 3 years ago so I don't recall all of it, and code might have a changed since then. But from what I written there:
> ConfigMaterialUpdater - new component
Added new component - ConfigMaterialUpdater which listens on config-material-update-
completed topic. So when MDU is done then ConfigMaterialUpdater gets its chance to work with material being updated:
 -It uses MaterialRepository to check if there were any changes
 -It uses existing pollers code to checkout material to directory
 -It calls GoRepoConfigDataSource (where parsing happens) and when done
 -It posts to material-update-completed which is picked up by MaterialUpdateService using standard procedure as if this was an old-school material. This removes material from inProgress status.

So you are making (previously singleton) `ConfigMaterialUpdater` into multiple listeners, and then rely on  locking in merge mechanism.
OK, I am starting to get your point.

**Comment by tomzo** [comment]
Ping me once you've fixed the failing tests. 
I'd like to check if this is not breaking anything by starting a test server with all my config-repos and see if it will get to valid config after parsing all of them.

**Comment by ibnc** [comment]
> Ping me once you've fixed the failing tests.
> I'd like to check if this is not breaking anything by starting a test server with all my config-repos and see if it will get to valid config after parsing all of them.

That'd be a great help :)

**Comment by ibnc** [comment]
@tomzo Fixed the tests

**Comment by ibnc** [comment]
@tomzo :D 

Thank you for helping!

**Comment by tomzo** [comment]
Can you rebase and squash the commits into 1?

**Comment by ibnc** [comment]
Can do

**Comment by arvindsv** [comment]
@maheshp and I will probably take a look at the whole of MDU and see what can be done to make it simpler, if possible. Even before this change, it was a little too complicated and convoluted.

**Comment by ibnc** [comment]
@arvindsv it's def too complicated/convoluted

@maheshp technically, yes it will reduce the number of listeners for material updates. That being said, ConfigMaterialUpdateListener will not affect the rate that the MaterialUpdateListener listeners will process. 

Perhaps we should raise the default number of MaterialUpdateListeners to 3 or 4?

**Comment by arvindsv** [comment]
@ibnc Do you mean _by_ 3 or 4? The default number of listeners is 10. Config update listeners were 2, for a total of 12. Now, the total is 10, as far as I understand.

**Pull request merged**
