### PR TITLE
Allow artifact plugins to introduce new env vars

### PR DESCRIPTION
**Pull request by arvindsv**
This allows an artifact plugin to introduce environment variables into the job, after fetching an external artifact. This was planned for earlier versions of the k8s work but was not finished. Without this, you'll need to use external tools to parse the metadata JSON. With this, the plugin can expose environment variables which are then made available to all the tasks following the fetch artifact.

Assume there's a new version of the Docker artifact plugin. Assume a config which contains:

```
Pipeline 1:
    Stage 1:
        Job 1:
            Task 1: Run some tests
            Task 2: Run a docker build

            Specify artifact 1: External artifact (id = X) for the plugin - image1/v${GO_PIPELINE_COUNTER}

Pipeline 2:
    Stage 1:
        Job 1:
            Task 1: Fetch external artifact X from "Pipeline 1 / Stage 1 / Job 1"
            Task 2: Deploy to k8s using helm
            Task 3: Notify about state of deployment
```

At the end of "Task 1" in the second pipeline, the plugin can now set environment variables by returning a JSON such as the one below:

```
[
  {
    "name": "IMAGE_ID",
    "value": "image1/v23",
    "secure": false
  },
  {
    "name": "USERNAME",
    "value": "user1",
    "secure": false
  },
  {
    "name": "PASSWORD",
    "value": "some-password",
    "secure": true
  }
]
```

This will cause:
  1. Log messages in the console log of the fetch artifact task, which explain which environment variables are being set (see [test](https://github.com/gocd/gocd/compare/master...arvindsv:allow-artifact-plugins-to-introduce-new-env-vars#diff-c00abeef577a955db2e67dbf2c2a9079R156) for example messages).
  2. Introduce those environment variables into the job so that Task 2 and Task 3 will now have access to those environment variables when they execute.

Considerations:
  - It's possible for two fetch artifact tasks to overwrite each other's environment variables. Last one wins. It's up to the plugin to accept a prefix which it uses in the environment variable name.

### Test setup:

1. Use plugin built from [this](https://github.com/sheroy/docker-registry-artifact-plugin/tree/e6cce770b6115fb21a82c85e9ef71167d55410d0).

2. Pull docker image used in config below:

    ```
    docker pull sheroy/bulletin-board:1
    ```

3. Use this config XML (below), and replace all instances of `YOUR-DOCKER-HUB-USERNAME-HERE` and `YOUR-DOCKER-HUB-PASSWORD-HERE` with valid credentials:

<details>
    <summary>Show config XML:</summary><p>

```xml
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="113">
  <server artifactsdir="artifacts" agentAutoRegisterKey="0bc584a7-e64c-4a33-86e1-8c4fe0a8ac1d" webhookSecret="a3bd1404-d360-4e55-8434-a128411db580" commandRepositoryLocation="default" serverId="7b772e27-cd9a-46d8-bf2b-0cbb5fb9acf2" tokenGenerationKey="611db7c3-f137-44a1-b5f3-10a3f625e308">
    <backup emailOnSuccess="true" emailOnFailure="true" />
  </server>
  <artifactStores>
    <artifactStore id="abc" pluginId="cd.go.artifact.docker.registry">
      <property>
        <key>RegistryURL</key>
        <value>https://index.docker.io/v1/</value>
      </property>
      <property>
        <key>Username</key>
        <value>YOUR-DOCKER-HUB-USERNAME-HERE</value>
      </property>
      <property>
        <key>Password</key>
        <value>YOUR-DOCKER-HUB-PASSWORD-HERE</value>
      </property>
    </artifactStore>
  </artifactStores>
  <pipelines group="defaultGroup">
    <pipeline name="Abc">
      <materials>
        <git url="git@github.com:arvindsv/faketime.git" />
      </materials>
      <stage name="stage1">
        <jobs>
          <job name="job1_stage1">
            <tasks>
              <exec command="bash">
                <arg>-c</arg>
                <arg>docker tag sheroy/bulletin-board:1 YOUR-DOCKER-HUB-USERNAME-HERE/bulletin-board:v${GO_PIPELINE_COUNTER}</arg>
                <runif status="passed" />
              </exec>
            </tasks>
            <artifacts>
              <artifact type="external" id="abcdef" storeId="abc">
                <configuration>
                  <property>
                    <key>BuildFile</key>
                    <value />
                  </property>
                  <property>
                    <key>Image</key>
                    <value>YOUR-DOCKER-HUB-USERNAME-HERE/bulletin-board</value>
                  </property>
                  <property>
                    <key>Tag</key>
                    <value>v${GO_PIPELINE_COUNTER}</value>
                  </property>
                </configuration>
              </artifact>
            </artifacts>
          </job>
        </jobs>
      </stage>
      <stage name="stage2">
        <jobs>
          <job name="job1_stage2">
            <tasks>
              <fetchartifact artifactOrigin="external" artifactId="abcdef" pipeline="Abc" stage="stage1" job="job1_stage1">
                <configuration>
                  <property>
                    <key>EnvironmentVariablePrefix</key>
                    <value>PREFIX1</value>
                  </property>
                </configuration>
                <runif status="passed" />
              </fetchartifact>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>env</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
</cruise>
```
    
</p></details>
&nbsp;

4. Trigger pipeline. In the console of the job, "job1_stage2", you should see something like this:

    ```
     NOTE: Setting new environment variable: PREFIX1_ARTIFACT_IMAGE = YOUR-DOCKER-HUB-USERNAME-HERE/bulletin-board:v1
    ```

    You'll also see in the output of the `env` command that it has the environment variable, `PREFIX1_ARTIFACT_IMAGE`, set.

### Todos:

- [ ] Update [functional spec](https://github.com/gocd/ruby-functional-tests/blob/master/specs/ExternalArtifacts.spec) - Done in: https://github.com/gocd/ruby-functional-tests/pull/172
  - [ ] Update the [test plugin](https://github.com/bdpiparva/dummy-artifact-plugin) - Done in: https://github.com/gocd/go-plugins/pull/69
  - [x] Move the test plugin into the gocd org - Done in: https://github.com/gocd/go-plugins/pull/68
- [ ] Introduce new plugin which uses this version and sets environment variables (@sheroy) - Will come from https://github.com/sheroy/docker-registry-artifact-plugin/commits/master
- [ ] Update [API docs](https://plugin-api.gocd.org/current/artifacts/#fetch-artifact)
- [x] Provide more info in this issue (provide a config XML which shows this being used)

@sheroy has seen this.

### CODE REVIEW

**Comment by arvindsv** [comment]
For review:

- Update environment variable context after fetching artifact (in the builder): [here](https://github.com/gocd/gocd/pull/5188/files#diff-e666f98b420cca16516aa3331ef52154R79)
- Test for the builder: [here](https://github.com/gocd/gocd/pull/5188/files#diff-c00abeef577a955db2e67dbf2c2a9079R156)
- Introduce version 2 of extension: All over and [here](https://github.com/gocd/gocd/pull/5188/files#diff-df4e20f0f8f2f6ae0d1ba4a1611f9766R50)

@sheroy will soon submit a PR for the docker artifact plugin, which sets environment variables.

**Comment by varshavaradarajan** [comment]
@arvindsv - what if there are 2 fetch artifact tasks at the beginning of the job to fetch 2 different images? Based on the comment above, the env var IMAGE_ID is set. Why did you choose to not prefix the env var name with the artifact I'd?

**Comment by varshavaradarajan** [comment]
Sorry, rather the plugin should set the env var like that.

**Comment by arvindsv** [comment]
@varshavaradarajan Two reasons:

1. I felt that there will always be corner cases, if we decide to try and "disambiguate". Artifact ID is unique only within a pipeline, right? If there are two pipelines with the same artifact ID, then you can still face that problem.

2. Suddenly, your environment variables are dependent on an upstream pipeline's artifact ID. If the artifact ID changes (and someone changes all occurrences of it in the config), your scripts which except the environment variable will fail.

**Comment by adityasood** [comment]
I spent some time testing this PR today. 

**Go Version: 18.11.0-7813**
**Artifact plugin for docker Version:1.0.0-49**

Attached are screenshots from the test environment and a test-config.xml file

### VSM
screen shot 2018-10-31 at 4 21 44 pm

### Two fetch tasks with env getting overridden (as expected)

screen shot 2018-10-31 at 3 58 35 pm

### Two fetch tasks with Prefix for the env

screen shot 2018-10-31 at 3 58 02 pm

<details> <summary> Sample config.xml </summary>

```xml
<artifactStores>
    <artifactStore id="docker-local-artifact" pluginId="cd.go.artifact.docker.registry">
      <property>
        <key>RegistryURL</key>
        <value>localhost:5000</value>
      </property>
      <property>
        <key>Username</key>
        <value>admin</value>
      </property>
      <property>
        <key>Password</key>
        <encryptedValue>password</encryptedValue>
      </property>
    </artifactStore>
  </artifactStores>
  <pipelines group="defaultGroup">
    <pipeline name="sample-docker-pipeline">
      <materials>
        <git url="https://github.com/adityasood/licensemgmt" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>docker tag ubuntu:16.04 localhost:5000/gocd-build:v${GO_PIPELINE_COUNTER}</arg>
                <runif status="passed" />
              </exec>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>docker images</arg>
                <runif status="passed" />
              </exec>
            </tasks>
            <artifacts>
              <artifact type="external" id="sample-docker-artifact" storeId="docker-local-artifact">
                <configuration>
                  <property>
                    <key>Image</key>
                    <value>localhost:5000/gocd-build</value>
                  </property>
                  <property>
                    <key>Tag</key>
                    <value>v${GO_PIPELINE_COUNTER}</value>
                  </property>
                  <property>
                    <key>BuildFile</key>
                    <value />
                  </property>
                </configuration>
              </artifact>
            </artifacts>
          </job>
        </jobs>
      </stage>
    </pipeline>
    <pipeline name="sample-docker-dowstream-pipeline">
      <materials>
        <pipeline pipelineName="sample-docker-pipeline" stageName="defaultStage" materialName="upstreamPipeline" />
        <pipeline pipelineName="sample-docker-pipelin-2" stageName="defaultStage" materialName="upstreamPipeline02" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>docker images</arg>
                <runif status="passed" />
              </exec>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>docker rmi localhost:5000/gocd-build:v${GO_DEPENDENCY_LABEL_UPSTREAMPIPELINE}</arg>
                <runif status="passed" />
              </exec>
              <fetchartifact artifactOrigin="external" artifactId="sample-docker-artifact" pipeline="sample-docker-pipeline" stage="defaultStage" job="defaultJob">
                <configuration>
                  <property>
                    <key>EnvironmentVariablePrefix</key>
                    <value>GO_DEPENDENCY_LOCATOR_UPSTREAMPIPELINE</value>
                  </property>
                </configuration>
                <runif status="passed" />
              </fetchartifact>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>echo $GO_DEPENDENCY_LOCATOR_UPSTREAMPIPELINE_ARTIFACT_IMAGE</arg>
                <runif status="passed" />
              </exec>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>docker images</arg>
                <runif status="passed" />
              </exec>
              <fetchartifact artifactOrigin="external" artifactId="sample-docker-artifact" pipeline="sample-docker-pipelin-2" stage="defaultStage" job="defaultJob">
                <configuration>
                  <property>
                    <key>EnvironmentVariablePrefix</key>
                    <value>GO_DEPENDENCY_LOCATOR_UPSTREAMPIPELINE02</value>
                  </property>
                </configuration>
                <runif status="passed" />
              </fetchartifact>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>echo $GO_DEPENDENCY_LOCATOR_UPSTREAMPIPELINE_ARTIFACT_IMAGE; echo $GO_DEPENDENCY_LOCATOR_UPSTREAMPIPELINE02_ARTIFACT_IMAGE;</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
    <pipeline name="sample-docker-pipelin-2">
      <materials>
        <git url="https://github.com/adityasood/licensemgmt" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>docker tag ubuntu:16.04 localhost:5000/gocd-build:v${GO_PIPELINE_COUNTER}</arg>
                <runif status="passed" />
              </exec>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>docker images</arg>
                <runif status="passed" />
              </exec>
            </tasks>
            <artifacts>
              <artifact type="external" id="sample-docker-artifact" storeId="docker-local-artifact">
                <configuration>
                  <property>
                    <key>Image</key>
                    <value>localhost:5000/gocd-build</value>
                  </property>
                  <property>
                    <key>Tag</key>
                    <value>v${GO_PIPELINE_COUNTER}</value>
                  </property>
                  <property>
                    <key>BuildFile</key>
                    <value />
                  </property>
                </configuration>
              </artifact>
            </artifacts>
          </job>
        </jobs>
      </stage>
    </pipeline>
```
</details>

**Pull request merged**
