### PR TITLE
Frontend changes to show server health messages on SPAs

### PR DESCRIPTION
**Pull request by ketan**
#4232

### CODE REVIEW

**Comment by akshaydewan** [comment]
Screenshot of the Errors and Warnings modal:
screen shot 2018-01-31 at 10 46 01

**Comment by ketan** [comment]
@naveenbhaskar @tinozza — I know you guys raised an issue about consistency in styles and colors and everything else in between :)

So I wanted to check with you if you have any thoughts on the current color selection.

**Comment by akshaydewan** [comment]
Screenshot for Errors and Warnings in the top menu
screen shot 2018-01-31 at 12 22 42

**Comment by GaneshSPatil** [comment]
@ketan @akshaydewan -- I guess we need to add the errors section to the spark spa navigations too.
Probably adding [this](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/views/new_navigation_elements/_navigation.html.erb#L39) line [here](https://github.com/gocd/gocd/blob/master/spark/spark-spa/src/main/resources/velocity/new_navigation_elements/_navigation.vm#L50) too?

**Pull request merged**
