### PR TITLE
Use the safe output stream consumer to replace secrets in pluggable tasks. (#4737)

### PR DESCRIPTION
**Pull request by varshavaradarajan**
cc @akshaydewan

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
Pending: 

- [ ] Websocket enabled agents
- [ ] Agents using BuildSession

**Comment by arvindsv** [comment]
Agents using build session don't support plugins (yet). Right? Or is it just the golang one?

I'd not tie those two to what you already have. Meaning I'd consider those separate PRs. Makes it easier to review and merge, imo.

**Comment by varshavaradarajan** [comment]
> Agents using build session don't support plugins (yet). Right? Or is it just the golang one?

No idea. We saw something called `ExportCommandFilter` that does the masking. Need to try that out with pluggable task. You just made me realize that if that's the case, even publish and fetch of external artifacts must be supported by Build Session :)

> I'd not tie those two to what you already have. 

Okay.

**Comment by varshavaradarajan** [comment]
Tried it out with BuildSession - Got the error `"com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder" does not support new build command agent` - So, pluggable tasks is not supported by BuildSession. @jyotisingh - checked with websockets. Works.

**Comment by varshavaradarajan** [comment]
https://github.com/gocd/gocd/issues/4401

**Comment by varshavaradarajan** [comment]
https://build.gocd.org/go/pipelines/value_stream_map/trigger/2776

**Pull request merged**
