### PR TITLE
[Experiment] Add universal add pipeline button to dashboard

### PR DESCRIPTION
**Pull request by kierarad**
- No group is passed, so an option for a group to be selected needs to be added to the new flow in order for the add pipeline to succeed

### CODE REVIEW

**Comment by kierarad** [comment]
[Can we have a universal add pipeline button? (vs an add pipeline button per group)](https://trello.com/c/zXPOe6Ux/40-can-we-have-a-universal-add-pipeline-button-vs-an-add-pipeline-button-per-group)

**Comment by arvindsv** [comment]
@kierarad Can you add an image / animation to this PR to show how it looks?

**Comment by arvindsv** [comment]
I do like the add pipeline button per group ... but I'm willing to have my mind changed. For existing users, it'll feel more natural to have the add pipeline button at the group level (my hypothesis).

**Comment by streisguth** [comment]
I think if we have an 'Add Pipeline' action outside of the context of a group, then I imagine we'll just have to make the Pipeline Group a required field, likely somewhere in the context of 'Pipeline Name' on the 'Add Pipeline' screen.

**Comment by arvindsv** [comment]
Yes, that's what we do today. To me, it's less about what we will need to do if we put a single button than about what feels more natural to users. Whether it's more natural to look at a bunch of pipelines and say, "I need a new pipeline here. Let me click that button. Let me go select the group of the pipeline in a dropdown. Now, I can do the rest" vs. "I need a new pipeline here. Let me click the add pipeline button for that group. Now I can do the rest".

**Comment by marques-work** [comment]
@kierarad I would think that enabling this would hide the "add" buttons on the groups. Are you planning to implement that? I'm assuming this is still WIP.

image

@arvindsv also, that's what it looks like :) ☝️

**Comment by marques-work** [comment]
@streisguth @arvindsv @kierarad do we want to also expose pipeline group at the top-level of the add form? Currently, it's an advanced option, so the user won't see it unless they know what they are looking for. Bringing it up top would force the user to consider which group they want to add a pipeline to, though for new users, this may be a new concept.

**Comment by arvindsv** [comment]
@marques-work If it's a global button, then it might make sense to bring the group out of advanced. If it's a group-level one, I think it's fine to leave it in advanced.

**Comment by kierarad** [comment]
Closing this as some user research indicates adding pipelines within a specific group seems to be more natural for users

**Pull request closed without merging**
