### PR TITLE
Support for blacklist/whitelist in Fan-In behaviour

### PR DESCRIPTION
**Pull request by bhimsenpadalkar**
This change will potentially fix the [limitation](https://docs.gocd.io/15.2.0/advanced_usage/fan_in.html#limitations) of Fan-In where pipeline does not get triggered if one of the upstream pipelines has blacklist/whitelist.

Current issues opened:
[3451](https://github.com/gocd/gocd/issues/3451)
[2081](https://github.com/gocd/gocd/issues/2081)
[2489](https://github.com/gocd/gocd/issues/2489)

### CODE REVIEW

**Comment by jyotisingh** [comment]
@bhimsenpadalkar - do you mind rebasing this PR?

**Comment by bhimsenpadalkar** [comment]
Rebased..

**Comment by ketan** [comment]
@bhimsenpadalkar — That's a merge not a rebase, try and rebase and force push to this branch.

**Comment by bhimsenpadalkar** [comment]
Sorry. Fixed now. See if it's OK.

**Comment by ketan** [comment]
Closing since I've been made aware offline from a few peeps on your team that there are bugs in this implementation.

**Pull request closed without merging**
