### PR TITLE
API to delete all disabled users.

### PR DESCRIPTION
**Pull request by varshavaradarajan**
#3619

### CODE REVIEW

**Comment by ketan** [comment]
I assumed that deleting users is not permissible, because we have references to users in other tables.

@arvindsv @jyotisingh — care to throw some light?

**Comment by ketan** [comment]
Arguably, there is [this API](https://api.gocd.org/current/#delete-a-user) to delete a user, written by yours truly...

**Comment by arvindsv** [comment]
@ketan - As far as I know, there is no foreign key from any table to the users table. So, delete should be fine. @jyotisingh might know better.

The only problem we had with the delete is that, with the default value of the "Allow users that exist in LDAP, password file or via plugin to log into GoCD, even if they haven't been explicitly added to GoCD" flag being "true", a deleted user might be able to log back in, whereas a disabled user would not have been allowed to.

**Comment by arvindsv** [comment]
Having said that ... the "delete all disabled users" seems like too specific an API to exist. I'd expect people to write a script which goes through all the disabled users, by using the API and submitting "delete user" calls instead. We could look at a "bulk delete users" call, if needed - but this one seems too specific.

I try to see whether API calls are composable. This one doesn't seem to be.

**Comment by varshavaradarajan** [comment]
Bulk delete makes sense. But why wouldn't you want to give an option to delete all disabled users too?

**Comment by arvindsv** [comment]
I'll invoke the "lowly-product-manager" defence here and will let all of you decide. This one is more technical than anything. As I said, to me, it feels like a weirdly specific action to have as an API. But, if you can convince the others, good for you. :)

**Comment by varshavaradarajan** [comment]
Can you tell me what you mean by "weirdly" specific? Why can't an API be specific?

**Comment by ketan** [comment]
I agree with what @arvindsv has to say. A bulk delete API makes sense if you're asking it to delete objects with specific identifiers. Like [this](https://api.gocd.org/current/#bulk-update-agents) or [this](http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html).

What makes me queasy about this api is that it applies an operation (delete) to objects that match a filter (disabled).

**Comment by varshavaradarajan** [comment]
> What makes me queasy about this api is that it applies an operation (delete) to objects that match a filter (disabled).

Why? I think we should have a bulk delete too. But why not this too?

**Comment by ketan** [comment]
>> What makes me queasy about this api is that it applies an operation (delete) to objects that match a filter (disabled).

> Why? So what if its a filter? Why not perform an operation on things that match a filter? I think we should have a bulk delete too. But why not this too?

The idea in such a case would be to introduce a resource called a `filter`, and perhaps call a delete with that filter id:

```http
POST /api/users/filters?where='state=disabled'
```

Response:
```
Location: /api/users/filter/1234
```

Then you perform a delete:

```
DELETE /api/users?filterId=1234
```

Alternatively, do a delete by query API - https://www.elastic.co/guide/en/elasticsearch/reference/1.4/docs-delete-by-query.html

**Comment by varshavaradarajan** [comment]
Closing this. Will open another PR for bulk delete of disabled users.

**Pull request closed without merging**
