### PR TITLE
More human-readable task descriptions in console logs

### PR DESCRIPTION
**Pull request by marques-work**

### CODE REVIEW

**Comment by jyotisingh** [comment]
@marques-work & @kyleolivo  - The tests Ketan and I were talking about:
AntTaskTest:
 
```
    @Test
    public void shouldRetainDoubleQuotesInDescription(){
        antTask.setTarget("\"foo bar\" baz —debug");
        assertThat(antTask.describe(), is("ant \"foo bar\" baz —debug"));
    }

    @Test
    public void shouldRetainSingleQuotesInDescription(){
        antTask.setTarget("'foo bar' baz —debug");
        assertThat(antTask.describe(), is("ant 'foo bar' baz —debug"));
    }
```

**Comment by ketan** [comment]
I'm looking at merging this in...

**Comment by jyotisingh** [comment]
@marques-work - Acceptance tests are failing right now for this build (https://build.gocd.io/go/pipelines/value_stream_map/installers-PR/265). Its basically the assertion for task description in job console log. Could you please send a PR to fix that too?

**Comment by ketan** [comment]
Here's a quick test using these tasks:

```
<tasks>
  <exec command="ls" workingdir="ant">
    <arg>-al</arg>
    <arg>..</arg>
  </exec>
  <ant buildfile="build.xml" target="&quot;default&quot; &quot;-Dfoo=C:\Program Files\foo&quot;" workingdir="ant">
    <runif status="passed" />
  </ant>
  <rake buildfile="Rakefile" target="&quot;boo=C:\Program Files\baz&quot;">
    <runif status="passed" />
  </rake>
</tasks>
```

The output contains:

```
13:15:40.262 [go] Start to execute task: ls -al ...
13:15:40.272 total 4
13:15:40.273 drwxr-xr-x 4 ketanpadegaonkar staff 170 Feb 28 13:15 .
13:15:40.273 drwxr-xr-x 3 ketanpadegaonkar staff 102 Feb 28 13:14 ..
13:15:40.273 drwxr-xr-x 7 ketanpadegaonkar staff 476 Feb 28 13:15 .git
13:15:40.273 -rw-r--r-- 1 ketanpadegaonkar staff 170 Feb 28 13:14 Rakefile
13:15:40.273 drwxr-xr-x 2 ketanpadegaonkar staff 102 Feb 28 13:14 ant
13:15:40.375 [go] Current job status: passed.



13:15:40.375 [go] Start to execute task: ant -f "build.xml" "default" "-Dfoo=C:\Program Files\foo" (workingDirectory: ant).
...
13:15:40.832 [echoproperties] foo=C\:\\Program Files\\foo
...


13:15:40.957 [go] Start to execute task: rake -f "Rakefile" "boo=C:\Program Files\baz".
...
13:15:42.131                               boo = C:\Program Files\baz
...
```

```
$ cat Rakefile
desc "default"
task :default do
  longest_key = ENV.to_h.keys.sort_by(&:length).last.length
  ENV.to_h.each do |k, v|
    puts "#{k.rjust(longest_key)} = #{v}"
  end
end
```

```
$ cat ant/build.xml
<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." default="default">
  <target name="default">
    <echoproperties/>
  </target>
</project>
```

**Comment by ketan** [comment]
@marques-work — if you submit a PR for the functional tests, please have @arvindsv merge that PR and this one as well.

**Comment by jyotisingh** [comment]
This PR was reverted as it breaks all tasks which have a combination of double and single quotes. 

```
2017-03-23 05:51:41,959 ERROR [75@MessageListener for WorkFinder] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@15dee2b3
com.thoughtworks.go.utils.CommandUtils$ParseException: Can't handle single and double quotes in same argument: if [ "${REALLY_REALLY_UPLOAD}" != 'YES_I_REALLY_REALLY_WANT_TO_UPLOAD' ]; then echo "REALLY_REALLY_UPLOAD environment variable should be overridden while triggering."; exit 1; fi
	at com.thoughtworks.go.utils.CommandUtils.shellEscape(CommandUtils.java:85)
	at com.thoughtworks.go.utils.CommandUtils.shellJoin(CommandUtils.java:99)
	at com.thoughtworks.go.config.ExecTask.describe(ExecTask.java:73)
	at com.thoughtworks.go.server.service.builders.ExecTaskBuilder.createBuilder(ExecTaskBuilder.java:41)
	at com.thoughtworks.go.server.service.builders.ExecTaskBuilder.createBuilder(ExecTaskBuilder.java:31)
	at com.thoughtworks.go.server.service.builders.BuilderFactory.builderFor(BuilderFactory.java:66)
	at com.thoughtworks.go.server.service.builders.BuilderFactory.buildersForTasks(BuilderFactory.java:60)
	at com.thoughtworks.go.server.service.BuildAssignmentService$3.surrounding(BuildAssignmentService.java:308)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.transactionSurrounding(TransactionTemplate.java:71)
	at com.thoughtworks.go.server.service.BuildAssignmentService.createWork(BuildAssignmentService.java:295)
	at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:152)
	at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:135)
	at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:56)
	at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:30)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:745)
```

**Pull request merged**
