### PR TITLE
Notify listeners about lock status change only after the transaction is complete (#4448)

### PR DESCRIPTION
**Pull request by akshaydewan**
Since the DB cache is invalidated in the `afterCommit` hook, it was possible for the event listeners to get stale information. With this change the lock status event listeners will get notified only after the transaction has completed.

### CODE REVIEW

**Comment by akshaydewan** [comment]
Don't merge this yet, since there seems to be a functional test failure. I'll look into it.

**Comment by jyotisingh** [comment]
I think I have asked this before, but I seem to be forgetting. Why is doing this in `afterCommit` not good enough since we care about committed transactions alone?

**Comment by jyotisingh** [comment]
If we must to do this as part of `afterCompletion` hook instead of `afterCommit`, then we need to fix notification in case of `stageStatusChanged` event too, but like I said I do not know/remember why this should be done in `afterCompletion`.

**Comment by akshaydewan** [comment]
We are invalidating the cache in the `afterCommit` hook, and we need to notify listeners after that is done. If we have multiple `afterCommits`, the order is unpredictable. So one way around it is to notify listeners in the `afterCompletion` hook.

**Comment by jyotisingh** [comment]
Spoke to @akshaydewan about the two comments:
https://github.com/gocd/gocd/pull/4507#issuecomment-376093430 - we need the notifications to be sent after all the afterCommit blocks have been executed. Since there are multiple afterCommit blocks registered across different classes for a given nested transaction, the only way to ensure all of them are executed before notifying listeners is to do it in the afterCompletion block which comes a little later in the lifecycle after all registered afterCommits have been executed. 

https://github.com/gocd/gocd/pull/4507#issuecomment-376094759 - While we are not aware of any issues with `stageStatusChanged`, going by the theory about unpredictable order of afterCommit, we need to address this too, but changing things around that would require a lot more effort (going through scenarios etc) and can be taken care of in a separate PR.

Merging this PR.

**Pull request merged**
