### PR TITLE
Removing unnecessary url encoding of data passed via jQuery POST. (#2825)

### PR DESCRIPTION
**Pull request by varshavaradarajan**
@arvindsv - Please review.

### CODE REVIEW

**Comment by ketan** [comment]
Why was this needed?

**Comment by varshavaradarajan** [comment]
@ketan, sometime ago, the validation for email address, hostname and port was changed from jQuery get to post. Since, during a post call, the default encoding is already UTF-8, we didn't have to encode it again. The change from get to post was made only for the validity of hostname, port, email address. But we didn't have to do it for sendTestEmail and validateLdapSettings also. Check #2825. 

@arvindsv , I verified for everything but ldap. Will check ldap tomorrow?

**Comment by arvindsv** [comment]
Ok. It should work too. Let me know if anything doesn't or you need help.

**Comment by varshavaradarajan** [comment]
@arvindsv , verified the check LDAP call. Works fine.

**Pull request merged**
