### PR TITLE
Added a blank check for build tasks attributes. (#2753)

### PR DESCRIPTION
**Pull request by varshavaradarajan**
#2753

### CODE REVIEW

**Comment by arvindsv** [comment]
In #2753, something is adding that blank attribute, though (don't know if it's sent over in the JSON request or happening during deserialization). Don't know if this fixes that.

Also, adding this check retroactively (without a config migration to remove the blank values in existing config) might cause issues upon editing one of those configs, right?

**Comment by ketan** [comment]
IMO, we should not be calling the setter unless there's something to be set. Handle this in the representer, should we?

**Comment by varshavaradarajan** [comment]
@arvindsv, In quick edit, we default to a blank string if the user input is not specified. I chose not to default to null on the javascript side because the using the api independently would still have this problem. 
@ketan , we call the setter from the pipeline config API representers. From the old UI, the ```setConfigAttributes``` method on the config entity objects are used which makes these checks anyway, hopefully for all config objects. Doing this check only at the representer would have meant that someone directly editing the xml would still face the issue.

Also, I don't think a config migration was needed because this is not called from the ```validateTree``` method, thus not breaking the existing xml. But only to set the future values to null upon encountering a blank string (while setting it using the api only). We should not be validating these fields as they are optionally provided.

It isn't harmful that the xml may have an empty string for these values as @arvindsv  pointed in the issue, except for the ```buildFile``` attribute. However, if we decide that a config migration is needed, I'll send another PR. :)

**Comment by arvindsv** [comment]
Talked to @varshavaradarajan: Decided not to have a config migration for now. If this has affected anyone, we would have learnt about it.

**Pull request merged**
