### PR TITLE
Upgrade from Rails 5.2 to Rails 6.1

### PR DESCRIPTION
**Pull request by chadlwilson**
**Methodology**
Followed
* https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0
* https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1
* Run `./gradlew railsExec -Pcmd='-S rails zeitwerk:check'` and review

**Testing**
* [x] Build
  * [x] Rspecs passing
  * [x] Regression tests all passing
* [x] Local dev experience validation
  * [x] Error during start. (Not quite sure what happened here, but this went away. Maybe a build cleanliness problem)
  ```
    2022-08-15 23:54:40,682 ERROR [qtp973576304-28] Rails:-2 -
  NoMethodError (undefined method `+' for nil:NilClass):
  
  lib/log4j_logger.rb:21:in `silence'
  ```
  * [x] Logging for rails Slf4j working fine
  * [x] Dynamic reloading working fine/as normal
  * [x] Stack traces coming out on local while debugging 
  * [x] 500 errors from Rack are not being logged anywhere by default
    * Fixed in Rack 2.2.4 which came out recently, funnily enough, not related to Rails upgrade, just made it difficult initially to debug the below 500 error caused by Rails/Jetty interaction
  * [x] 500 errors for all pages in local dev being caused by excessive `Links` response header being added by Rails 6.1. Disabled in dev, as per general recommendations.

* [x] The *Great, Paranoid Brute force manual Ruby/Rails testing* list
   * [x] Overall rendering incl headers/footers etc
   * [x] Rails Stage Details page and all tabs
     * [x] Rails Stage Details page > Config Changed Stage History modal (admin function)
     * [x] Rails Stage Details page > "Run 1 of 2" run switcher dropdown
   * [x] Rails Job/Build Details page and all tabs
     * [x] Rails Job/Build Details page > Job History dropdown
   * [x] Rails Value Stream Map page
     * [x]  Rails Value Stream Map page > general Javascript navigation etc
   * [x] Legacy Admin pages
     * [x] Admin > Config XML (as admin) 
     * [x] Admin > Config XML (as group admin only)
   * [x] Review browser console logs for any unexpected errors from JS

### CODE REVIEW

**Comment by arvindsv** [comment]
Wow! It's amazing that a major-version Rails upgrade affects 33 files! I know it might not be complete yet, but it's still amazing. I remember when [the Rails 2.x to 4.x migration](https://github.com/gocd/gocd/issues/130#issuecomment-41795987) took months. The issue I linked to is just the tip of the iceberg. There were so many discussions and planning before that, and more work after it.

The codebase was much more Rails heavy at that time, of course. The changes over time seem to have made it more maintainable, compared to then.

**Comment by chadlwilson** [comment]
I don't think it's actually working properly. 😅 The regression tests passed, however the server wasn't starting properly locally so I'm pretty suspicious (unless it's something to do with dev mode, haven't tried downloading a built production installer)

But yeah, there's not that much code left compared to then.

**Comment by chadlwilson** [comment]
Believe it or not, it all seems to be kind of working now, just had https://github.com/rails/rails/pull/39939 to workaround locally which was mainly causing the problems. Will keep kicking the tyres over the next little while.

**Comment by chadlwilson** [comment]
This all appears to be working totally fine, and since I have pre-merged and validated the pre-requisite changes already, reducing this change to only 5 files, it's easily rolled back.

Let's give it a whirl on https://build.gocd.org.

**Pull request merged**
