### PR TITLE
Remove some old cruft sitting there.

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by arvindsv** [comment]
Can ```run_rspec_tests.rake``` be removed as well, then? /cc @srinivasupadhya

**Comment by ketan** [comment]
> Can run_rspec_tests.rake be removed as well, then? /cc @srinivasupadhya

I think so, I looked around, but could not find references. I'd rename the `run_rspec_tests_use_new_rails.rake` to `run_rspec_tests.rake` as well.

**Comment by arvindsv** [comment]
Yes, that makes sense to me. Might need to change usages in build.go.cd config.

**Comment by srinivasupadhya** [comment]
sure :+1:

**Comment by arvindsv** [comment]
I've also had my eye on idea-settings.jar and killableprocess.exe, but they can be in a different PR.

**Comment by arvindsv** [comment]
Not merging this yet, till ```run_rspec_tests_use_new_rails.rake``` is removed, since there is a reference to old.go.jruby in it.

**Comment by arvindsv** [comment]
Removed the old file. Renamed the use_new_rails bit. Changed it in all the configs of the Go Servers I know of (including build.go.cd).

**Pull request merged**
