### PR TITLE
Allow Whitelisting of SCM materials, in place of blacklisting. Useful for those of us using a monorepo.

### PR DESCRIPTION
**Pull request by ravenscar**
Currently the blacklisting feature [causes a lot of pain](https://github.com/gocd/gocd/issues/436) for those of us using a mono repo where a simple commit such as a new file added to the base directory may end up triggering hundreds of pipelines.

Several people have suggested hacks to update the `config.xml` every time a file directory is added such as [@scottmuc](https://github.com/gocd/gocd/issues/436#issuecomment-161057277) and [@donaldguy](https://github.com/gocd/gocd/issues/436#issuecomment-207534624) but these are manual processes and can cause problems if someone doesn't know about them.

In this PR I have added an additional checkbox below the filter box for SCM materials. 

If selected this will change the behaviour of `Modifications.shouldBeIgnoredByFilterIn()` such that the file changeset will be ignored iff the set of all files in the changeset are disjoint from files matched by the filter.

I have also added additional unit tests, a config migration, and UI minor additions.

This change is backwards compatible in terms of expected behaviour.

### CODE REVIEW

**Comment by ravenscar** [comment]
Example of the new checkbox, below the Blacklist filter:
image

**Comment by zabil** [comment]
Adding @naveenbhaskar for UX feedback

**Comment by ketan** [comment]
@ravenscar — could you take a look at the failing tests. Login with user `view` and password `password` to see the failures.

**Comment by cv** [comment]
Hi @ketan and @ravenscar! I'm in serious need for this feature, and I'm willing to help out (even if just by fixing the tests, etc). What's the best way to go about it?

**Comment by zabil** [comment]
Hey @cv to start off we'd like help in fixing the tests.

And if you have a set up where you can try this out can you take a build off this PR and try it out?

Once you have the dependencies installed. (java, maven, nodejs) from the checkout folder you can

```
 $ ./bn clean cruise:prepare dist
```

To get the jar files in the target folder

**Comment by cv** [comment]
Excellent, @zabil - I can't push to this PR, so I've merged in these changes and started a new one, referenced above.

**Comment by ravenscar** [comment]
Sorry I've been on holiday and ignoring work completely. @cv looks like you've already fixed everything, thanks! We've been using this for the past 2 months and we haven't run into any problems, hopefully it works well for you.

**Pull request merged**
