### PR TITLE
Changing the page_header to be a fixed element at the top of the page

### PR DESCRIPTION
**Pull request by ibnc**
* This will allow easier navigation back to the job/stage/pipeline level when looking at a long console log

### CODE REVIEW

**Comment by naveenbhaskar** [comment]
image

agents job run history page is broken.
agents page -> click on any agent name

**Comment by ibnc** [comment]
@naveenbhaskar Thanks for taking a look! I just pushed a fix, and validated things locally

**Comment by ibnc** [comment]
Fixed the conflicts.

**Comment by arvindsv** [comment]
I took a look at this. Every page I tried looks good. I tried to put in as much data as I can to get it to scroll. It seems to work fine. One place where the header still scrolled was the preferences page (click on the username on the top right and then "Preferences" - http://localhost:8153/go/tab/mycruise/user).

@naveenbhaskar - Even without this, I think the rest of it is ready to be merged.

**Comment by arvindsv** [comment]
From a functionality perspective, that is.

**Comment by ibnc** [comment]
@arvindsv You're totally right. That page is one of the old VM pages, and the page header style is "page-header" instead of "page_header" like everywhere else. I'll push a fix for this

**Pull request merged**
