### PR TITLE
Disable link to job run history for elastic agents #2913

### PR DESCRIPTION
**Pull request by iamsumanth**
* Remove space between agents table header and body

### CODE REVIEW

**Comment by ketan** [comment]
I feel this is a bit pre-mature. Just because our agents go away immediately after a build does not necessarily mean that all elastic agents go away immediately.

Can we punt on this for a while?

**Comment by varshavaradarajan** [comment]
@ketan if its a long running job on an elastic agent, it is shown on the agents spa with the hostname link broken, right?

**Comment by ketan** [comment]
@varshavaradarajan — no reason for the link to be broken. The link should be broken only when the agent disappears from the config, not otherwise.

**Comment by zabil** [comment]
Modified the issue description. Any relevant information other than page not found.

**Pull request closed without merging**
