### PR TITLE
Get rid of some code that we can delegate down to scrollToFixed

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by arvindsv** [comment]
@ketan: Do you want me to take a look at this before 15.3? Apart from the back to top link overlap thing, if the rest is just a refactor to use scrollToFixed, I'd rather leave it to 15.3, especially since this is not well tested.

If it needs to go in, in 15.2, I'd need to test it quite thoroughly (different browsers, different window sizes and seeing whether that  arrow hides itself properly, etc). I can do it. Or, if you can show it to someone else, that's fine too.

**Comment by ketan** [comment]
Sounds good. I'm going to cherry-pick the fix for the back-to-top link overlap and we'll look at this for 15.3.

**Comment by zabil** [comment]
@ketan is there any work pending on this?

**Comment by ketan** [comment]
This is obsolete, closing

**Pull request closed without merging**
