### PR TITLE
[Do Not Merge]Add XML Migration to support clusterProfileId attribute on profile tag (#5538)

### PR DESCRIPTION
**Pull request by GaneshSPatil**
* Add clusterProfileId attribute on 'profile' tag
* Define a default clusterProfile under elastic/clusterProfiles

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
[Do not merge]
---
Had a conversation with @maheshp, based on which following implementation improvements can be done:

1. Make `clusterProfileId` an optional attribute on elastic agent profile.
  - For EA plugins implemented using 'v4' extension, no need of specifying 'clusterProfileId'.
  - For EA plugins implemented using `v5` extension, `clusterProfileId` is mandatory.
  - Instead of adding an XSD validation for `clusterProfileId` being the mandatory field, we can add this check at the Java Config Entity validation level.

2. As the `clusterProfileId` is an optional field on EA profiles. the EA profiles will continue to work as is, with EA extension v4. **No need for config-migration** (defining `default` cluster config and `default` clusterProfileId on all profiles).

3. Introduce `migrate-plugin-settings-to-cluster-profile` call as part of EA extension v5
  - This call accepts **plugin settings** and returns the **cluster profile**. For many plugins, this call will return the exact same configuration back as of plugin-settings. For plugins which have a different configuration for the cluster profile, will need to take care of migration.
  - Upon plugin upgrade, the server will make a call (once) to migrate plugin-settings to cluster-profile, and define a new cluster will the plugin returned profile. Also, all the profiles belonging that plugin will start referring to the newly created cluster.

---

Few Advantages with above approach:
1. Nothing changes for EA plugins implemented using v4 extension. Neither the elastic profile config entity.
2. The task of config migration of plugin-settings to cluster profile is delegated to plugin. As there will be change in the configurations (different/new settings), plugins will take care of config migrations.

\cc: @bdpiparva @maheshp

**Comment by GaneshSPatil** [comment]
Closing this PR.
Will send another PR to support optional clusterProfileId attribute on elastic agent profiles.
AND
Once we decide upon the plugin settings migration strategy, we can either add the config migration or the new plugin-extension call (`migrate-plugin-settings-to-cluster-profile`).

**Comment by arvindsv** [comment]
@GaneshSPatil @maheshp If someone edits the config directly and removes the clusterProfileId for a v5 plugin, what happens? This might work somehow, but my preference would be to keep the config consistent and not dependent on the version of a plugin.

**Comment by GaneshSPatil** [comment]
@arvindsv -- 

> If someone edits the config directly and removes the clusterProfileId for a v5 plugin, what happens?

The validation of cluster_profile_id can happen at the elastic agent profile entity validation level, where if the plugin used for defining elastic agent profile is on v5, the profile needs to have a cluster_profile_id reference.

> This might work somehow, but my preference would be to keep the config consistent and not dependent on the version of a plugin.

Defining an unused attribute on elastic agents profile might cause confusion. As it refers to a dummy cluster which will not be used anywhere.

**Comment by bdpiparva** [comment]
@GaneshSPatil - I think `migrate-plugin-settings-to-cluster-profile` is the good approach as plugin author can define how the migration should happen.

Instead of calling `migrate-plugin-settings-to-cluster-profile` just make it `migrate(pluginSetting, clusterProfiles, elasticProfiles)` and let the plugin author decide what to do.


> Before Migration

```
requestBodyForMigration = {
	"plugin_settings": {"ACCESS_KEY":"ADSDFDGDGSd", "SECRET_KEY":"dsadasddsgdflkghjkdfg"},
	"cluster_profiles" :[],
	"elastic_profiles" : [...],
        "extension_version": "v5"
}
```

> Migration response from the plugin

```
{
  "plugin_settings": {},
  "cluster_profiles": [
    {
      "id": "default",
      "configuration": {
        "ACCESS_KEY": "ADSDFDGDGSd",
        "SECRET_KEY": "dsadasddsgdflkghjkdfg"
      }
    }
  ],
  "elastic_profiles": [...]
}
```

I think we should also start considering versioning the plugin config as well. That will allow plugin author to migrate same config to different version without breaking plugin compatibility.

WDYT?

**Pull request closed without merging**
