### PR TITLE
Websocket communication (#1098) #1793: enable jetty fragment extension

### PR DESCRIPTION
**Pull request by xli**
Ok, here is jetty fragment extension. Reverted changes merged by #1856.
It simplified implementation of relaxing message size limit. 
But it seems not all websocket impl will have fragment extension.
So, it may have problem when we impl another language agent, which probably is fine, because we may not need fragment anymore (sending small messages)

### CODE REVIEW

**Comment by xli** [comment]
This is ready for review

**Comment by ketan** [comment]
I checked in the morning and there is a deflate extension too. Any reason to not use that instead of our custom gzip?

**Comment by ketan** [comment]
Ignore my comment about custom gzip. I just recall you mentioning it is still in draft

**Comment by ketan** [comment]
@xli — can you resolve conflicts?

**Comment by xli** [comment]
@ketan fixed

**Pull request merged**
