### PR TITLE
Add validation for email length in config #695

### PR DESCRIPTION
**Pull request by arvindsv**
WIP - Need to run PR build and then update functional tests.

### CODE REVIEW

**Comment by cv** [comment]
Looks like this build failed for an unrelated reason - couldn't find the hg binary in the Windows install?

**Comment by arvindsv** [comment]
Hey @cv! Good to see you! I can take care of this PR. As you said, I this the agent provisioning script was wrong and hadn't installed hg. I'll rerun it later.

**Comment by arvindsv** [comment]
Also, I see that your PR adds schema migration for 82. I'll let that go ahead first, and then re-do this one.

**Comment by arvindsv** [comment]
Open too long. Closing for now. Needs re-look.

**Pull request closed without merging**
