### PR TITLE
Fixing styling for validation errors on add pipeline page

### PR DESCRIPTION
**Pull request by ibnc**
Need to wrap the text without throwing off everything else

before:
Screenshot_2019-06-04_at_11 46 26

after:

Screen Shot 2019-06-11 at 14 56 18

### CODE REVIEW

**Comment by ibnc** [comment]
@marques-work @kierarad would one of you mind reviewing this, and merging?

**Comment by marques-work** [comment]
@ibnc I'll look at this now

**Comment by marques-work** [comment]
@ibnc sorry, I did look at this and it looks ok on the surface, but there are some edge cases I wanted to validate. I'll do that today after I clean up my workspace and commit -- then I can build and play around with it.

**Comment by marques-work** [comment]
@ibnc I'm going to remove the `height` property and see if this fixes the edge case where we get a bunch of server validation errors that we couldn't map. This ought to allow the actions section to expand to accommodate.

image

**Comment by marques-work** [comment]
@ibnc ok removing `height: 35px` definitely fixes this.

image

**Pull request merged**
