### PR TITLE
Feature to make loading template a little bit easier

### PR DESCRIPTION
**Pull request by danielsomerfield**
Added a simple feature that if template name starts with "classpath:", then it will search the classpath for the provided fully qualified file.

### CODE REVIEW

**Comment by arvindsv** [comment]
Hi @danielsomerfield. I thought about this, and I think this is useful, and I want to accept it. Especially because plans for deprecation usually take a while to materialize fully (to get out of the codebase, I mean).

It looks like you haven't signed the [CLA](http://www.go.cd/contribute/cla.html) yet. Can you please do that? As soon as you do, I'll accept it. I've been updating the plugin docs recently. I'll add a small note about this, there, as well. I'd ask you to, but since my [PR](https://github.com/gocd/documentation/pull/83) hasn't been accepted yet, it'll conflict with it.

**Comment by danielsomerfield** [comment]
That's cool! Glad it could help.

I can sign it if you need, but I'm a TW employee, so I assume I have already signed my life over to the company :-) 

I haven't had time to look at the new JSON mechanism yet, but I know the SF office is talking about another hack night and I'll see if I can work on it there.

**Comment by arvindsv** [comment]
> I can sign it if you need, but I'm a TW employee, so I assume I have already signed my life over to the company :-)

Ha ha! :) Alright. I saw the name, and wondered, but wasn't sure.

**Comment by arvindsv** [comment]
Ah, I see the email address of your commit, now.

**Pull request merged**
