### PR TITLE
Ldap displayname configuration added

### PR DESCRIPTION
**Pull request by bdpiparva**

### CODE REVIEW

**Comment by arvindsv** [comment]
This PR needs a description.

**Comment by tpbrown** [comment]
This is great! It's really useful to us.

**Comment by ketan** [comment]
Closing in favor of #2956

**Comment by tpbrown** [comment]
@ketan #2956 doesn't address the issue with displayName. 

e.g. - the displayNameAttribute pulled the attribute from the LDAP user data, not the base  data.

The below snippet works with this PR, but does not work with 17.1.0 (of course dropping the displayNameAttribute since it wont be recognized).    In 17.1.0 the users display name will be 'users'.
`<ldap uri="ldaps://ldap.mycompany.com" searchFilter="(uid={0})" displayNameAttribute="cn">
        <bases>
          <base value="cn=users,dc=mycompany,dc=com" />
        </bases>
      </ldap>`

**Comment by arvindsv** [comment]
cc @bdpiparva

**Comment by bdpiparva** [comment]
@tpbrown `displayNameAttribute` is not  part of 17.1 release. https://github.com/gocd/gocd/issues/2956 will take care of displayName and ldap based authorization.

**Pull request closed without merging**
