### PR TITLE
Fix UI issues (#5464)

### PR DESCRIPTION
**Pull request by GaneshSPatil**
* Fix elastic profiles modal width.

#### References:
* https://github.com/gocd/gocd/issues/5464#issuecomment-447135559

#### Screenshot
screen shot 2018-12-17 at 10 56 00 am
screen shot 2018-12-17 at 10 56 08 am

\cc: @akshaydewan @naveenbhaskar @varshavaradarajan

### CODE REVIEW

**Comment by bdpiparva** [comment]
@GaneshSPatil  - Also change the width of config_repo modal

**Comment by GaneshSPatil** [comment]
@bdpiparva -- The internal styles of config repo modals will break if we change the modal width.
Here is a screenshot what I mean:

screen shot 2018-12-17 at 12 28 20 pm
screen shot 2018-12-17 at 12 28 12 pm

**Comment by bdpiparva** [comment]
@GaneshSPatil - I see, but we should be able to adjust it for a large modal

**Comment by akshaydewan** [comment]
I had worked with @naveenbhaskar on the config repo modals and we decided to go with the medium sized modal. The view isn't rendered by a plugin, and we had checked all material types to make sure it looks alright.

I think we should keep the Config Repos as it is, unless there's a good reason to change it.

**Comment by rahulpargaonkar** [comment]
verified the issue on build.gocd. seems fixed

**Pull request merged**
