### PR TITLE
Upgrade Highcharts to v6.2.0

### PR DESCRIPTION
**Pull request by GaneshSPatil**
\cc @maheshp @arvindsv @ketan 

We've Highcharts license for `v6`
Upgrading GoCD core to `v6.x.x` of Highcharts should be fine?

### CODE REVIEW

**Comment by arvindsv** [comment]
@GaneshSPatil Not really. :( We have a limited license. Not an unlimited license like the one for 2.x.

**Comment by GaneshSPatil** [comment]
@arvindsv -- IIRC, we've Highchart's OEM and Enterprise License, which allows us to use Highcharts on 100 instances/applications.

Can you check and let me know?

If we're limited by the usage number, we can close this PR.

**Comment by arvindsv** [comment]
@GaneshSPatil Yes, I think the "100 instances" part will become a problem. Each installation will be considered an "instance". If we add it to the installer (18.10, 18.11, etc) it'll be an instance, is my understanding.

**Comment by GaneshSPatil** [comment]
Ahh. Thanks for the information. :)
Closing this PR.

**Pull request closed without merging**
