### PR TITLE
Docker based integration tests for mercurial

### PR DESCRIPTION
**Pull request by jyotisingh**
To run the docker test, run "mvn -Pdocker-tests verify". This would bring up a docker container with a http based, auth-enabled hg repo. HgMaterialDockerTest relies on this repo to run the tests. On completion, the container is stopped and removed.

Actual change is not a lot, its just that we moved all unit tests to test/unit folder :)

### CODE REVIEW

**Comment by arvindsv** [comment]
@jyotisingh I took a look at this. It looks alright to me. Is there any reason I should not accept this? For instance, are all the agents on build.go.cd setup to run Docker, and is the target (or profile) of these tests setup to be used?

**Comment by jyotisingh** [comment]
@arvindsv  These test run using a different target (mvn -Pdocker-tests verify) which I need to add once the changes get merged. Docker is installed on 5 build.go.cd agents which would be good enough for now, I still need to tag them appropriately. Nothing would start breaking as soon as you merge this, so please accept this :)

**Comment by arvindsv** [comment]
Ok, done.

**Comment by arvindsv** [comment]
> Nothing would start breaking as soon as you merge this ...

Liar. :P

screen shot 2015-03-02 at 4 04 28 pm

I've added those executions into the docker-tests profile. Take a look sometime, and see if they're ok.

**Comment by jyotisingh** [comment]
:P

**Pull request merged**
