### PR TITLE
Pipeline groups & Materials listing API change

### PR DESCRIPTION
**Pull request by srinivasupadhya**
* added material config attributes for the API consumer to use
* added jobs (names) in stage details

sample json:

```json
[
  {
    "pipelines": [
      {
        "stages": [
          {
            "jobs": [
              {
                "name": "job"
              }
            ],
            "name": "stage"
          }
        ],
        "name": "pipeline",
        "materials": [
          {
            "fingerprint": "3ea17fbcc84105952431372f3498e44c86284548b193fd2ff1961995bd737dbd",
            "mercurial-configuration": {
              "url": "\/Users\/sriniup\/Documents\/repos\/hg-repo-1"
            },
            "type": "mercurial"
          },
          {
            "fingerprint": "189a9aa60d9560055bf197e2ba4c25f05505a8c70d2f789198ed5eead36e31fd",
            "git-configuration": {
              "branch": "master",
              "url": "\/Users\/sriniup\/Documents\/repos\/git-repo-1"
            },
            "type": "git"
          },
          {
            "fingerprint": "c37b238467c1740a86b04323787e1141be9e23c8ad49fd376e82536452f20cf6",
            "svn-configuration": {
              "username": "view",
              "check-externals": true,
              "url": "\/Users\/sriniup\/Documents\/repos\/svn-repo-1"
            },
            "type": "svn"
          },
          {
            "fingerprint": "43d9a012f09cd9ac8a01c972682dd02e9c87e1c673bcf79a4f005855687a4695",
            "perforce-configuration": {
              "username": "view",
              "use-tickets": true,
              "view": "view\/path",
              "url": "perforce-repo-1.com:8080"
            },
            "type": "perforce"
          },
          {
            "fingerprint": "9a0d69da5217e858a863f371376dcb75e0de970ccf2ae7ba666ff5aa999e2d8e",
            "tfs-configuration": {
              "username": "view",
              "project-path": "project\/path",
              "domain": "domain",
              "url": "http:\/\/tfs-repo-1.com"
            },
            "type": "tfs"
          },
          {
            "fingerprint": "7ce1e33a256dfc23dfcdbcca9e47a8ab454c4d5561d089406d11388454cb14cd",
            "pipeline-configuration": {
              "pipeline-name": "test",
              "stage-name": "stage"
            },
            "type": "pipeline"
          }
        ],
        "label": "${COUNT}"
      }
    ],
    "name": "first"
  }
]
```

### CODE REVIEW

**Comment by ketan** [comment]
@srini - is there any reason to add to the existing deprecated API instead of porting it over and adding the needed bits?

**Comment by srinivasupadhya** [comment]
@ketan - i will try & port it to newer format sometime soon.

**Comment by ketan** [comment]
When you do, this is going to involve defining a bunch of entities starting from material configs, stage configs, among other config things.

Since this is a huge API change (as compared to the minuscule users and agents api), not just in terms of defining what these entities look like, but what bulk operations one can perform (single page app for updating an entire stage for e.g.) instead of individual pieces like tasks, jobs.

**Comment by ketan** [comment]
Closing this issue, we have opened #1417 instead

**Pull request closed without merging**
