### PR TITLE
#914 - Changed 'Current Time' to 'Job Assigned'.

### PR DESCRIPTION
**Pull request by mdaliejaz**

### CODE REVIEW

**Comment by arvindsv** [comment]
Hmm, technically the job assignment time is different (it's decided on the server), but I get why this is done. Build is red. I can accept this, when it's ok.

**Comment by mdaliejaz** [comment]
How about 'Job Started' or 'Job Picked'?

**Comment by arvindsv** [comment]
I like Started.

**Comment by arvindsv** [comment]
Do you want to see if #930 needs to be fixed, with this? Or, do you want me to accept this?

**Comment by mdaliejaz** [comment]
I'll fix #930 as part of another PR. Please go ahead and merge this :)

**Pull request merged**
