### PR TITLE
Adding auto_update to material health state scope

### PR DESCRIPTION
**Pull request by ibnc**
* Addresses #6030

### CODE REVIEW

**Comment by arvindsv** [comment]
I think I see where this is going, but can you please explain exactly what was happening and how this fixes it? Thank you!

**Comment by ibnc** [comment]
@arvindsv sure.

Here's a run down of the issue:
1. An error occurs for a material update
2. A health state message is created for that material
3. "Poll for new changes" is turned off for that material
4. After the config has been updated, we go through the materials, and remove any health state messages that are no longer relevant because the config changed, i.e. stale messages (see [here](https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/materials/MaterialUpdateService.java#L235))
5. The health state message for the material in question is not removed because, from the health state scoping perspective, nothing has changed. We scope materials [here](https://github.com/gocd/gocd/blob/master/common/src/main/java/com/thoughtworks/go/serverhealth/HealthStateScope.java#L61) using the material's [sql criteria](https://github.com/gocd/gocd/blob/master/domain/src/main/java/com/thoughtworks/go/config/materials/AbstractMaterial.java#L64). While the sql criteria is slightly different for each material type, it never includes `autoUpdate`. So, the health state message never gets considered as stale, and thus is never removed.

The changes here add the `autoUpdate` field to the `HealthStateScope` for materials. So with these changes, when polling is disabled for a material, it's health state messages will be cleaned up.


@arvindsv Let me know if I need to clarify anything I've written here.

**Comment by arvindsv** [comment]
Makes sense to me. I'd prefer if someone else looked at the code, though. Others probably have a more up-to-date view of changes.

One case you should probably consider and verify is updating a material config through the [pipeline config API](https://api.gocd.org/current/#edit-pipeline-config).

A test analogous to [this one](https://github.com/gocd/gocd/blob/add0c661f6f975d3a604e1141658f87c8f076671/server/src/test-integration/java/com/thoughtworks/go/server/materials/MaterialUpdateServiceIntegrationTest.java#L57) might also help make it clear. Or maybe something in MaterialUpdateServiceTest.

**Comment by arvindsv** [comment]
@ibnc Does this work when the pipeline config API is used?

**Comment by ibnc** [comment]
@arvindsv I can confirm that this works even if you update the pipeline config through the pipeline config api

**Pull request merged**
