### PR TITLE
Use a different SQL to load pipeline history based on stage counter (#3464)

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by ketan** [comment]
No tests yet, but I wanted to get @jyotisingh to take a quick look to see if the direction is right.

**Comment by jyotisingh** [comment]
@ketan - Sorry, took me a while to look at this. I think something like this would work.

**Comment by jyotisingh** [comment]
The approach looks good to me. But, I haven't done a thorough analysis of the new queries itself, let me know when this is ready for a full review.

**Comment by GaneshSPatil** [comment]
@ketan @jyotisingh -- any updates on this?

**Comment by ketan** [comment]
No updates, this is a bit risky, right now. I'll work on this over the next few days to be merged in 18.8.

**Pull request closed without merging**
