### PR TITLE
Fix problems with cruise-config encoding

### PR DESCRIPTION
**Pull request by cinex-ru**
Issue: #10895

Description:
Fix problems with cruise-config encoding when saving from admin panel and from task.

### CODE REVIEW

**Comment by chadlwilson** [comment]
Hey there! Any reason you decided to close this PR?

I think you're right that there is likely a problem here on Windows where the (Java) default encoding is not UTF-8. We'd need to think carefully about where/how to address it as changing the behaviour may break backwards compatibility for some folks where we change the default interpretation from cp-1252, and they have certain mismatched characters.

**Comment by cinex-ru** [comment]
> t there is likely a problem here on Windows where the (Java) default encoding is not UTF-8. We'd need to think carefully about where/how to address it as changing the behaviour may break backwards compatibility for some folks where we change the default interpretation from cp-1252, and they have certain mism

Hello.
I found one more related problem and need some time to rework and test this PR. Hope it will be ready today.

**Comment by chadlwilson** [comment]
OK. Yeah, we'd ideally want some unit tests too, although acknowledge that it's a bit difficult in some of these areas.

**Comment by cinex-ru** [comment]
> OK. Yeah, we'd ideally want some unit tests too, although acknowledge that it's a bit difficult in some of these areas.

Yeah, feel like can't do without testing.

**Comment by cinex-ru** [comment]
> OK. Yeah, we'd ideally want some unit tests too, although acknowledge that it's a bit difficult in some of these areas.

I finished but without tests yet. Checked only with manual testing. If thats ok, i can create new PR.

**Pull request closed without merging**
