### PR TITLE
Provide additional status information

### PR DESCRIPTION
**Pull request by ketan**
Removes the fields `status` and `enabled` and replaces them with following -

* `agent_config_status` one of `Enabled`, `Disabled` or `Pending`
* `agent_state` one of `LostContact`, `Missing`, `Idle` or `Building`; `Cancelled` is treated as `Building`
* `build_state` one of `Building` or `Cancelled`

### CODE REVIEW

**Comment by ketan** [comment]
Fix for #1438. Please do not merge since the `PATCH` API does not have the correct semantics (yet)

**Comment by grahamc** [comment]
:fireworks:

**Comment by arvindsv** [comment]
Just for history. Some conversations about this, [here](https://gitter.im/gocd/gocd?at=55db3971004c3e375ad07f4b) and [here](https://gitter.im/gocd/gocd?at=55dda4b66ebe0cd612644370).

**Comment by ketan** [comment]
@grahamc - I'd like for you to take a quick look at the model - `AgentRepresenter` and the controller spec. 

For `PATCH` requests the `enabled` flag which accepted a Boolean, is now a `agent_config_state` flag which takes in `enabled` or `disabled` as inputs.

Let me know if this is what you were expecting.

**Comment by grahamc** [comment]
Just reading the code, 

1. Yes, PATCHing an agent config state enabled / disabled is good.
2. Yes, it *appears* I will be able to determine if an agent is building or not even after it is disabled.

I would be happy to install this locally and test it myself, though, if you can provide a .deb.

**Comment by ketan** [comment]
@arvindsv - this is good to merge

@grahamc - you should be able to find an "experimental" build a couple of hours after the PR is merged. If there are any additional improvements, bugs you find, please file them against #1438.

**Comment by arvindsv** [comment]
Done. Added a small spec for agent_config_state.

**Comment by ketan** [comment]
@grahamc - This API is available starting with build 2409 from the download page - http://www.go.cd/download/

**Comment by arvindsv** [comment]
@ketan, shouldn't this be closed?

**Pull request merged**
