### PR TITLE
Introduce a server health messages API (#4231)

### PR DESCRIPTION
**Pull request by ketan**
```
curl 'http://localhost:8153/go/api/server_health_messages' \
  -H 'Accept: application/vnd.go.cd.v1+json'

[
  {
    "message": "Command Repository",
    "detail": "Unable to upgrade command repository located at server/db/command_repository/default. Message: Could not find default command snippets zip on classpath.",
    "level": "ERROR",
    "time": "2018-01-30T07:34:43Z"
  },
  {
    "message": "Modification check failed for material: URL: tesasdfdt-repo, Branch: master",
    "detail": "Failed to run git clone command STDERR: fatal: repository 'tesasdfdt-repo' does not exist",
    "level": "ERROR",
    "time": "2018-01-30T07:40:47Z"
  }
]
```

### CODE REVIEW

**Comment by d-led** [comment]
the endpoint seems unavailable via the SSL port

**Comment by arvindsv** [comment]
@d-led I tried this just now, on 18.7.0, and it worked. Do these work (below)? They do, for me:

```
curl https://<server>:8154/go/api/agents -k -H 'Accept: application/vnd.go.cd.v4+json'
curl https://<server>:/go/api/v1/health -k
``` 

If none of them work, maybe there's a different problem.

**Comment by d-led** [comment]
@arvindsv will try tomorrow.

**Comment by ketan** [comment]
Works for me too:

```
curl https://build.gocd.org:8154/go/api/v1/health
{
  "health": "OK"
}
```

```
curl https://build.gocd.org:8154/go/api/agents -H 'Accept: application/vnd.go.cd.v4+json' -uview:password
{
  "_links": {
    "self": {
      "href": "https://build.gocd.org:8154/go/api/agents"
    },
    "doc": {
      "href": "https://api.gocd.org/#agents"
    }
  },
  "_embedded": {
...
}
```

**Comment by d-led** [comment]
@ketan oh, sorry. This has probably something to do with my curl on Windows. Tried same from a Linux box, and each of the endpoints worked. 
Bad one:
```
λ curl --version
curl 7.58.0 (x86_64-pc-win32) libcurl/7.58.0 OpenSSL/1.1.0g (WinSSL) zlib/1.2.11 WinIDN libssh2/1.8.0 nghttp2/1.30.0
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy MultiSSL
```

good one:

```
curl 7.45.0 (x86_64-pc-linux-gnu) libcurl/7.45.0 OpenSSL/1.0.2l zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Pull request merged**
