### PR TITLE
Make agents page more responsive

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by ketan** [comment]
Obligatory screenshots:

### 800x600

screen shot 2017-03-18 at 4 15 54 pm

### 1024x768

screen shot 2017-03-18 at 4 16 01 pm


### 1280x1024

screen shot 2017-03-18 at 4 16 13 pm

**Comment by naveenbhaskar** [comment]
fixed

**Comment by naveenbhaskar** [comment]
fixed for 1280 X 760... should we fix for screensize less than that?

**Comment by ketan** [comment]
It seems to render fine upto 800x600 (see first screenshot). I don't feel we need to support anything below that.

**Pull request merged**
