### PR TITLE
Set default destination directory for config repo job artifacts (#5342)

### PR DESCRIPTION
**Pull request by GaneshSPatil**
Fallback on defaults for destination directory of config repo jobs' artifacts.

Artifact Type | Default Value
-------------|--------------
Build             | "" (defaultRoot)
Test              |  `testoutput`

For: #5342

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
#### Tested with following YAML pipeline config:
```
format_version: 3
pipelines:
  TestGoPipelineAPI:
    group: DevOps
    materials:
      mygit:
        git: https://github.com/gocd-contrib/getting-started-repo.git
    stages:
    - Build:
        jobs:
          build:
            tasks:
            - exec:
                command: mkdir
                arguments:
                - "surefire-reports"
            artifacts:
            - test:
                source: surefire-reports
            - build:
                source: surefire-reports
```

#### console log
screen shot 2018-10-29 at 7 43 17 pm

#### Artifacts
screen shot 2018-10-29 at 7 43 58 pm

**Comment by adityasood** [comment]
@GaneshSPatil this does the job. Verified the branch locally.

**Comment by bdpiparva** [comment]
@GaneshSPatil - We are converting config repo artifacts to artifact configs(`TestArtifactConfig` and `BuildArtifactConfig`). Those classes have default values for the destination and that should work for config repo too(I would prefer to fix it over there).

**Comment by GaneshSPatil** [comment]
Closing this PR in favor of https://github.com/gocd/gocd/pull/5356

**DO NOT COPY DEFAULT VALUES AT MULTIPLE PLACES**

**Pull request closed without merging**
