### PR TITLE
Add which as a dependency (#1850)

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by jyotisingh** [comment]
`which` is used to determine  value of JAVA_HOME if its not set already. If JAVA_HOME is set then we do not even need `which`. On the other hand if JAVA_HOME wasn't set and `which` not installed, the only thing that would happen is that `JAVA_HOME` wouldn't be set and so Go wouldn't startup automatically. However, user could install java post Go's install, set JAVA_HOME appropriately and things would start rolling again. With this PR, if `which` is not installed, Go's installation would fail. That doesn't sound right.

**Comment by ketan** [comment]
> With this PR, if which is not installed, Go's installation would fail. That doesn't sound right.

If you're installing via a package manager (yum) that would not happen. In most cases, which is installed, and the package won't fail. However in cases of minimal CentOS installs like on docker, this will pull down which.

In either case, if a package is required by GoCD, it should be declared it in its dependency.

PS: Arguably, on debian packages, we define the jdk as a dependency, which will also cause a similar problem that you describe.

**Comment by arvindsv** [comment]
Yeah. Since it fails in certain cases, as mentioned in #1850, I think we will need to add this dependency.

**Comment by arvindsv** [comment]
Need to ensure that "which" is a package on other RPM distributions, though. Like RedHat/Fedora.

**Comment by ketan** [comment]
I checked it is.

**Comment by ketan** [comment]
> Need to ensure that "which" is a package on other RPM distributions, though. Like RedHat/Fedora.

To add to that, `Requires: foo` can be used to mean install package `foo` or install package that "provides" `foo`.

But just in case -

* http://rpm.pbone.net/index.php3?stat=3&search=which&srodzaj=3
* https://www.rpmfind.net/linux/rpm2html/search.php?query=which

**Pull request merged**
