### PR TITLE
#M8104 Using the full path for plugin controller

### PR DESCRIPTION
**Pull request by zabil**

### CODE REVIEW

**Comment by arvindsv** [comment]
Will need to change auth plugins too.

**Comment by jyotisingh** [comment]
@arvindsv - We don't need to change the plugins, they should already be using the correct url. Or, are you referring to some controller that handles that?

**Comment by arvindsv** [comment]
Ah ok, if the URL was already `/plugin/interact/...` then it's fine. Sorry.

**Comment by jyotisingh** [comment]
Yes, none of the urls were changed. We just need to explicitly specify them in the controllers.

**Pull request merged**
