### PR TITLE
Environment Index Page - Change view to show the environment config for each environment.

### PR DESCRIPTION
**Pull request by varshavaradarajan**
* Add id attribute to environment name on the config index page to fix the link from the dashboard.

@arvindsv , @maheshp , @ketan  - Now that the environments page is a config only page, I am yet to move the environments tab under the admin dropdown as per what we had discussed: https://github.com/gocd/gocd/pull/4157#issuecomment-355881484.  The url now to this page should be `/go/admin/environments` or `/go/environments`? And if its going to be `/go/admin/environments` should we set up redirection from `/go/environments` to `/go/admin/environments`?

Also, because the group by environments is available on the dashboard for view users, this page will be accessible only to super admins. Right? 

@ketan, @maheshp  - I have not deleted `shared/_pipeline.html.erb` because `/go/old_dashboard` is still available at this time. When will it be removed?

### CODE REVIEW

**Comment by arvindsv** [comment]
My answers:

> The url now to this page should be /go/admin/environments or /go/environments?

I think `/go/admin/environments`.

> And if its going to be /go/admin/environments should we set up redirection from /go/environments to /go/admin/environments?

It's optional. I wouldn't be too worried about it.

> Also, because the group by environments is available on the dashboard for view users, this page will be accessible only to super admins. Right?

Yes.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan @gocd/committers -- This might be too late to ask this question, But I think we should consider writing an SPA for environments config.

Few points:
* We shouldn't modify ERBs (actively move towards deleting ruby code)
   - pain to write/debug partials
   - Very difficult to modify/maintain old CSS
* In this PR, the full environment config is shown, which might cause:
  - Lots of unnecessary information on the page (the user might be interested in one)
  - No hyperlinks to a specific environment config.
* Does not support config repo entities:
  - Does not show merge environments
  - Does not show config repo pipelines are unavailable as they are defined in config repo

**Comment by varshavaradarajan** [comment]
> We shouldn't modify ERBs (actively move towards deleting ruby code)

The purpose of this PR was to help get rid of the pipeline instances view (old dashboard), showing the pipeline instances on the env page was unnecessary as people use environments to associate pipelines and agents, which is a config operation. But yes, needs to be replaced by an SPA. Feel free to close the PR if that's what's decided. 

> In this PR, the full environment config is shown, which might cause:
Lots of unnecessary information on the page (the user might be interested in one)

What is the unnecessary information? 

> No hyperlinks to a specific environment config. 

Created one for each env. Once you click on the env name from the dashboard (after grouping by environment), the page scrolls to the specific env. 

> Does not support config repo entities:
Does not show merge environments
Does not show config repo pipelines are unavailable as they are defined in config repo

I moved the existing functionality to this page which was previously showing just a list of environment names (and pipeline instances). Were we ever showing the CR environments (is that what you meant by merge environments?) before? If not, we should, and out of scope for this PR.

For showing CR pipelines are unavailable, we can add those to the list of unavailable pipelines while editing the pipeline section if needed. Again, out of scope for this PR, I would say.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan -- I agree with you that the PR only addresses showing expanded environment config view and moving it under admins section. Though my point is if we're putting in efforts, rather than fixing the page now and again on an SPA, let's just do it once.

**Comment by varshavaradarajan** [comment]
Sure. Closing this then.

**Comment by GaneshSPatil** [comment]
Hi @varshavaradarajan -- after discussing with @goteam, we've decided to work on this PR and merge it and going forward we will migrate this page to an SPA.

**Comment by GaneshSPatil** [comment]
The new environments page link is `/go/admin/environments`, whereas create new environment still points to `/go/environments/new` can we change it to point `go/admin/environments/new`?

**Comment by varshavaradarajan** [comment]
> Can we wait until the entire PR build passes just to verify we havent broken anything?

Up to you.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan -- would you mind fixing the padding issue and resolving the conflicts? post that the PR can be merged

**Comment by GaneshSPatil** [comment]
@varshavaradarajan -- can you check the build failures on this PR?

**Comment by GaneshSPatil** [comment]
@rajiesh @maheshp -- MERGING THIS PR. we have been sitting on this PR for a while now. unit and integration tests are green. If any of the functional tests fail, I will send another PR to fix them.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan -- we've decided not to expand the view by default as its showing all the information even if it's not required. also, the config repo pipelines are showing up on the new environments page. 
I will be reverting this PR and will send a new PR with the following changes:
1. Move environments under the admins' section and remove it from the top-level menu.
2. Add a redirect from `/go/environments` to `/go/admin/environments`

**Pull request merged**
