### PR TITLE
Ensure collapse/expand all link is always present

### PR DESCRIPTION
**Pull request by marques-work**
Should fix https://github.com/gocd/gocd/issues/3367

### CODE REVIEW

**Comment by ketan** [comment]
Unless I'm missing something. The default state of the page is collapsed and the link says "collapse all" instead of "expand all"?

**Comment by marques-work** [comment]
@ketan before https://github.com/gocd/gocd/pull/3398 the last section would be expanded; now that this is not the case, it does make sense to flip the default state. I'll do that now.

**Comment by arvindsv** [comment]
Merging this so @marques-work is not blocked. @ketan needs to take a look.

**Comment by ketan** [comment]
> Merging this so @marques-work is not blocked. @ketan needs to take a look.

LGTM. I was just waiting on the build to go green.

**Pull request merged**
