### PR TITLE
Expose Config Repo Contract to Plugins

### PR DESCRIPTION
**Pull request by ibnc**
This is extracting out the config repo contract and codecs into a separate module so that both the server and plugins will have access to them.

See #5374 for more details/discussion 

@arvindsv @ketan @maheshp I'm unsure what my next step should be as far as building and publishing this module...

### CODE REVIEW

**Comment by ketan** [comment]
LGTM. As far as building and publishing this as a jar is concerned, we do that here:

https://github.com/gocd/build_utilities/blob/master/upload-to-maven#L71-L90

Basically, the installer pipeline publishes the api jar, which is then pulled down by the task above in `UploadInstallers` pipeline to publish to maven central.

For this PR:

You seem to have checked in the .class files from idea :)

Apart from this — I believe we need some discipline in maintaining the classes in this package, primarily because these are "API".

Is there some tooling available that'll break the build in case there's an API breakage? I'm familiar with http://javadiff.sourceforge.net/ and https://github.com/melix/japicmp-gradle-plugin, I'm sure there are other tools that do the job. These tools usually check the current jar against a known "reference" api jar and generate a api diff report.

**Comment by ibnc** [comment]
@ketan lol, you're totally right. I just pushed a commit to remove those .class files.

**Comment by ibnc** [comment]
@ketan I suspect that the [ConfigConverterTest](https://github.com/gocd/gocd/blob/master/server/src/test-fast/java/com/thoughtworks/go/config/ConfigConverterTest.java) will provide enough coverage to ensure that the module will be correct... What do you think?

**Comment by ibnc** [comment]
What do you think about bundling go-plugin-api and go-plugin-config-repo into a single build artifact to make the changes on the build_utilities side simpler? It'd allow for a single download

**Comment by ketan** [comment]
> @ketan I suspect that the [ConfigConverterTest](https://github.com/gocd/gocd/blob/master/server/src/test-fast/java/com/thoughtworks/go/config/ConfigConverterTest.java) will provide enough coverage to ensure that the module will be correct... What do you think?

Renaming something in the IDE will silently change the tests without us realizing that API has been broken.

**Comment by ketan** [comment]
> What do you think about bundling go-plugin-api and go-plugin-config-repo into a single build artifact to make the changes on the build_utilities side simpler? It'd allow for a single download

There's a case to be made about similar interfaces for other plugin types. I feel having separate jars is probably better (so plugins can depend on the smallest possible subset of things).

**Comment by ketan** [comment]
If you're looking for help publishing this module to maven central, I can help you walk through the code. I believe @arvindsv should be able to do that as well.

**Comment by ibnc** [comment]
@ketan What is the Jar that I should be comparing to?

Also, I'm unsure how this will help ensure the api is working properly in the future. I can see how it'd ensure things are correct right now, but I don't see the benefit of adding a break point in the build for this check. 

Maybe I'm not understanding things. Do you have an example I could look at to help illuminate things?

**Comment by arvindsv** [comment]
@ibnc - Ketan's on vacation. I can probably work with you on this tomorrow or day after, if you want.

**Comment by ibnc** [comment]
@arvindsv Then I guess my question would be, is this required work before the PR can be merged? I think this can be follow up work that I can do after having a conversation with @ketan when he's back from vacation.

**Comment by arvindsv** [comment]
I don't have enough context to merge it anyway, without working with you on it. So, I guess we can wait till Ketan's back.

**Comment by ibnc** [comment]
@ketan @arvindsv Another thing to note is that the ConfigConverterTest hasn't changed beyond the imports changing. So the tests are still valid. The only renaming that was done is the package change. The actual class names are all the same. I don't think we need to worry about this for this PR.

@arvindsv if you're not comfortable reviewing/merging this PR, then would you mind taking a look @marques-work?

**Comment by ketan** [comment]
LGTM. I'll merge this today (after talking to @arvindsv)

**Pull request merged**
