### PR TITLE
Update material editor for supporting packages and scm materials

### PR DESCRIPTION
**Pull request by kritika-singh3**
Issue: #6737, https://github.com/gocd/gocd/pull/7904#issuecomment-603317125

Description: added support to add reference of a pkg/scm material to the pipeline
Show case error message
1. Packages
 - no package repo plugins are installed
 - no package repositories defined
 - if the selected pkg repo has no valid plugin
 - if there are no pkgs defined for the selected pkg repo
2. Pluggable SCMs
 - no scm plugins are installed
 - no scms defined
 - if there are no scms defined for the selected plugin

Preview:

Screen Shot 2020-03-27 at 12 34 08 AM

Screen Shot 2020-03-27 at 1 30 29 AM

Screen Shot 2020-03-27 at 1 30 35 AM

### CODE REVIEW

**Comment by kritika-singh3** [comment]
Update Preview:

pkg-updated-preview

**Comment by GaneshSPatil** [comment]
@kritika-singh3 - I might be late to the party :(

With the Package Repo and Package Material fields shown side by side, it makes it difficult to read these configurations as the sometimes the config values are split across two lines. Example: `Id`, `Description`  and `URL` in this case.

I would prefer rendering one key=value in 100% width.

We can render the `Package Repository` configurations under its dropdown,  **_Collapsed by default_**.
And, similarly we can render the `Package` configurations under the `Package` dropdown, **_Collapsed by default_**.

---

Another Thought,

With plugins providing the view for the configuration, rendering the config in a key-value view is not always the best idea, as the plugin might contain **_optional_**, **_mutually-exclusive_** and sometimes **internal**  config fields. And GoCD Server does not have this knowledge, to render them as per their importance.
An example of such plugin view is: `Kubernetes Elastic Agent Plugin Elastic Configuration View`, where there are `optional`, `mutually-exclusive` and `internal` fields too. Not sure if there is a package-repo plugin with these complexities :)

So, can we instead make use of the plugin view itself and render it in read-only format? And the view can be exapnd-collapsible, collapsed by default.

This is just a thought, can be ignored, if we've had these conversations. :)

**Comment by kritika-singh3** [comment]
@GaneshSPatil You are not! 😄 
>We can render the Package Repository configurations under its dropdown, Collapsed by default.
And, similarly we can render the Package configurations under the Package dropdown, Collapsed by default.

Any reason for it being collapsable? IMO the widget is required to add the selected package/scm as a material to the pipeline. The configs are provided as readonly. Making them collapsable does not seem right to me.

> So, can we instead make use of the plugin view itself and render it in read-only format? And the view can be exapnd-collapsible, collapsed by default.

This is a question which differs from apps to apps. Some UX guide suggest (which I agree with) that showing readonly info in a disabled input raises the question as to why they are disabled - is there some switch which, when turned on, makes them editable or did the user make some mistake.

Hence, I'm not in favour of disabled/readonly input fields. But if my point does not seem valid for our app, will make that change.

cc:\ @streisguth @arvindsv @maheshp

**Comment by arvindsv** [comment]
Yes, in an ideal world, disabled would give the wrong impression and we should replace it with a proper set of keys / values. Your point about UX is well made.

But, the point Ganesh made about the k8s plugin and ending up showing conflicting values is fair too. That might confuse users even more.

Maybe we can call out that it is readonly in some other way or make it clear somehow? I can't think of any way at this time. Maybe the others have ideas.

**Comment by maheshp** [comment]
Does it make sense to use some kind of display value, similar to [getConfigForDisplay](https://github.com/gocd/gocd/blob/master/config/config-api/src/main/java/com/thoughtworks/go/domain/packagerepository/PackageRepository.java#L230) . Also provide a link to view/edit the package repository.

**Comment by kritika-singh3** [comment]
@maheshp The said method `getConfigForDispaly` outputs a single string with non-secure configuration.
E.g. `Repository: [repo_url=https://npm.root.com]` (You can view the same by adding a package to a pipeline and viewing the rails based pipeline edit page).

Screen Shot 2020-03-31 at 10 12 17 AM

I would prefer a key-value combination over a single string.

>Also provide a link to view/edit the package repository.

Will a link to edit the package repository suffice or link to view is needed as well?

**Comment by streisguth** [comment]
I agree with @kritika-singh3 about not having read-only inputs display the same way as disabled inputs. Can we append 'Read Only' to the title of a disabled selection?

Example:
Screen Shot 2020-03-31 at 12 54 59 PM

One more piece of feedback: there should be a break in the lines that span across both dropdown sections (highlighted below).

Screen Shot 2020-03-31 at 12 57 21 PM

**Comment by kritika-singh3** [comment]
@streisguth The sections are disabled due to there being no options to select from.
E.g. there are no package repositories configured, or for a selected one, there are no packages to select.
IMO, in such cases, the `Read only` tag will not make sense because there may be no configurations to show. WDYT?

**Comment by arvindsv** [comment]
I'm slowly leaning towards a key-value pair as shown above. One other option I'm considering is:



In this way, it is clear that the view is supposed to be read-only and it allows the rich plugin view that might come from the plugin. Otherwise, key-value pair might be better.

**Comment by kritika-singh3** [comment]
Update Preview:

update-material-editor

**Comment by kritika-singh3** [comment]
Preview on Add new pipeline wizard:

update-pipeline-wizard

**Comment by arvindsv** [comment]
@kritika-singh3 I think it will be nice to add a link to create a new SCM or package to this screen / component.

Create_New

It would link to the corresponding page. It's possible a person doesn't have permission to go there and I think that's ok.

To think about: If that link opens in a new page and they create one and come back, is it possible to show the newly created package / SCM or do they need to refresh. Either is ok, but the first is preferable, of course.

**Comment by kritika-singh3** [comment]
@arvindsv After creation of new package/scm, the users would need to refresh the page.
IMO creation of package repositories, packages (not sure about pluggable scms) are usually part of initial setup configuration. If we want to update the wizard as they are created - it would require us to poll the get all APIs for them. Not sure if that is a good idea network wise.

**Comment by arvindsv** [comment]
@kritika-singh3 Ok. Understood. Let's then link to the page and expect needing a page refresh? It's better than not having that link there, imo.

**Comment by kritika-singh3** [comment]
@arvindsv Sounds good to me!

**Comment by mrmanc** [comment]
> It would link to the corresponding page. It's possible a person doesn't have permission to go there and I think that's ok.

This looks better than where we are now. What permissions would be required for this? I’m hoping that the average user will be able to create new materials, otherwise they won’t be able to self-create their pipelines.

**Comment by arvindsv** [comment]
@mrmanc All pipeline group administrators can create them. It's not (yet?) incorporated into the [granular policy](https://docs.gocd.org/current/configuration/policy_in_gocd.html), and so it can't be controlled _which materials_ they will be able to control, but you just need to be a pipeline group admin.

**Comment by arvindsv** [comment]
Given that: My point about "It's possible a person doesn't have permission to go there" is moot. View users won't be seeing the pipeline creation page anyway.

@kritika-singh3 asked me to say: Group admins or system admins can manage materials. If security is disabled, everyone is a system admin anyway.

**Comment by kritika-singh3** [comment]
Preview:

1. No plugins installed

Screen Shot 2020-04-10 at 9 43 05 AM

Screen Shot 2020-04-10 at 10 23 15 AM

2. SCM selected

update-pipeline-wizard-scm

**Comment by kritika-singh3** [comment]
3. No package repos defined

Screen Shot 2020-04-10 at 10 26 03 AM

4. Package selected

update-pipeline-wizard-package

**Comment by maheshp** [comment]
There are further changes to this PR in - https://github.com/gocd/gocd/pull/8021

**Comment by arvindsv** [comment]
@maheshp I've marked https://github.com/gocd/gocd/issues/7022 and https://github.com/gocd/gocd/issues/2947 as QA Done, based on this PR. Assuming you checked that behaviour as well.

**Comment by maheshp** [comment]
There are changes to the new PipelineConfig SPA which needs to be verified, which can be done later as this PR is marked as part of the PipelineConfig Rewrite project as well.

**Pull request merged**
