### PR TITLE
Disable autocompletion, autocapitalization and spellchecking...

### PR DESCRIPTION
**Pull request by Vyax**
…when searching for pipelines

### CODE REVIEW

**Comment by Vyax** [comment]
I'm on 18.5.0. Has the search bar been removed completely in the newer releases?

**Comment by arvindsv** [comment]
@Vyax It has been replaced and should be better! Take a look at https://www.gocd.org/releases/#18-8-0

**Comment by Vyax** [comment]
Okay, I haven't tried it yet.

**Comment by ketan** [comment]
I just checked the newer dashboard, which has this:

```html
<input autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" type="text" placeholder="Search pipelines" data-prop-name="searchText" class="pipeline-search pipeline-search_dashboard">
```

Close this as "FIX_NOT_NEEDED" ;) ?

**Pull request closed without merging**
