### PR TITLE
Remove solaris installer code

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by sriramnrn** [comment]
Wow.. why is this being removed !? We are using this on my current project !!!

**Comment by ketan** [comment]
We've not provided solaris installers for the past couple of releases now.

https://github.com/gocd/gocd/issues/1946
https://groups.google.com/forum/#!topic/go-cd/sw9hLBX8iDY

You can continue to use

**Comment by ketan** [comment]
Fat fingered the send button –

You may continue to use the zip installers, but solaris support would be on a best effort basis, since the team can no longer justify building and testing installers on solaris for the few downloads that the installers receive.

**Comment by sriramnrn** [comment]
Thanks for the link to the forum topic. I have certainly not been keeping track of everything on GoCD. Also, we had installed the GoCD agent for Solaris last November and have been upgrading it since then.

My situation at my current client is going to get tricky, since we have commercial support for GoCD here, and didn't get a formal EoL notification.

**Pull request merged**
