### PR TITLE
Fix misspelling in stages widget

### PR DESCRIPTION
**Pull request by webdevwilson**
Maybe I am OCD, but these really bugged me.

### CODE REVIEW

**Comment by ketan** [comment]
Hi —

Thank you for the fixes. May I ask that you author your commits using the same email address you use on github, or add the email address `kerry[at]reluscloud.com` to your github profile so we can verify it's really you :)

Thanks.

**Comment by webdevwilson** [comment]
Doh. Started a new consulting gig and now juggling a lot of git configs. It's fixed now.

**Comment by arvindsv** [comment]
Hmm, it still shows that - and so, the CLA bot is still saying it's not signed. Maybe you forgot to force push it, @webdevwilson?

**Comment by webdevwilson** [comment]
My bad. I didn't know about the CLA. It is good to go now.

**Comment by arvindsv** [comment]
Indeed it is. Thank you!

**Pull request merged**
