### PR TITLE
New theme fixes

### PR DESCRIPTION
**Pull request by naveenbhaskar**

### CODE REVIEW

**Comment by bdpiparva** [comment]
1) Problem in config.xml edit

**Comment by bdpiparva** [comment]
2. Breadcrumb alignment issue still persist
3. console/Failures log still having issue with floating toolbar 

screen shot 2016-12-02 at 12 06 09 pm

**Comment by ketan** [comment]
I think there's a typo in the font name — all fonts are falling back to Arial instead of "Open Sans"

**Comment by ketan** [comment]
@naveenbhaskar —

```

**Comment by ketan** [comment]
Merged via 7cd56f28bf55417221a608140e72532de5501f5a

**Pull request closed without merging**
