### PR TITLE
Add deprecation warning message on plugins page for elastic agent plugins not supporting cluster profiles.

### PR DESCRIPTION
**Pull request by viraj2712**

### CODE REVIEW

**Comment by viraj2712** [comment]
* Screenshot for deprecartion warning message

Screenshot 2019-04-16 at 4 33 37 PM

**Comment by maheshp** [comment]
@viraj2712 IMO the warning should be more prominent. 

\\cc @naveenbhaskar

**Comment by adityasood** [comment]
@viraj2712 just an observation, maybe we can skip the plugin id in the message, makes it more readable. This is per plugin and is understood IMO.

**Comment by viraj2712** [comment]
* Updated deprecation warning message

Screenshot 2019-04-16 at 6 26 34 PM

\cc @maheshp @adityasood @naveenbhaskar @GaneshSPatil

**Comment by GaneshSPatil** [comment]
Can we modify the message to 
`Deprecated!
Plugin with id 'cd.go.contrib.elasticagent.kubernetes' is implemented using a deprecated Elastic Agent extension version which does not support defining cluster profiles. Deprecated Elastic Agent extension will be removed in upcoming releases, which will cause this plugin to not work. We recommend you to upgrade this plugin to the latest version.
` ?

\cc: @rajiesh @maheshp @adityasood -- suggestions?

**Comment by adityasood** [comment]
@GaneshSPatil the message is for plugin users, the majority of whom might not be worried why/how the plugin is deprecated. The message should be simple and highlight the base reason and recommendation to upgrade.

**Comment by naveenbhaskar** [comment]
The warning icon has to be very visible and show the message on a tooltip. Lets use a red warning icon for this.

image

**Comment by maheshp** [comment]
> Lets use a red warning icon for this.

Don't we use red for errors, this is more a warning.

**Comment by viraj2712** [comment]
* Updated deprecation message:

Screenshot 2019-04-18 at 4 30 26 PM

\cc: @GaneshSPatil @naveenbhaskar @adityasood @maheshp

**Comment by viraj2712** [comment]
Updated deprecation warning

Screenshot 2019-04-19 at 10 58 29 AM

\cc: @GaneshSPatil @naveenbhaskar @adityasood @maheshp

**Comment by viraj2712** [comment]
* Updated deprecation warning message:

Screenshot 2019-04-19 at 12 36 06 PM

\cc: @maheshp @GaneshSPatil @adityasood

**Pull request merged**
