### PR TITLE
#795 - CCTray Perf Fix

### PR DESCRIPTION
**Pull request by arvindsv**
This is a parallel implementation of cctray, available at /go/new_cctray.xml (for now). It reuses much of the existing code, but implements caching in a better way (as mentioned in the mail referenced in #795).

Still need to verify the performance benefits of this. But, this can be accepted if someone has the time to review it, since it is implicitly feature toggled (since the URL is new).

### CODE REVIEW

**Comment by arvindsv** [comment]
Personal build is green: go/pipelines/value_stream_map/personal-arvind/7 on 05.

**Comment by arvindsv** [comment]
Some performance numbers are [here](https://github.com/gocd/gocd/issues/795#issuecomment-73578607).

**Comment by mrmanc** [comment]
Hi… just got here from the release notes for 15.1 and thought I’d mention that the URL mentioned in the first message is no longer correct—would it be worth editing it to indicate that the url is not `/go/new_cctray.xml`?

**Comment by arvindsv** [comment]
Done.

**Pull request merged**
