### PR TITLE
Add id on config repo validation errors

### PR DESCRIPTION
**Pull request by GaneshSPatil**
#### Current
screen shot 2017-07-24 at 3 24 00 pm

##### Proposed
screen shot 2017-07-24 at 3 45 41 pm

### CODE REVIEW

**Comment by jyotisingh** [comment]
@GaneshSPatil - Change looks fine, but since we are adding the repo-id here, I guess we should add it to `RepoConfigOrigin.displayName()` as well to make sure the id shows up at other places too. 
Rebase please.

**Comment by ketan** [comment]
Can you add a test to verify that credentials are not leaked with these two materials:

* `<svn url='https://foo:bar@example.com/svn/my-project' />`
* `<svn url='https://example.com/svn/my-project' username='foo' password='bar' />`

**Comment by jyotisingh** [comment]
@GaneshSPatil - I think we need to rephrase some of the messages in this PR based on the discussion we had yesterday - about the terms like 'config repo' etc

**Comment by ketan** [comment]
@GaneshSPatil @jyotisingh — can we close this PR if not relevant, or rebase and merge if relevant?

**Pull request closed without merging**
