### PR TITLE
Remove the pipeline pause, unpause, schedule and unlock apis from rails.

### PR DESCRIPTION
**Pull request by varshavaradarajan**
* There are versioned spark APIs available for this now.

### CODE REVIEW

**Comment by ketan** [comment]
These are still used from the old dashboard (and environments page)

**Comment by varshavaradarajan** [comment]
What did we decide to do about the old dashboard and environments page? I thought the env page will be a config only page and that we were getting rid of the old dashboard page? @arvindsv - can I move the milestone on this or should I close the PR?

**Comment by arvindsv** [comment]
Yes. The old dashboard and environments pages will go soon. The environments functionality will be combined into the dashboard: https://github.com/gocd/gocd/pull/4820

**Comment by ketan** [comment]
This change looks good, I'll pile more changes to this to remove the dashboard and pipelines on the environments page.

**Comment by marques-work** [comment]
Environments functionality is now trackable on #5006

**Pull request merged**
