### PR TITLE
Config Repo Contract V3

### PR DESCRIPTION
**Pull request by ibnc**
* Adds the ability to fetch configuration files for a plugin and repo

Part of #6611 

Plugin PRs implementing endpoint:
JSON: https://github.com/tomzo/gocd-json-config-plugin/pull/49
YAML: https://github.com/tomzo/gocd-yaml-config-plugin/pull/126

### CODE REVIEW

**Comment by ibnc** [comment]
@tomzo @marques-work 

Would one of y'all mind reviewing this?

**Comment by tomzo** [comment]
@ibnc  once you add the test, I'll merge this, then I'll release plugins and make a PR to bundle the new versions.

**Comment by arvindsv** [comment]
This should only be merged after 19.7 (which should be coming out in the next day or so). There is a problem with the EC2 nodes running out of IOPS, causing some regression pipelines to fail, which is making it harder than usual to get the right builds out. Thank you!

**Comment by ibnc** [comment]
@tomzo Is there a reason why we can't just make `ConfigFilesResponseMessage#gitFiles` return an empty list if files is null? Receiving null is essentially the same as receiving the empty list. I do agree tho that the plugins should be returning an empty list rather than null tho

**Comment by tomzo** [comment]
My point was that if a plugin returns an invalid message, e.g.
```json
{}
```
Or
```json
{
   "files-bogus-field-name" : [ "a.yaml"] 
}
```
Then in both cases it would deserialize to an object with `null` in (the correct) `files` field.

**Comment by ibnc** [comment]
@tomzo would you mind taking another look?

**Comment by tomzo** [comment]
@ibnc thanks, looks perfect now.

I see that 19.7 is out, so we just need a rebase and this can be merged.

**Pull request merged**
