### PR TITLE
Display Duration on VSM

### PR DESCRIPTION
**Pull request by rohitggarg**
Per #3445 the approach has a problem on the API side when build state is unknown.
1. Added the check for Build state being unknown
2. Removed the Display part so that the diff is only on the API side.

Please take a cue from this one and update #3472

### CODE REVIEW

**Comment by ketan** [comment]
Just trying to confirm that you want me to point to this difference between this PR and #3472


```patch
diff --git a/server/webapp/WEB-INF/rails.new/app/models/value_stream_map_model.rb b/server/webapp/WEB-INF/rails.new/app/models/value_stream_map_model.rb
index 069f2dd24f..c4e4b04820 100644
--- a/server/webapp/WEB-INF/rails.new/app/models/value_stream_map_model.rb
+++ b/server/webapp/WEB-INF/rails.new/app/models/value_stream_map_model.rb
@@ -112,7 +112,11 @@ class VSMPipelineInstanceModel
     @counter = counter
     @locator = ""
     @locator = pdg_path_partial.call name, counter unless counter == 0
-    @stages = stages.map { |stage| VSMPipelineInstanceStageModel.new(stage.getName(), stage.getState().to_s, stage.getDuration().getTotalSeconds(), stage.getCounter(), name, counter, stage_detail_path_partial) }
+    @stages = stages.map do |stage|
+      state = stage.getState()
+      duration = stage.getDuration().getTotalSeconds() if state != StageState::Unknown
+      VSMPipelineInstanceStageModel.new(stage.getName(), state.to_s, duration, stage.getCounter(), name, counter, stage_detail_path_partial)
+    end
   end
 end
```

**Comment by rohitggarg** [comment]
That is correct + The tests as well

**Comment by ketan** [comment]
> That is correct + The tests as well

Perfect, I'll lift just the diff I pasted in the comment above, and any corresponding tests.

**Comment by ketan** [comment]
Closing in favor of #3472.

**Pull request closed without merging**
