### PR TITLE
Add support for proxies

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by ketan** [comment]
A build is still running, you should see some installers in another 10 minutes or so at https://build.gocd.org/go/tab/build/detail/installers-PR/633/dist/1/dist. Please make sure to use both the server and agent from that build.

To connect an agent through the proxy, you'd need to setup 2 variables on your agent:

```
AGENT_BOOTSTRAPPER_JVM_ARGS='-Dhttp.proxyHost=... -Dhttp.proxyPort=...'
AGENT_STARTUP_ARGS='-Dhttp.proxyHost=... -Dhttp.proxyPort=...'
```

**Comment by dnewhook** [comment]
Thanks for the build.  I deployed the rpm package on a RHEL 7 VM and used the agent zip file on a separate server.  From the server where the agent is deployed, I'm able to curl the GO_SERVER_URL through the forward proxy but the bootstrapper fails (see output below).

```
export GO_SERVER_URL=https://[vf go server host]:[vf proxy port]/go
export AGENT_BOOTSTRAPPER_JVM_ARGS='-Dhttp.proxyHost=[vf proxy host] -Dhttp.proxyPort=[vf proxy port]'
export AGENT_STARTUP_ARGS='-Dhttp.proxyHost=[vf proxy host] -Dhttp.proxyPort=[vf proxy port]'
```

go-agent-bootstrapper.out.log
```
[Thu Sep 14 11:54:23 CEST 2017] Starting Go Agent Bootstrapper with command: /opt/SP/app/jre/bin/java -Dhttp.proxyHost=[vf proxy host] -Dhttp.proxyPort=[vf proxy port] -jar /opt/SP/app/go-agent2/agent-bootstrapper.jar -serverUrl https://[vf go server host]:[vf go server port]/go
[Thu Sep 14 11:54:23 CEST 2017] Starting Go Agent Bootstrapper in directory: /opt/SP/app/go-agent2
[Thu Sep 14 11:54:23 CEST 2017] AGENT_STARTUP_ARGS=-Dcruise.console.publish.interval=10 -Xms128m -Xmx256m    -Djava.security.egd=file:/dev/./urandom
```

go-agent-launcher.log
```
2017-09-14 11:54:23,619  INFO [TouchLoopThread-2] Lockfile:102 - Using lock file: /opt/SP/app/go-agent-17.11.0/.agent-bootstrapper.running
2017-09-14 11:54:28,932 ERROR [main] ServerBinaryDownloader:80 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error:
org.apache.http.conn.ConnectTimeoutException: Connect to [vf go server host]:[vf go server port] [[vf go server host]/[vf go server port]] failed: connect timed out
```

Here is the curl output showing connectivity via the proxy
```
[vf go server host]$ curl -v --insecure -x http://[vf proxy host]:[vf proxy port] https://[vf go server host]:[vf go server port]
* About to connect() to proxy [vf proxy host] port [vf proxy port] (#0)
*   Trying [vf proxy ip]...
* Connected to [vf proxy host] ([vf proxy ip]) port [vf proxy port] (#0)
* Establish HTTP proxy tunnel to [vf go server host]:[vf go server port]
> CONNECT [vf go server host]:[vf go server port] HTTP/1.1
> Host: [vf go server host]:[vf go server port]
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
```

**Comment by dnewhook** [comment]
I got further by passing Dhttps parameters.  I think the bootstrapper is now working.
```
AGENT_STARTUP_ARGS=-Dhttp.proxyHost=[vf proxy host] -Dhttp.proxyPort=[vf proxy port] -Dhttps.proxyHost=[vf proxy host] -Dhttps.proxyPort=[vf proxy port]
AGENT_BOOTSTRAPPER_JVM_ARGS=-Dhttp.proxyHost=[vf proxy host] -Dhttp.proxyPort=[vf proxy port] -Dhttps.proxyHost=[vf proxy host] -Dhttps.proxyPort=[vf proxy port]
```
Here is the output of go-agent-launcher.log - bootstrapper is getting files from the server but launching the agent without the Dhttp or Dhttps parameters.
```
2017-09-14 13:01:25,398  INFO [TouchLoopThread-2] Lockfile:102 - Using lock file: /opt/SP/app/go-agent-17.11.0/.agent-bootstrapper.running
2017-09-14 13:01:25,976  INFO [main] ServerBinaryDownloader:106 - Downloading agent.jar
2017-09-14 13:01:26,028  INFO [main] ServerBinaryDownloader:113 - Got server response
2017-09-14 13:01:26,524  INFO [main] ServerBinaryDownloader:121 - Piped the stream to admin/agent
2017-09-14 13:01:26,525  INFO [main] PerfTimer:53 - Performance: Downloading new admin/agent with md5 signature: [removed] == took 548ms
2017-09-14 13:01:26,526  INFO [main] JarUtil:69 - Attempting to load Go-Agent-Bootstrap-Class from agent.jar File:
2017-09-14 13:01:26,527  INFO [main] JarUtil:84 - manifestClassKey: Go-Agent-Bootstrap-Class: com.thoughtworks.go.agent.AgentProcessParentImpl
2017-09-14 13:01:26,529  INFO [main] AgentProcessParentImpl:51 - Agent is version: 17.11.0-5387
2017-09-14 13:01:26,681  INFO [main] ServerBinaryDownloader:106 - Downloading agent-plugins.zip
2017-09-14 13:01:26,718  INFO [main] ServerBinaryDownloader:113 - Got server response
2017-09-14 13:01:26,769  INFO [main] ServerBinaryDownloader:121 - Piped the stream to admin/agent-plugins.zip
2017-09-14 13:01:26,769  INFO [main] PerfTimer:53 - Performance: Downloading new admin/agent-plugins.zip with md5 signature: [removed] took 88ms
2017-09-14 13:01:26,808  INFO [main] ServerBinaryDownloader:106 - Downloading tfs-impl.jar
2017-09-14 13:01:26,849  INFO [main] ServerBinaryDownloader:113 - Got server response
2017-09-14 13:01:27,580  INFO [main] ServerBinaryDownloader:121 - Piped the stream to admin/tfs-impl.jar
2017-09-14 13:01:27,581  INFO [main] PerfTimer:53 - Performance: Downloading new admin/tfs-impl.jar with md5 signature: [removed] == took 773ms
2017-09-14 13:01:27,589  INFO [main] AgentProcessParentImpl:69 - Launching Agent with command: [jvm path]/jre1.8.0_131/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom -Dagent.plugins.md5=[removed] -Dagent.binary.md5=[removed]== -Dagent.launcher.md5=[removed]== -Dagent.tfs.md5=[removed]== -jar agent.jar -serverUrl https://[vf go server]:[vf go port]/go -sslVerificationMode NONE
```

**Comment by ketan** [comment]
If you're running the agent via zip file `./agent.sh`, can you use `GO_AGENT_SYSTEM_PROPERTIES` instead of `AGENT_STARTUP_ARGS`.

The `AGENT_STARTUP_ARGS` is an internal variable, sorry to create confusion.

**Comment by dnewhook** [comment]
Success!  I used GO_AGENT_SYSTEM_PROPERTIES and added Dhttp & Dhttps parameters.

```
2017-09-14 16:39:07,292  INFO [main] AgentControllerFactory:102 - Connecting to server using HTTP(S)
2017-09-14 16:39:07,335  INFO [main] TimerFactoryBean:97 - Initializing Timer
2017-09-14 16:39:07,338  INFO [main] TimerFactoryBean:97 - Initializing Timer
2017-09-14 16:39:07,340  INFO [main] TimerFactoryBean:97 - Initializing Timer
2017-09-14 16:39:08,557  INFO [loopThread] SslInfrastructureService:92 - [Agent Registration] Starting to register agent.
2017-09-14 16:39:29,458  INFO [loopThread] SslInfrastructureService:191 - This agent is now approved by the server.
2017-09-14 16:39:29,543  INFO [loopThread] SslInfrastructureService:124 - [Agent Registration] Retrieved registration from Go server.
```

Agent is registered - going to do some basic testing to see if we can run the same pipelines.

Thank-you.

**Comment by ketan** [comment]
If things work file, let me know and I'll merge this in.

**Comment by ketan** [comment]
> Agent is registered - going to do some basic testing to see if we can run the same pipelines.

Wanted to follow up if you can report if everything works as expected. I don't want to merge this change late in the release.

**Comment by dnewhook** [comment]
We are still testing - having some troubles passing the parameters to the windows agent with wrapper-properties.conf.  We suspect this is due to a lack of experience deploying windows agents more than anything else.  We've been playing around with the following directives in the file without success.  Looks like the agent never starts - the launcher gets stuck trying to fetch jars from the server (connection timed out).  Looks like Launcher is not going via the proxy (our windows server has no connectivity to gocd).  Going to try with the zip file on windows next.

```
wrapper.java.additional.2=-Dhttps.proxyHost=192.168.178.100
wrapper.java.additional.3=-Dhttps.proxyPort=3128

wrapper.app.parameter.4=-sslVerificationMode
wrapper.app.parameter.5=FULL
wrapper.app.parameter.6=-Dhttps.proxyHost=192.168.178.100
wrapper.app.parameter.7=-Dhttps.proxyPort=3128
wrapper.app.parameter.8=-rootCertFile
wrapper.app.parameter.9=D:\Program Files\go_ca\ca.crt

set.AGENT_BOOTSTRAPPER_ARGS=%AGENT_BOOTSTRAPPER_ARGS% -Dhttps.proxyHost=192.168.178.100 -Dhttps.proxyPort=3128

set.AGENT_STARTUP_ARGS=%AGENT_STARTUP_ARGS% -Dhttps.proxyHost=192.168.178.100 -Dhttps.proxyPort=3128
```

**Comment by ketan** [comment]
For windows, here's what you need to do. Create a `config/wrapper-properties.conf` in the install directory with the following contents:

```
# yes `1000` 
wrapper.java.additional.1000=-Dhttps.proxyHost=...
wrapper.java.additional.1001=-Dhttps.proxyPort=...
set.AGENT_STARTUP_ARGS=-Xms128m -Xmx256m -Dhttps.proxyHost=... -Dhttps.proxyPort=...
```

We hope to clean and improve some of these configurations to be consistent between windows an linux in the next release or two.

**Comment by ketan** [comment]
Merging since @rajiesh has tested it. If there are specific cases where this does not work as expected, we can possibly fix things on a case-by-case basis.

**Comment by Hashfyre** [comment]
What file needs to be created on OS-X to get this done, the official docs here: https://docs.gocd.org/current/installation/configure-agent-proxy.html
Only mentions Linux and Windows.

**Comment by ketan** [comment]
We've redone some aspects of the macOS installers. For the version you're currently on. You should be able to tweak this block https://github.com/gocd/gocd/blob/18.11.0/installers/go-server/osx/Info.plist#L54

by adding the following:

```xml
  <dict>
    <key>https.proxyHost</key>
    <string>...</string>
    <key>https.proxyPort<key>
    <string>...</string>
    ....
  </dict>
```

Please be advised that this will break the next release. We'll make sure to update the documentation to be able to change the jvm arguments for osx.

**Pull request merged**
