### PR TITLE
Force encoding of the console log to utf-8

### PR DESCRIPTION
**Pull request by ketan**
* ensure that the output is read in utf-8
* ensure that it is transmitted in utf-8
* ensure that it is written AS-IS byte-by-byte
* ensure that it is read in utf-8 before being rendered to the browser

### CODE REVIEW

**Comment by arvindsv** [comment]
Looks good to me. I guess there's no easy way for us to enable #2900.

**Comment by ketan** [comment]
> I guess there's no easy way for us to enable #2900.

Not sure I understand. Care to elaborate?

**Comment by arvindsv** [comment]
#2900 is about non-UTF8 characters being coerced into UTF-8, essentially, as far as I understand. Of course, there will be a bit about the console log GET method forcibly returning UTF-8 and the page forced to UTF-8 (in the view).

This PR seems to make that a little more hard-coded. Especially the changes to ConsoleService and StreamPumper. Just based on my quick look.

I understand that encoding is more about how you interpret a string than make any changes to it and that the bytes/pairs of the Cyrillic and Chinese characters are not really lost, but shown assuming it's UTF-8. But, as I said, this assumes all console output to be UTF-8, right?

**Comment by ketan** [comment]
> But, as I said, this assumes all console output to be UTF-8, right?

Correct, I was talking about this with @maheshp yesterday. And realized that this does not feel like it's the right approach to the problem. Here's what we discussed —

GoCD "reads" bytes from various streams. The encoding of these streams is not directly controlled by GoCD —

* password file typically containing usernames with multi-byte chars (server)
* SCM material process execution (`git log`, `svn log`, `hg log`, etc) (server). SCM updates on the agent can probably be ignored, since GoCD does not read the output of such commands.
* Build script execution (agent)

Git, SVN and HG support a `--encoding` argument to override the commit encoding. However all of them claim that the encoding defaults to utf-8. And encourage that you users use that encoding. Git specifically stores the encoding of each commit object. 

For `git` — see [this](https://git-scm.com/docs/git-commit/#_discussion) and [this](https://git-scm.com/docs/git-log/#_discussion).
For `hg` - see [hg(1)](https://linux.die.net/man/1/hg) (search for encoding)
For `svn` - see http://svnbook.red-bean.com/en/1.7/svn.ref.svn.html

As far as reading these console outputs is concerned — I'm not sure what's the best way to proceed, I'm sure `jGit` can probably help us read the `git log` output in a better manner. We might need to look at other libraries for svn, hg and p4.

As far as console output for builds is concerned, we might need to consider not reading the output as `utf-8`. However that'd mean we figure out(not sure how), or allow the user to specify what the encoding is(not sure where, i.e. on each agent, or per job) — and more importantly, save that encoding (on the server) along with the console log, so we can render it in the correct encoding when sending it to the browser (on the job detail page).

**Pull request closed without merging**
