### PR TITLE
 Added validation for users cannot be blank (#1646)

### PR DESCRIPTION
**Pull request by varshavaradarajan**
* Added a new migration to remove existing blank users

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
Updated PR adding all cases for user to be blank.

**Comment by varshavaradarajan** [comment]
Have to update copyright in one of the files. Will do so after the build-linux-PR finishes building.

**Comment by ketan** [comment]
@varshavaradarajan — is this ready to review?

**Comment by varshavaradarajan** [comment]
Yes.

**Comment by ketan** [comment]
@arvindsv @jyotisingh — I've merged this so we can run the extensive set of smokes and regression. But I'm left to wonder if we're breaking compatibility [here](https://github.com/gocd/gocd/pull/1775/files#diff-dea6f2dfc75a0ab60ebc7dbb6c7f51bcR1166).

**Comment by arvindsv** [comment]
I don't think I have full context on this. Why would removing empty tags break compatibility? I mean, we don't really remove any information, right?

**Comment by varshavaradarajan** [comment]
It removes only the empty tags within <authorization>.

**Pull request merged**
