### PR TITLE
#854 - Removed validation on Single Hash.

### PR DESCRIPTION
**Pull request by mdaliejaz**
* Validation doesn't fail for a single hash.
* Removed/Modified/Added test for new changes.

### CODE REVIEW

**Comment by mdaliejaz** [comment]
Personal went green.

**Comment by arvindsv** [comment]
@mdaliejaz, I'm guessing you'll work with someone to get this accepted. You mentioned migration of config in #854. But, I don't see that happening here. So, with this change, the validation seems to be removed, right? So, # is allowed, as well as ##. I guess ## converts to #. However, for new users of this, the fact that ## converts to # is confusing and unexpected. Right?

Once the config migration is done, then all ## in config will be replaced, and this change is meaningful. What do you think? If you agree, then, should config migration be part of this?

**Comment by mdaliejaz** [comment]
@arvindsv Sorry, I forgot to update here.
Yes, there is more work required. I intended to complete both the steps mentioned in #854, and they should go together in a release.
Since this wasn't going in 15.1, I parked the story for sometime due to other priorities for 15.1, but forgot to update it over here.
I can close this PR and send another PR with all the commits together on a later date, or this PR can be merged later when other commits are pushed :) Let me know what you think.

**Comment by arvindsv** [comment]
Yes, I think closing it for now, makes sense.

**Comment by mdaliejaz** [comment]
Cool. Closing it for now :)

**Pull request closed without merging**
