### PR TITLE
Remove warnings

### PR DESCRIPTION
**Pull request by cv**
This is a simple PR to remove warnings generated by IntelliJ IDEA inspections. I took care to make each automated warning removal as a separate commit, so it'd be slightly easier to review (the combined diff might be a little overwhelming, mind).

No behavior is expected to change as a result of this.

### CODE REVIEW

**Comment by ketan** [comment]
Some of the usages of lamdas and method references may fail because of the old version of spring we use.

I've kicked off a build so you should be able to see some failures if there are any. Please login using the guest login icon on the login page or use `view:password` as the login credentials.

**Comment by cv** [comment]
Thanks, @ketan! I'll go through the failing tests - looks like there were some related to lambdas, indeed - and update the PR accordingly.

**Comment by ketan** [comment]
@cv — is there still interest in cleaning this?

**Comment by cv** [comment]
I think I'd have to start over - probably a lot easier than solving the merge conflicts manually. Closing this and booking some time later this month for it. Wish me luck! :)

**Pull request closed without merging**
