### PR TITLE
Show multiple pipeline level analytics if the plugin supports multiple pipeline level analytics

### PR DESCRIPTION
**Pull request by GaneshSPatil**
More information: https://twstudios.mingle-staging.thoughtworks.com/projects/sf_dev_team/cards/291

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
@maheshp -- this PR takes care of showing all the pipeline level analytics from all the plugins on the pipeline tile.

**_Note:_** On the Pipeline Tab under analytics page, the value of the chart is hardcoded to ["Pipeline Duration Chart"](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/webpack/views/analytics/pipeline_metrics.js.msx#L45). I will send another PR to fix the pipeline tab to show all the available pipeline level analytics (after https://github.com/gocd/gocd/pull/4671 is merged).

**Comment by maheshp** [comment]
@GaneshSPatil is it ok put this PR on hold till @tinozza finalises the designs. We need to handle multiple pipeline analytics both on the pipeline dashboard(which your PR does) as well as on the Analytics dashboard.

**Comment by GaneshSPatil** [comment]
@maheshp sure!

**Comment by GaneshSPatil** [comment]
Closing this PR as the designs for the same isn't ready. I've created a GitHub issue (https://github.com/gocd/gocd/issues/4898) to track the same.

Will send another PR according to the new design.

**Pull request closed without merging**
