### PR TITLE
Remove the inoperable failures tab from job build detail

### LINKED ISSUE #9578: Junit Failures not showing up on the Failures Tab
##### Summary
Despite showing that there are failures on the tests tab...
image
No failures are displayed in the failures tab.
image

##### Environment

WinSrv2019 GoCD 21.2.0
```plain
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="440" tests="1170" time="182.609375">
	<testsuite assertions="56" disabled="0" errors="0" failures="34" name="Files" skipped="0" tests="90" time="14.046875" hostname="linux-64-centos-60" id="linux-64-centos-60">
```

###### Basic environment details

* Go Version: 21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f)
* JAVA Version: 15.0.2
* OS: winsrv2019 
* Browser vendor and version (if relevant): Tested on a few browsers.

##### Steps to Reproduce
1.  Generating JunitXML using python plugin https://pypi.org/project/junit-xml/
2.  Output as a TEST artifact in GoCD - ends up in testoutput
3. 
4. 

##### Expected Results
Failures are listed in the failures tab.

##### Actual Results
Nada

### PR DESCRIPTION
**Pull request by chadlwilson**
Issue: Fixes #9578

Description:

As discussed at #9599 and #9578 this tab hasn't been working since GoCD 19.10; i.e it always considers there to be no failing tests. Based on discussion at #9599 this is to be removed, along with any of the style seemingly only used by this particular tab.

- [X] Removed tab
- [X] Removed unused style and JS
- [X] Correct in-software help text when manually assembling pipelines
- [X] Sanity check locally
- [X] Ensure automated tests are passing
- [X] Tested look and feel + tab functionality OK
- [X] Tested XML test reports still getting parsed for Tests tab (see https://docs.gocd.org/21.3.0/faq/dev_understand_why_build_broken.html#with-the-tests-tab )
- [X] Docs update / PR - done in https://github.com/gocd/docs.go.cd/pull/597, mainly at https://docs.gocd.org/21.3.0/faq/dev_understand_why_build_broken.html

For now I have left the Tests tab in tact. Possibly we should remove this too; however this is a start :-)

### CODE REVIEW

**Review by yulian-tw — APPROVED** [review]
The changes are LGTM. They are all driven by removal of file `server/src/main/webapp/WEB-INF/vm/build_detail/_failures.vm`.

**Review by kritika-singh3 — APPROVED** [review]
Code wise - LGTM. Haven't had the time to run it locally (but I'm hoping you would have done the same :) )

**Review by arvindsv — APPROVED** [review]
Looks good.

I tried to see if there is a functional test that will fail for this. I think not. The closest one I saw was [this one](https://github.com/gocd/ruby-functional-tests/blob/4ce789b4c4b96ed9d9f19eb5a6125adbd6a2af53/specs/ArtifactMD5VerificationFailure.spec) which is verifying failures in artifact verification.

It looks like the regression suite has already run on this change anyway. So, I think this is fine to merge.

**Comment by chadlwilson** [comment]
Yeah, I looked also and couldn't find any such tests, which probably explains how it was able to be broken into a bit of an inoperable state where it either just displays the console log if the job got into failed state or incorrectly displays "No failed tests".

**Pull request merged**
