### PR TITLE
Add support for plugin and package materials on Comparison SPA

### PR DESCRIPTION
**Pull request by kritika-singh3**
Issue: #7754

Description:
 - The plugin and package materials were not supported on the SPA. Added support for that
 - To uniquely identify such materials - added a `display_type` and `description` on the material json in the comparison result ( bumped up the API to v2)

API Doc: https://github.com/gocd/api.go.cd/pull/625

### CODE REVIEW

**Comment by maheshp** [comment]
@kritika-singh3 probably this should have been a review comment, but I think `display_type` and `description` should be under `attributes` for each material.

**Comment by kritika-singh3** [comment]
@maheshp `type` and `display_type` has a minor difference. Hence, decided to keep them at the same level.
Let me know if you think otherwise, will raise a PR to make the changes.

**Comment by maheshp** [comment]
@kritika-singh3 I would probably move it to `attributes`.

**Comment by maheshp** [comment]
Verified on - GoCD Version: 20.2.0 (11325-dcb8fa908ba08d4f82de172bc942de6f2ca1e28d).

**Pull request merged**
