### PR TITLE
Remove elastic agent profiles API v1 (#5538)

### PR DESCRIPTION
**Pull request by GaneshSPatil**

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
\cc: @maheshp @arvindsv

**Comment by arvindsv** [comment]
Does it make sense to show a good message in the response body, when API versions are deprecated?

**Comment by maheshp** [comment]
> Does it make sense to show a good message in the response body, when API versions are deprecated?
I would prefer not changing the response body, probably consider an appropriate response code.

**Comment by GaneshSPatil** [comment]
@maheshp @arvindsv -- can we add a custom response header for deprecated APIs?

```
X-GoCD-Deprecated-API: true
```

Though, I am not sure how many people will pay attention to the response headers.

**Comment by arvindsv** [comment]
Depends on what the current response is. If it's easy to understand that the version is no longer supported, then it's ok.

**Pull request merged**
