### PR TITLE
Secret configuration SPA

### PR DESCRIPTION
**Pull request by kritika-singh3**
Added toggle for Secret Config SPA. The default toggle value is `false`.
To turn it on:
```bash
curl http://localhost:8153/go/api/admin/feature_toggles/show_secret_config_spa -d toggle_value=on -H 'Confirm:true' -u admin:badger
```

### CODE REVIEW

**Comment by kritika-singh3** [comment]
Preview:
secret_config_spa

**Comment by arvindsv** [comment]
@kritika-singh3 Can you add a placeholder for the "Id" field? Also, should the file path itself be encrypted? What do we gain from that? It would end up making it confusing, won't it?

**Comment by kritika-singh3** [comment]
> Can you add a placeholder for the "Id" field? As in `<input placeholder="..."/>`. 

Will do.

> Also, should the file path itself be encrypted? What do we gain from that? It would end up making it confusing, won't it?

I agree. Will set  `secure=false` in the file plugin.

**Comment by kritika-singh3** [comment]
Updated Preview:
secret_config_spa

**Pull request merged**
