### PR TITLE
Show config repo info for pipelines in dashboard

### PR DESCRIPTION
**Pull request by viraj2712**
Issue: #6125 

Show config repo id and material URL for the pipelines defined using config repo on the dashboard.
This information will be available in the hover message on the settings icon.

### CODE REVIEW

**Comment by viraj2712** [comment]
Screenshot of the hover message:

Screenshot 2019-07-04 at 10 32 39 AM

**Comment by viraj2712** [comment]
Screenshot of the updated hover message:

Screenshot 2019-09-23 at 4 54 37 PM

\cc: @adityasood @maheshp

**Comment by viraj2712** [comment]
Updated hover message for pipelines defined in config repository:

config_repo_hover_msg

\cc: @adityasood

**Comment by viraj2712** [comment]
Info icon instead of gear icon:

1.
Screenshot 2019-10-03 at 11 20 51 AM

2.
Screenshot 2019-10-03 at 11 26 55 AM

\cc: @adityasood  @arvindsv @maheshp

**Comment by adityasood** [comment]
I like the second option

**Comment by akshaydewan** [comment]
I think the first _i_ icon is more consistent, if you look at the kitchen sink tooltips and icons. But I'm not too picky.

If you do choose the second option, I think the tooltip should be properly aligned with the icon.

**Comment by viraj2712** [comment]
we're going with the first option

**Comment by viraj2712** [comment]
Hover message with improved styling:
(Showing url value next to `Url:` text)

Screenshot 2019-10-16 at 3 38 33 PM

\cc: @adityasood @maheshp @bdpiparva

**Pull request merged**
