### PR TITLE
Rename `exec` tasks `command` attribute to `executable`.

### PR DESCRIPTION
**Pull request by ketan**
* and some other formatting changes.

### CODE REVIEW

**Comment by jyotisingh** [comment]
Changes look good to me. Can we rename this in `ExecTask` and xml too for consistency's sake?

**Comment by ketan** [comment]
> Changes look good to me. Can we rename this in ExecTask and xml too for consistency's sake?

Can we do this for 16.1?

**Comment by jyotisingh** [comment]
@ketan - will you be submitting another PR to take care of renaming the attribute in xml and ExecTask class or updating this one? Also, you need to resolve some conflicts on this one.

**Comment by ketan** [comment]
I've resolved conflicts, however have to create an ApiV2 for this change, which I'll do later.

Also, opened #1755 to rename the `<exec/>` task attribute, if you're OK with that change, I'll update both the PRs to use ApiV2

**Comment by jyotisingh** [comment]
Check comment on #1755

**Pull request closed without merging**
