### PR TITLE
Update the `resetWorkingDirectory` process

### PR DESCRIPTION
**Pull request by akshaydewan**
Issue #5856
- Use submodule deinit instead of manually removing submodules from .git/config
- Update few other commands using newer submodule command arguments like --recursive and --foreach
- Do a git clean -dffx instead of -dff

### CODE REVIEW

**Comment by ketan** [comment]
Not so sure about the change to git clean. There was a long conversation about it #1059

**Comment by akshaydewan** [comment]
Based on that thread, I can add an [agent side toggle](https://github.com/gocd/gocd/pull/5666) for reverting to the old behaviour for git clean.

**Comment by akshaydewan** [comment]
Currently the linux build is failing with the error log showing:
```
org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
	Error performing command: --- Command ---
git submodule deinit -f --all
--- Environment ---
{}
--- INPUT ----


--- EXIT CODE (1) ---
--- STANDARD OUT ---

--- STANDARD ERR ---
STDERR: You need to run this command from the toplevel of the working tree.
---
```

I'm not sure if there's some parent working directory that is under version control, or if the path is somehow wrong when running the test on CI.

Moreover, the git version on CentOS 6 is `1.7.1`, which doesn't support `submodule deinit`. We will also need to update git to at least 1.9 on the build agents.

**Comment by ketan** [comment]
Tests run in a temporary directory which is under `project-name/tmp`

**Pull request merged**
