### PR TITLE
#838 - Removing extra validation step while creating

### PR DESCRIPTION
**Pull request by zabil**
*goConfigFileDao* return a valid config file. Writing to the output stream to create the document root can skip the validation.

### CODE REVIEW

**Comment by mdaliejaz** [comment]
Reviewed it. Looks fine :)
Will however wait for the code walkthrough to happen before merging.

**Comment by arvindsv** [comment]
@zabil, @mdaliejaz: It seems like a wrong merge has happened. It's showing too many commits in this PR.

**Comment by mdaliejaz** [comment]
Yeah, I think the PR has been rebased.
@zabil What about sending a fresh PR with only the related commits?

**Comment by zabil** [comment]
Did a rebase. Screwed up the history. Resending this.

**Comment by zabil** [comment]
Yeah I screwed up during rebase.

New one up here.
https://github.com/gocd/gocd/pull/941

**Pull request closed without merging**
